[dados] pnad_populacao
basedosdados/mais pull request #1013
Opened 2021-12-10 00:00 UTC by crislanealves

2021-12-11 12:14 UTC, rdahis commented
@crislanealves sabe dizer o que rolou com os erros?

2021-12-11 19:27 UTC, crislanealves commented
@rdahis foi aqui, eu acho

2021-12-12 13:31 UTC, rdahis commented
Tudo certo, exceto que é melhor botar a unidade de população em 1 pessoa, ao invés de 1000 pessoas =/

2021-12-13 03:18 UTC, lucasnascm commented on bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_config.yaml
> +      covered_by_dictionary: no
Eu entendo que aqui e nas demais variáveis que estejam contidas em diretórios, seja `yes` uma vez que o dicionário é a tabela em `br_bd_diretorios_`

2021-12-13 03:18 UTC, lucasnascm commented on bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_config.yaml
> +      is_partition: no
Eu não sei se chega a ser um problema, mas esse campo é `false`

2021-12-13 11:58 UTC, rdahis commented on bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_config.yaml
> +      covered_by_dictionary: no
Em princípio eu estava separando cobertura por dicionário vs cobertura em diretórios. Pra ficar claro que existe uma "coisa além" que é ser uma entidade no banco inteiro. Podemos falar disso na reunião.

2021-12-15 01:32 UTC, crislanealves commented
@rdahis alterações feitas.

2021-12-15 11:54 UTC, rdahis commented on bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/table_config.yaml
> +table_id: ano_regiao_metropolitana_raca_cor
Tá certo aqui? Não é `grupo_idade`?

2021-12-15 19:36 UTC, crislanealves commented on bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/table_config.yaml
> +table_id: ano_regiao_metropolitana_raca_cor
☑️

2021-12-19 15:31 UTC, rdahis requested changes

2021-12-19 15:31 UTC, rdahis commented on bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_config.yaml
> +      measurement_unit:
Mais um detalhe aqui: todas as colunas `populacao` tem `measurement_unit=person`. Em inglês pois é uma chave das possíveis unidades de medida [aqui](https://github.com/basedosdados/website/blob/master/ckanext-basedosdados/ckanext/basedosdados/validator/available_options/measurement_unit.py).

2021-12-19 15:31 UTC, rdahis commented on bases/br_ibge_pnadc/ano_brasil_raca_cor/table_config.yaml
> +      measurement_unit:
```suggestion
      measurement_unit: year
```

2021-12-19 15:31 UTC, rdahis commented on bases/br_ibge_pnadc/ano_municipio_grupo_idade/table_config.yaml
> +entity: person
Melhor deixar todos esses `entity` vazios.

2021-12-19 15:31 UTC, rdahis commented on bases/br_ibge_pnadc/ano_municipio_grupo_idade/table_config.yaml
> +      measurement_unit:
```suggestion
      measurement_unit: year
```

2021-12-19 15:31 UTC, rdahis commented on bases/br_ibge_pnadc/ano_brasil_raca_cor/table_config.yaml
> +      measurement_unit:
Se aplica a todas as colunas `ano`!

2021-12-29 11:37 UTC, rdahis approved these changes

2021-12-29 11:41 UTC, merged

2021-12-29 11:53 UTC, rdahis commented
@crislanealves o `table approve` aqui falhou em publicar os metadados. Você pode rodar na mão aí o `basedosdados metadata publish` em produção para cada uma das tabelas? Os yamls tão prontos então deve ser rápido.

2021-12-29 20:08 UTC, crislanealves commented
@rdahis  :white_check_mark: