[dados] br_inep_formacao_docente
basedosdados/mais pull request #1019
Opened 2021-12-13 03:05 UTC by lucasnascm

2021-12-14 13:49 UTC, rdahis requested changes

2021-12-14 13:49 UTC, rdahis commented on bases/br_inep_formacao_docente/brasil/table_config.yaml
> +      covered_by_dictionary: yes
Só é `yes` quando a coluna for coberta pelo dicionário local do conjunto. Quando tiver nos diretórios é `no`.

2021-12-14 13:49 UTC, rdahis commented on bases/br_inep_formacao_docente/escola/table_config.yaml
> +      covered_by_dictionary: yes
Mesma coisa.

2021-12-14 13:49 UTC, rdahis commented on bases/br_inep_formacao_docente/escola/table_config.yaml
> +          column_name:
Aqui seria `nome`?

2021-12-14 13:49 UTC, rdahis commented on bases/br_inep_formacao_docente/escola/table_config.yaml
> +      covered_by_dictionary: yes
Mesma coisa.

2021-12-14 13:49 UTC, rdahis commented on bases/br_inep_formacao_docente/escola/table_config.yaml
> +      covered_by_dictionary: yes
Mesma coisa. etc.

2021-12-14 13:49 UTC, rdahis commented on bases/br_inep_formacao_docente/escola/table_config.yaml
> +      bigquery_type: int64
Aqui não seria `STRING` com dicionário?`

2021-12-14 13:49 UTC, rdahis commented on bases/br_inep_formacao_docente/municipio/publish.sql
> +SAFE_CAST(grupo AS INT64) grupo,
Mesma pergunta sobre tipo e dicionário.

2021-12-14 15:39 UTC, lucasnascm commented on bases/br_inep_formacao_docente/escola/table_config.yaml
> +      bigquery_type: int64
Até pode ser considerada como `string`, mas os valores de 1 a 5 eu especifiquei na própria descrição da variável`então deixei desse jeito, já que não existe dicionário, uma vez que tudo é descrito na base

2021-12-15 02:51 UTC, lucasnascm commented
@rdahis tá redondo aqui! dicionário incluso tbm

2021-12-15 12:03 UTC, rdahis approved these changes

2021-12-15 12:03 UTC, merged