[dados] mundo_bm_learning_poverty
basedosdados/mais pull request #1031
Opened 2021-12-20 22:06 UTC by lucasnascm

2021-12-20 22:16 UTC, rdahis requested changes

2021-12-20 22:16 UTC, rdahis commented on bases/mundo_bm_learning_poverty/dataset_config.yaml
> +organization: banco-mundial
`mundo-bm`

2021-12-20 22:16 UTC, rdahis commented on bases/mundo_bm_learning_poverty/pais/table_config.yaml
> +          column_name:
Não sabemos aqui?

2021-12-21 12:15 UTC, rdahis approved these changes

2021-12-21 12:15 UTC, merged

2021-12-21 12:29 UTC, rdahis commented
@d116626 aqui o `approve` deu certo mas parece não ter publicado os metadados no site (https://basedosdados.org/dataset?organization=mundo-bm&order_by=score). Sabe dizer o que rolou?

2021-12-21 12:30 UTC, rdahis commented
Mentira, ele publicou o conjunto aqui (https://basedosdados.org/dataset/mundo-bm-learning-poverty) mas nenhum metadado dentro.

2021-12-21 12:51 UTC, d116626 commented
> @d116626 aqui o `approve` deu certo mas parece não ter publicado os metadados no site (https://basedosdados.org/dataset?organization=mundo-bm&order_by=score). Sabe dizer o que rolou?

O  `tb-approve` quase sempre vai parecer que deu tudo certo, vc só vai ter certeza olhando os logs das actions. Olha o erro que apareceu lá

```sh

  File "/home/runner/work/mais/mais/.github/workflows/table-approve/table_approve.py", line 345, in table_approve
    md.validate()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/***/upload/metadata.py", line 355, in validate
    raise BaseDosDadosException(message)
***.exceptions.BaseDosDadosException: /home/runner/work/mais/mais/bases
/mundo_bm_learning_poverty/pais/table_config.yaml has validation errors: {'mundo-bm-
learning-poverty': [{'loc': ['resources', 0, 'BdmTable', 'columns', 1, 'directory_column', 
'dataset_id'], 'msg': "value is not a valid enumeration member; permitted: 
'br_bd_diretorios_brasil', 'br_bd_diretorios_data_tempo'", 'type': 'type_error.enum', 'ctx': 
{'enum_values': ['br_bd_diretorios_brasil', 'br_bd_diretorios_data_tempo']}}, {'loc': 
['resources', 0, 'BdmTable', 'columns'], 'msg': 'str type expected', 'type': 'type_error.str'}]}

```

2021-12-21 13:55 UTC, d116626 commented on bases/mundo_bm_learning_poverty/pais/table_config.yaml
> +          dataset_id: br_bd_diretorios_mundo
@rdahis aqui o problema, esse diretório n ta no `avaliable_options`: https://basedosdados.org/api/3/action/bd_available_options

O validate que pegou isso. A action que roda o `metadata.validdate `automaticamente n acusou isso?

2021-12-21 14:37 UTC, rdahis commented on bases/mundo_bm_learning_poverty/pais/table_config.yaml
> +          dataset_id: br_bd_diretorios_mundo
Confesso que não tinha prestado atenção na action de `metadata.validate`. Vamos olhar melhor agora!

2021-12-21 14:38 UTC, d116626 commented on bases/mundo_bm_learning_poverty/pais/table_config.yaml
> +          dataset_id: br_bd_diretorios_mundo
é bom rodar local tbm