[dados] br_ana_reservatorios
basedosdados/mais pull request #1052
Opened 2022-01-12 00:57 UTC by crislanealves

Não consegui gerar o `metadata_modified `de jeito nenhum. 

:bulb:  ?

2022-01-12 10:50 UTC, rdahis commented
Chegou a rodar o `metadata create`? Assim ele gera um yaml local com o metadata_modified correto. E você pode preencher o resto dos metadados em cima.

O que eu recomendo para não perder trabalho é copiar o yaml que você já preencheu pra fora da pasta, rodar o `metadata create`, e depois copiar e colar tudo a não ser o `metadata_modified` pra dentro.

2022-01-12 10:58 UTC, crislanealves commented
Sim. Eu fiz isso, mas não tá dando certo dessa fez. Cheguei até tentar criar o conjunto no site e rodar tudo depois pra ver se puxava, mas também não rolou. O _metadata validate_ tá retornando esse erro:

```bash

Local metadata is invalid. Please check the traceback below for more information on how to fix it:

BaseDosDadosException("C:\\Users\\Crislane\\bases\\br_ana_reservatorios\\sin\\table_config.yaml has validation errors: {'br-ana-reservatorios': [{'loc': ['owner_org'], 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}]}")
```
Estranho que ele passou apontar isso depois que abri o PR. Antes disso tava tudo ok.

2022-01-12 11:45 UTC, rdahis commented
Estranho mesmo até porque o conjunto já está criado aqui: https://basedosdados.org/dataset/br-ana-eservatorios e a tabela também.

O que acontece se você só rodar o `metadata create`? Ele puxa um yaml normal?

2022-01-12 11:48 UTC, crislanealves commented
É que eu criei o conjunto depois para ver se ele puxava, mas não rolou. 

- Depois de rodar o _metadata create_ ele retorna o `yaml ` com `metadata_modified` vazio.

2022-01-12 11:51 UTC, rdahis commented
Matei. Tem um typo no nome do conjunto já no site: https://basedosdados.org/dataset/br-ana-eservatorios era pra ser https://basedosdados.org/dataset/br-ana-reservatorios.

2022-01-12 12:00 UTC, crislanealves commented
💥

2022-01-12 13:51 UTC, rdahis commented
Show avisa por favor quando tiver atualizado os metadados de acordo aqui!

2022-01-12 15:00 UTC, crislanealves commented
Acho que foi aqui

2022-01-12 15:01 UTC, crislanealves commented
@rdahis  acho que foi aqui

2022-01-12 18:50 UTC, rdahis requested changes

2022-01-12 18:50 UTC, rdahis commented on bases/br_ana_reservatorios/sin/table_config.yaml
> +      measurement_unit: day
```suggestion
      measurement_unit: 
```

2022-01-12 18:50 UTC, rdahis commented on bases/br_ana_reservatorios/sin/table_config.yaml
> +    - name: codigo_reservatorio
Pode se chamar `id_reservatorio`? Daria pra criarmos um diretório de reservatórios?

2022-01-12 18:50 UTC, rdahis commented on bases/br_ana_reservatorios/sin/table_config.yaml
> +    - name: reservatorio
```suggestion
    - name: nome_reservatorio
```

2022-01-12 18:50 UTC, rdahis commented on bases/br_ana_reservatorios/sin/table_config.yaml
> +      measurement_unit: m
Acho que a chave para metro é `meter`.

2022-01-12 23:08 UTC, crislanealves commented on bases/br_ana_reservatorios/sin/table_config.yaml
> +    - name: codigo_reservatorio
Hm... tem mais 3 reservatórios. Se pá, acho que rola sim.

2022-01-12 23:10 UTC, crislanealves commented on bases/br_ana_reservatorios/sin/table_config.yaml
> +      measurement_unit: m
Pois é, fiquei dividida com relação a isso. [Aqui](https://github.com/basedosdados/website/blob/master/ckanext-basedosdados/ckanext/basedosdados/validator/available_options/measurement_unit.py) tem ``m`` e ``meter2``. Muda para `meter`?

2022-01-13 00:45 UTC, crislanealves commented
@rdahis mudei de `m` para `meter`

2022-01-17 17:49 UTC, rdahis commented
@crislanealves já pode fazer o `metadata publish` aí.

2022-01-19 10:33 UTC, crislanealves commented
> @crislanealves já pode fazer o `metadata publish` aí.

@rdahis tudo certo lá no site.

2022-01-19 10:57 UTC, rdahis commented
Sucesso!

2022-01-19 11:12 UTC, rdahis approved these changes

2022-01-19 11:13 UTC, merged