[infra] r-package - primeiro esboço da vignette 1
basedosdados/mais pull request #1054
Opened 2022-01-12 21:05 UTC by mavalentim

Quero deixar o material pra uso da basedosdados como vignettes. Esse primeiro cria uma geralzona, mas depois vou criando mais especificas para bases e funcoes

2022-01-12 21:05 UTC, mavalentim commented
PS: Deu 1 erro no `check` para o pacote 'tibble'. Devíamos nos preocupar?

2022-01-13 00:26 UTC, pedrocava commented
> PS: Deu 1 erro no `check` para o pacote 'tibble'. Devíamos nos preocupar?

Printa o erro aqui?

2022-03-18 04:11 UTC, pedrocava commented
Vou revisar no final de semana, com calma :)

2022-03-21 18:15 UTC, pedrocava requested changes

2022-03-21 18:15 UTC, pedrocava commented on r-package/vignettes/basedosdados-basic-tutorial.Rmd
> +municipality. All of these datasets are available at Google Cloud,the R package
espaço na vírgula

2022-03-21 18:15 UTC, pedrocava commented on r-package/vignettes/basedosdados-basic-tutorial.Rmd
> +### Our one requisite
usa só um `#` ao invés de `###`

2022-03-21 18:15 UTC, pedrocava commented on r-package/vignettes/basedosdados-basic-tutorial.Rmd
> +2. The second way is by using a argument present in all our functions called
Na verdade passar o `billing_id` não é exatamente "setup" o ambiente. Acho interessante você falar do item 1 como o *único* jeito de setupar tudo e depois citar que você pode passar o id como argumento se não quiser.

2022-03-21 18:15 UTC, pedrocava commented on r-package/vignettes/basedosdados-basic-tutorial.Rmd
> +### Basic functions: `read_sql()` and `download()`
Mesma coisa de apenas um `#`

2022-03-21 18:15 UTC, pedrocava commented on r-package/vignettes/basedosdados-basic-tutorial.Rmd
> +#### Reading SQL queries into datasets
"Directly querying the datalake with SQL" é um pouco mais claro

2022-03-21 18:15 UTC, pedrocava commented on r-package/vignettes/basedosdados-basic-tutorial.Rmd
> +##### Opening an aggregated table
"Opening" é uma tradução literal de "abrir a base", procura um verbo mais apropriado

2022-03-21 18:15 UTC, pedrocava commented on r-package/vignettes/basedosdados-basic-tutorial.Rmd
> +#### Downloading datasets from queries
Importante enfatizar/ framear a questão aqui que `read_sql` retorna em memória e `download` desencadeia o efeito colateral de escrever no disco.

2022-04-27 13:39 UTC, rdahis commented
@mavalentim bora implementar essa revisão para dar merge?

2022-10-04 09:59 UTC, crislanealves commented
@arthurfg e @gustavoalcantara querem ajudar a tocar isso aqui? @pedrocava e @mavalentim o que falta pra finalizar?

2022-10-30 19:56 UTC, closed without merging