[dados] br_ibge_pnad.microdados_domicilio_pessoa
basedosdados/mais pull request #1135
Opened 2022-02-24 22:36 UTC by crislanealves

2022-02-25 12:57 UTC, rdahis commented on bases/br_ibge_pnad/microdados_compatibilizados_domicilio/table_config.yaml
> +observation_level:
Aqui é:
```
- entity: household
```

2022-02-25 12:58 UTC, rdahis commented on bases/br_ibge_pnad/microdados_compatibilizados_domicilio/table_config.yaml
> +    - name: id_regiao
Deveria vir acima de `sigla_uf`.

2022-02-25 13:00 UTC, rdahis commented on bases/br_ibge_pnad/microdados_compatibilizados_domicilio/table_config.yaml
> +update_frequency: one_year
```suggestion
update_frequency: unique
```

2022-02-25 13:03 UTC, rdahis commented on bases/br_ibge_pnad/microdados_compatibilizados_pessoa/table_config.yaml
> +observation_level:
```suggestion
observation_level:
  - entity: person
```

2022-02-25 13:04 UTC, rdahis commented on bases/br_ibge_pnad/microdados_compatibilizados_pessoa/table_config.yaml
> +    - name: id_regiao
Vir acima de `sigla_uf`

2022-02-25 13:05 UTC, rdahis requested changes
Alguns comentários abaixo!

2022-02-25 20:34 UTC, rdahis commented
Nessa query ainda tá com a ordem errada de `id_regiao`. Chegou a subir os csvs novos?

```sql
SELECT * FROM `basedosdados-dev.br_ibge_pnad.microdados_compatibilizados_domicilio` LIMIT 1000
```

2022-02-25 20:47 UTC, crislanealves commented
> Nessa query ainda tá com a ordem errada de `id_regiao`. Chegou a subir os csvs novos?
> 
> ```sql
> SELECT * FROM `basedosdados-dev.br_ibge_pnad.microdados_compatibilizados_domicilio` LIMIT 1000
> ```

Sim! Faltou o publish. Tenta agora.

2022-02-25 21:12 UTC, rdahis commented
Ainda faltou ficar acima do `id_uf` lá =(

2022-03-01 12:38 UTC, rdahis approved these changes

2022-03-01 12:38 UTC, merged