[dados] br_inep_saeb.proficiencia
basedosdados/mais pull request #1142
Opened 2022-03-07 10:55 UTC by lucasnascm

2022-03-08 20:18 UTC, crislanealves commented on bases/br_inep_saeb/proficiencia/publish.sql
> +SAFE_CAST(id_regiao AS STRING) id_regiao,
`id_regiao `antes de `sigla_uf`

2022-03-08 20:30 UTC, crislanealves requested changes
Trocar  `is_partition: no` para `is_partition: false`

2022-03-08 20:44 UTC, crislanealves commented on bases/br_inep_saeb/proficiencia/table_config.yaml
>        has_sensitive_data:
faltou preencher aqui

2022-03-09 14:17 UTC, crislanealves commented
Algumas inconsistências entre a tabela e o dicionário.

- [ ] Em 1995 tem `localizacao` = `9` e `null`. Essas chaves não constam no dicionário. 

```sql
SELECT DISTINCT localizacao
FROM `basedosdados-dev.br_inep_saeb.proficiencia`
WHERE ano = 1995
```

- [ ] Verificar valores `null`, `em branco `e `6`, para vários anos. Essas chaves não constam no dicionário

```sql
SELECT DISTINCT raca_cor
FROM `basedosdados-dev.br_inep_saeb.proficiencia`
ORDER BY raca_cor
```

- [ ] Algumas chaves não constam no dicionário. Na verdade essa coluna está meio bugada. Transformei provisoriamente em ``int64`` pra visualizar melhor. No formato de `string` o `output ` ficou bem estranho, como se algumas variáveis tivessem espaço na frente.

1.
```sql
SELECT DISTINCT SAFE_CAST(serie AS INT64) serie
FROM `basedosdados-dev.br_inep_saeb.proficiencia`
ORDER BY serie
```

2.
```sql
SELECT DISTINCT serie
FROM `basedosdados-dev.br_inep_saeb.proficiencia`
```

- [ ] Tem algo muito estranho com essa coluna, parece que ela está com valores trocados/misturados.

```sql
SELECT DISTINCT sexo
FROM `basedosdados-dev.br_inep_saeb.proficiencia`
ORDER BY sexo
```

- [ ] Tem variáveis que tem dicionário mas não tem aqui. 

```sql
SELECT DISTINCT turno
FROM `basedosdados-dev.br_inep_saeb.proficiencia`
ORDER BY turno
```

2022-03-09 14:19 UTC, crislanealves commented
Vamos criar o hábito de conferir se as chaves do dicionário estão batendo com os valores da tabela, principalmente dessas tabelas grandes que não dá pra conferir tudo no olho.

2022-03-09 14:30 UTC, rdahis commented
Vou (finalmente) escrever uma query que retorna os valores únicos de todas as colunas. Isso vai basicamente servir de input para o dicionário.

2022-03-09 14:48 UTC, lucasnascm commented
Vou ter que mandar e-mail ou pedir via LAI essa info. No dicionário de 95 não tem localização = 9, por exemplo. Tampouco, raca_cor = 6 em 1997. O dicionário para no 5. Vou mudar a tipagem da serie no publish e verificar as outras infos. Vou verificar a diferença entre _null_ e valores em branco, mas a princípio é tudo missing, n tem dicionário

2022-03-21 17:52 UTC, crislanealves approved these changes

2022-03-21 18:53 UTC, merged