[dados] `br_mma_extincao`
basedosdados/mais pull request #1273
Opened 2022-07-25 11:19 UTC by lucasnascm

Substituição do PR #1271 pra evitar conflito
Inclui coluna nova nos dados e todos os arquivos estão preenchidos corretamente
Base de fauna e flora ameaçados de extinção em colaboração com Bruno Mioto

2022-07-25 20:27 UTC, IngridSRabelo commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      description: Classificação da subordem das espécieis
no futuro, não seria interessante criar um dicionário?

2022-07-25 20:28 UTC, IngridSRabelo commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      bigquery_type: int64
é int64 mesmo?

2022-07-25 20:29 UTC, IngridSRabelo reviewed
por ingrid

2022-07-25 23:08 UTC, brunomioto commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      description: Classificação da subordem das espécieis
Classificação da família da espécie?

2022-07-25 23:10 UTC, brunomioto commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      description: Classificação da subordem das espécieis
Ou "Classificação taxonômica a nível de Família"

2022-07-25 23:10 UTC, brunomioto commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      description: Classificação da ordem no reino animal
Classificação taxonômica a nível de Ordem

2022-07-25 23:10 UTC, brunomioto commented on bases/br_mma_extincao/flora_ameacada/table_config.yaml
> +      description: Reunião das espécies segundo características comuns
Classificação taxonômica a nível de Família

2022-07-25 23:12 UTC, brunomioto commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      description: Agrupamento por ordem dos animais (e.g. anfibios, aves, peixes)
Agrupamento por grandes grupos dos animais (e.g. anfíbios, aves, invertebrados terrestres)

2022-07-29 21:47 UTC, lucasnascm commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      description: Classificação da subordem das espécieis
Acho que é válido um diretório futuramente sim! `br_bd_diretorio_natureza` e a tabela chamaria `especie`

2022-07-29 21:48 UTC, lucasnascm commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +      bigquery_type: int64
É uma dummy, então é int64 sim

2022-08-01 17:46 UTC, gustavoalcantara commented
all right for me.

2022-08-01 19:01 UTC, crislanealves commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +
Adoro que a gente tem uma entidade pra isso hahahahaha

2022-08-01 19:01 UTC, crislanealves commented on bases/br_mma_extincao/fauna_ameacada/table_config.yaml
> +    github_user: lucasnascm
não tem `.br`

2022-08-01 19:05 UTC, crislanealves requested changes
- Onde você colocou a tabela de arquitetura? Adiciona na pasta de dados depois.
- Não tem o código de tratamento?
- Excluir a tabela `fauna_aumeacada` do BQ depois.

2022-08-01 19:28 UTC, lucasnascm commented
Falei com o @brunomioto e achamos por bem subir o código numa versão 1.1 (com a inclusão dos dados de 2014) após resposta de uma requisição LAI. A tabela de arquitetura pode ser criada nesse período tbm

2022-08-01 19:31 UTC, crislanealves approved these changes

2022-08-01 19:31 UTC, merged