[dados] br_inep_sinopse_estatistica_educacao_basica.municipio_matricula_localizacao_rede
basedosdados/mais pull request #1290
Opened 2022-08-17 15:14 UTC by IngridSRabelo

2022-08-22 09:54 UTC, lucasnascm commented on bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
> +name: br_inep_sinopse_estatistica_educacao_basica
Aqui é por hífen e não underline

2022-08-22 09:54 UTC, lucasnascm commented on bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
> +      description: Localização (e.g. Zona Urbana, Zona Rural)
Questão de toc, mas zona urbana e rural poderiam estar em minúsculo igual no campo de rede, considerando que o resultado na tabela tbm vem tudo no formato lower

2022-08-22 09:54 UTC, lucasnascm commented on bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
> +      temporal_coverage:
Etapa/Nível. Será que não valeria tbm alguns exemplos?

2022-08-22 16:46 UTC, IngridSRabelo commented on bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
> +      description: Localização (e.g. Zona Urbana, Zona Rural)
certo

2022-08-22 16:46 UTC, IngridSRabelo commented on bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
> +name: br_inep_sinopse_estatistica_educacao_basica
certo

2022-08-23 14:38 UTC, laura-l-amaral commented on bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
> +      description: Cobertura temporaç
temporal

2022-08-23 14:41 UTC, laura-l-amaral requested changes
só um detalhe pra ajustar e subimos o PR

2022-08-23 21:59 UTC, crislanealves commented on bases/br_inep_sinopse_estatistica_educacao_basica/code/br_inep_sinopse_educacao_basica.py
> +
@lucascr91 fica super orgulhoso

2022-08-23 22:02 UTC, crislanealves commented on bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
> +  - indicadores educacionais
coloca aqui no singular

2022-08-23 22:04 UTC, crislanealves commented on bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
> +
v1.0

2022-08-23 22:06 UTC, IngridSRabelo commented on bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
> +
ok

2022-08-23 22:07 UTC, crislanealves commented on bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
> +      is_partition: False
true e false minúsculo em todas

2022-08-23 22:07 UTC, IngridSRabelo commented on bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
> +  - indicadores educacionais
https://basedosdados.org/api/3/action/tag_list eu peguei dessa lista aqui, aí só tem no plural

2022-08-23 22:08 UTC, IngridSRabelo commented on bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
> +      is_partition: False
ok

2022-08-23 22:11 UTC, crislanealves commented on bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
> +
v1.0

2022-08-23 22:12 UTC, IngridSRabelo commented on bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
> +
ok

2022-09-01 18:24 UTC, crislanealves commented on bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
> +  - indicadores educacionais
uhum... já falamos disso em algum outro PR, não lembro qual. 

Mas via de regra vamos seguir aqui 

```
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - sempre no singular
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
```

2022-09-05 14:10 UTC, laura-l-amaral approved these changes

2022-09-05 14:10 UTC, merged