[dados] corrige `br_bd_diretorios_brasil.etnia_indigena`
basedosdados/mais pull request #1293
Opened 2022-08-18 19:50 UTC by filipemsc

2022-08-18 20:09 UTC, gustavoalcantara reviewed
correção_gustavo

2022-08-18 20:09 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +    - 2022
2019(1)2022 é a forma correta

2022-08-18 20:09 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
>      github_user:
insere teu github aqui

2022-08-18 20:11 UTC, gustavoalcantara commented
sempre que for em relação à [dados], insira eu @gustavoalcantara, @crislanealves @laura-l-amaral @IngridSRabelo e @lucasnascm para revisão, por favor.

2022-08-18 20:55 UTC, filipemsc commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +    - 2022
resolvido

2022-08-18 21:00 UTC, filipemsc commented
corrigido, @gustavoalcantara

2022-08-19 12:11 UTC, lucasnascm commented
@filipemsc não consegui ver os dados no BQ. Quando rodo `SELECT *FROM datasus-356120.br_bd_diretorios_brasil_staging.etnia_indigena` obtenho essa resposta "Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern". Imagino que seja alguma coisa relacionada a permissão do seu projeto.

2022-08-19 13:25 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/publish.sql
> +FROM datasus-356120.br_bd_diretorios_brasil_staging.etnia_indigena AS t
está faltando o arquivo do novo código, a gente sobe geralmente

2022-08-19 13:30 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +source_bucket_name: bd-projetos
é para ser `basedosdados-dev`

2022-08-19 13:30 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +project_id_prod: datasus-356120
é para ser `basedosdados-dev`

2022-08-19 13:30 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +project_id_staging: datasus-356120
é para ser `basedosdados-dev`

2022-08-19 13:34 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
Onde está o campo?
`# Url do código de limpeza dos dados.
data_cleaning_code_url:`
Ele deve vir após `data_cleaning_description`

2022-08-19 13:42 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
>        is_partition: false
preencher `temporal_coverage` para todos os campos; preencher `covered_by_dictionary:` para todos, para esse campo a resposta pode ser `yes` ou `no`; preencher `has_sensitive_data: no` para todos os campos

2022-08-19 13:45 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
preencher versão da tabela (no caso fica v1.1.0, dado que foi um fix desse porte)

2022-08-19 13:46 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
Além disso, preencher `last_updated`, o formato é assim, por exemplo: 
```
last_updated:
    metadata: '2022-08-17'
    data: '2022-08-17 11:21:37'
    release: '2022-08-17 11:21:37'
```

2022-08-19 13:50 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
>  # Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
Em `entity`, o modelo que utilizamos é:
```
observation_level:
    - entity: year
      columns:
        - ano
# Opções de `entity` em 'https://basedosdados.org/api/3/action/bd_available_options'
```

2022-08-19 13:54 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
Senti falta de alguns campos que tem no novo modelo do `table_config`, além disso alguns campos mudaram de nome nesse novo modelo, como `time_unit`, agora é `update_frequency`. Aqui nesse [PR](https://github.com/basedosdados/mais/pull/1290) tem o modelo da nova `table_config`

2022-08-19 13:54 UTC, IngridSRabelo reviewed
por Ingrid

2022-08-19 13:56 UTC, IngridSRabelo commented
novo modelo do `table_config`:
https://github.com/basedosdados/mais/blob/d53d0e6858d1b7e8fd440c116fe6a77e305efc4b/bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml

2022-08-19 22:31 UTC, crislanealves commented
@filipemsc, querido muito bom ter você de volta, estávamos com saudades <3. Esses metadados estão no formato antigo, bom atualizar o pacote e rodar o `table create` de novo.

2022-08-23 14:10 UTC, laura-l-amaral commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +source_bucket_name: bd-projetos
Se os dados ainda não estiverem no BQ e vc for subir com o nosso pacote, esse campo e os próximos dois tem que ser `basedosdados-dev`

2022-08-23 17:52 UTC, IngridSRabelo commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
>  version: ''
version: v.1.1

2022-08-23 17:53 UTC, IngridSRabelo reviewed
Por Ingrid

2022-09-04 12:44 UTC, filipemsc commented
@lucasnascm checa se vc pode acessar no bigquery agora:
datasus-356120.br_bd_diretorios_brasil_staging.etnia_indigena
depois disso acho que tá pronto

2022-09-04 12:48 UTC, lucasnascm commented
Ainda não @filipemsc. O BQ acusa esse erro aqui `Access Denied: BigQuery BigQuery: Permission denied while opening file.`

2022-09-05 12:57 UTC, filipemsc commented
agora foi! acho que tudo pronto

2022-09-06 01:21 UTC, laura-l-amaral requested changes
Últimos ajustes pra gente finalizar seu PR:

- [x] temporal coverage -> pode deixar vazio, como é pra ser uma base sem temporalidade melhor deixar vazia
- [x] preencher campo version
- [x] rodar metadata validate pra checar se tudo bem deixar o temporal coverage das colunas desse jeito (normalmente tem um tracinho e uma identação, mas não sei se ela é obrigatória ou não)

2022-09-06 14:22 UTC, filipemsc commented
> Últimos ajustes pra gente finalizar seu PR:
> 
> * [ ]  temporal coverage -> pode deixar vazio, como é pra ser uma base sem temporalidade melhor deixar vazia
> * [ ]  preencher campo version
> * [ ]  rodar metadata validate pra checar se tudo bem deixar o temporal coverage das colunas desse jeito (normalmente tem um tracinho e uma identação, mas não sei se ela é obrigatória ou não)

metadados validados: 
![image](https://user-images.githubusercontent.com/11773789/188660143-0ea01bfb-3581-4b9a-a8be-7672d09a3ceb.png)

2022-09-08 13:52 UTC, laura-l-amaral requested changes

2022-09-08 13:52 UTC, laura-l-amaral commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +      has_sensitive_data: yes
Querido, antes fechar o PR, esse dado deveria ser sensível mesmo? se não trocar para 'no'

2022-09-08 14:11 UTC, filipemsc commented on bases/br_bd_diretorios_brasil/etnia_indigena/table_config.yaml
> +      has_sensitive_data: yes
ajeitei, @laura-l-amaral! metadados validados novamente tb (só pra garantir)

2022-09-11 13:12 UTC, laura-l-amaral approved these changes

2022-09-11 13:13 UTC, merged