feat: Fgv igp
basedosdados/mais pull request #1322
Opened 2022-09-13 16:08 UTC by mfagundes

É necessário que estes dados estejam em produção para que a pipeline possa subir. Porém, não rodei o `basedosdados table publish`. Não sei se nesse caso específico seria o correto. 

Os dados estão em `dev`, apenas em `staging` e subiram nos testes da pipeline.

2022-09-14 22:49 UTC, laura-l-amaral requested changes
Tá bem preenchido só precisamos de alguns ajustes chave:

* Em todos os table_config:
- [x] arrumar o observation_level
- [ ] preencher last_update
- [ ] preencher version
- [ ] incluir repositório com código de limpeza
- [ ] arrumar o nome das colunas para que não tenha abreviações

* Num geral:
- [ ] falta o dataset_config  (tem que rodar um comando de metadata_create pro dataset, se precisar de ajuda pode me chamar)
- [ ] rodar o metadata_validate pra ver se dá algum errinho

2022-09-14 22:49 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +observation_level: [month]
ajustar  no seguinte padrão:

    - entity: year
      columns:
      - ano
    - entity: month
      columns:
      - mes

2022-09-14 22:49 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +last_updated:
preencher

2022-09-14 22:49 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +version:
v1.0

2022-09-14 22:49 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +data_cleaning_code_url:
incluir repositório que tem o código da pipeline

2022-09-14 22:49 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +    - name: var_mensal
alterar para variacao_mensal (não deixamos abreviações no nome das colunas)

2022-09-14 22:49 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +    - name: var_12_meses
variacao_12_meses

2022-09-14 22:49 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +    - name: acum_ano
variacao_acumulada_ano

2022-09-15 04:12 UTC, mfagundes commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +data_cleaning_code_url:
@laura-l-amaral Não houve uma limpeza desses dados, no sentido em que ele é usado na BD, uma vez que tratou-se do único dado criado diretamente em pipeline. O código é, de fato, uma uma `task` do Prefect, que faz a leitura do Ipeadata, realiza os cálculos necessários e gera um csv, que é, então, enviado para produção.

2022-09-15 04:38 UTC, mfagundes commented
@laura-l-amaral:

1. Estava usando o dataset_config.yaml que já existia. Porém realmente será necessário refazê-lo também, pois o layout pode ter mudado. Se você puder me acompanhar nesse processo eu te agradeço.
2. Não existiu uma limpeza nesses dados, pois eles entraram direto via pipeline (ver https://github.com/basedosdados/mais/pull/1322#discussion_r971355047)
3. O `metadata validate` sempre dá um erro quando valido a tabela que foi criada à mão (IGP-DI mensal). Pelo que avaliamos, este fato decorre de a base de `staging` do CKAN ser sincronizada com a de `prod` nos finais de semana e, com isso, o `package` ter deixado de existir, quebrando os metadados em `owner_org` (uma `property` da classe `Metadata`)

2022-09-15 12:10 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +data_cleaning_code_url:
Entendi! pode colocar o caminho da pasta de pipeline ou algo do tipo, a ideia é que os usuários tenham junto com os metadados como consultar qual processo a base passou antes de subir para o nosso datalake

2022-09-15 20:04 UTC, gustavoalcantara commented on bases/br_fgv_igp/igp_m_mes/table_config.yaml
> +    data: '2022-09-12'
às vezes a gente coloca a hora tb... ó 
metadata: '2022-08-22'
data: '2022-08-22 14:25:30'
release: '2022-08-22 14:25:30'

e eu preencheria todos os campos...

2022-09-15 20:04 UTC, gustavoalcantara commented on bases/br_fgv_igp/igp_og_ano/table_config.yaml
> +    data: '2022-09-12'
mesma coisa aqui

2022-09-15 20:05 UTC, gustavoalcantara commented
deixei alguns breves comentários, @mfagundes 
abraços! great work

2022-09-15 20:18 UTC, mfagundes commented on bases/br_fgv_igp/igp_m_mes/table_config.yaml
> +    data: '2022-09-12'
Quando roda no automático ele coloca a hora. Mas, por ora, estou mantendo a atualização do dia 12/09 apenas para conseguir colocar esses dados no BD+. Após a inserção, o Prefect deve atualizar isso automaticamente

2022-09-19 12:41 UTC, laura-l-amaral commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +observation_level:
Aqui a observação não é mes?

2022-09-19 13:03 UTC, laura-l-amaral requested changes
O principal aqui é incluir o bigquery type naquela variável que ficou vazia. Depois disso só resolver as dúvidas e fechamos!

2022-09-19 18:01 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +    metadata:
preencher esse campo

2022-09-19 18:01 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +    release:
preencher esse campo

2022-09-19 18:03 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_10_mes/table_config.yaml
> +    data: '2022-09-12'
Não está no formato correto. O formato deve ser `yyyy-mm-dd hh:mm:ss`

2022-09-19 18:08 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +    release:
preencher esse campo para todas as tabelas

2022-09-19 18:09 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +    data: '2022-09-12'
Não está no formato correto. O formato deve ser yyyy-mm-dd hh:mm:ss
Ver para todas as tabelas

2022-09-19 18:10 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +version: v1.0
é a versão 1.0 mesmo? Já estava no site não?

2022-09-19 18:10 UTC, mfagundes commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +observation_level:
Você tem razão. Apesar de o índice calculado pelo Ipea ser um valor médio de cada mês este índice não precisa ser atualizado todo mês. Alterei o `temporal_coverage` também.

2022-09-19 18:10 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +version: v1.0
verificar para todas as tabelas

2022-09-19 18:13 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +    - 1944-01(1)2022-08
é por ano não? então, por padrão, não se coloca o mês no temporal_coverage

2022-09-19 18:16 UTC, IngridSRabelo commented on bases/br_fgv_igp/igp_m_ano/table_config.yaml
> +  - 1989-06(1)2022-08
se a frequência é anual, desconsiderar o mês no temporal_coverage

2022-09-19 18:20 UTC, IngridSRabelo reviewed
Revisão

2022-09-19 18:33 UTC, mfagundes commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +version: v1.0
Na verdade, não estava. Estes dados foram iniciados, mas acabaram não sendo finalizados.

2022-09-19 18:34 UTC, mfagundes commented on bases/br_fgv_igp/igp_di_ano/table_config.yaml
> +    - 1944-01(1)2022-08
Perfeito, estava tudo como mensal. Ajustei as anuais, inclusive o `temporal_coverage`

2022-09-20 19:24 UTC, laura-l-amaral approved these changes

2022-09-20 19:28 UTC, merged