br_tesouro_estoque_divida_publica
basedosdados/mais pull request #1467
Opened 2022-11-30 14:57 UTC by andrealvguim

Adicionando base sobre estoque da dívida pública do site do CKAN

2022-11-30 16:09 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +dataset_id: br_tesouro_estoque_divida_publica
dataset_id e table_id não podem ter o mesmo nome

2022-11-30 16:09 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +description:
descreva a base. Sempre pense no usuário final.

2022-11-30 16:10 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +temporal_coverage: ['2017(1)2022']
- 2017(1)2022

2022-11-30 16:10 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +    github_user:
inserir teu github user

2022-11-30 16:11 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +data_cleaning_description:
qual foi o processo de etl?

2022-11-30 16:11 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +data_cleaning_code_url:
veja as outras como estão preenchidas.

2022-11-30 16:11 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +      is_in_staging:
aqui é tudo true. Pra todas as variáveis.

2022-11-30 16:13 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/code/br_tesouro_estoque_divida_publica.py
> +    df_particao.to_csv(particao, index=False, encoding='utf-8', na_rep='')
prioriza deixar o nome do arquivo .csv tal qual o nome do table_id

2022-11-30 18:00 UTC, arthurfg commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +      is_partition:
Preencher com `is_partition : false` para as colunas que não viraram particões.

2022-11-30 18:00 UTC, arthurfg commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +      temporal_coverage: (1)
Aqui, salvo engano, precisa estar na linha inferior. 
`temporal_coverage:`
 [TAB]       `- (1)`

2022-11-30 18:00 UTC, arthurfg commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/dataset_config.yaml
> +tags:
adicionar as tags e groups

2022-11-30 18:33 UTC, gustavoalcantara commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +      temporal_coverage: (1)
boa

2022-12-01 17:45 UTC, gabrielle-carv commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +observation_level:
preencher o nível de observação

2022-12-02 12:05 UTC, andrealvguim commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +observation_level:
Bom dia, qual que deve ser o modelo para o nível de observação? Não consegui encontrar um padrão nas outras bases. Pelo que eu entendi o meu deveria ser algo como:

2022-12-02 12:06 UTC, andrealvguim commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +observation_level:
entity: titulo 
     -id_divida
entity:year
     -ano

2022-12-02 17:12 UTC, andrealvguim commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +observation_level:
ok, obrigado

2022-12-06 14:39 UTC, gabrielle-carv commented on bases/br_tesouro_ckan/bases/br_tesouro_ckan/estoque_divida_publica/table_config.yaml
> +    metadata:
Adicionar a data

2022-12-06 15:04 UTC, gabrielle-carv commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +update_frequency:
hmm aqui não seria `month`?

2022-12-08 10:42 UTC, andrealvguim commented on bases/br_tesouro_estoque_divida_publica/bases/br_tesouro_estoque_divida_publica/br_tesouro_estoque_divida_publica/table_config.yaml
> +update_frequency:
acredito que sim, vi no site que na verdade a atualização é mensal mesmo

2022-12-08 12:40 UTC, rdahis requested changes
Marquei um detalhe importante mas de resto tá show.

2022-12-08 12:40 UTC, rdahis commented on bases/br_tesouro_ckan/bases/br_tesouro_ckan/dataset_config.yaml
> +organization: tesouro-nacional
Melhor mudar para `br-me` e recriar o conjunto como `br_me_estoque_divida_publica` (ao invés de `bases/br_tesouro_ckan`)

2022-12-08 12:40 UTC, rdahis commented on bases/br_tesouro_ckan/bases/br_tesouro_ckan/dataset_config.yaml
> +groups: economia, gov-fin-pub
Acho que aqui tem que ser como lista:

groups:
    - economia
    - gov-fin-pub

2022-12-15 13:12 UTC, gabrielle-carv approved these changes

2022-12-15 13:55 UTC, rdahis approved these changes

2022-12-15 14:22 UTC, merged