[dados] `br_cnj_estatisticas_poder_judiciario.recursos_financeiros`
basedosdados/mais pull request #1471
Opened 2022-12-01 23:43 UTC by arthurfg

Sobe `br_cnj_estatisticas_poder_judiciario.recursos_financeiros`.
@gabrielle-carv, a tabela já está em dev, se pude dar uma olhadinha :).
closes #1446

2022-12-02 11:07 UTC, gabrielle-carv commented on bases/br_cnj_estatisticas_poder_judiciario/recursos_financeiros/table_config.yaml
> +description:
adiciona uma descrição

2022-12-02 11:07 UTC, gabrielle-carv commented on bases/br_cnj_estatisticas_poder_judiciario/recursos_financeiros/table_config.yaml
> +    metadata:
add a data

2022-12-02 11:10 UTC, gabrielle-carv reviewed
:)

2022-12-05 13:27 UTC, laura-l-amaral commented on bases/br_cnj_estatisticas_poder_judiciario/recursos_financeiros/table_config.yaml
> +observation_level:
Tava checando aqui, aparentemente esse id não é único, tem dois ids com que são os mesmos para siglas tribunais diferentes (nao entendi tbm)

Colocar como observation level: ano e sigla_tribunal

2022-12-06 14:27 UTC, gabrielle-carv commented on bases/br_cnj_estatisticas_poder_judiciario/dataset_config.yaml
> +groups:
Adicionar grupos, como:
```
groups:
    - gov-fin-pub
  ```

2022-12-12 21:31 UTC, laura-l-amaral requested changes
Ajustar os comentários colocados por Gabi e por mim antes de fechar

2022-12-15 11:56 UTC, laura-l-amaral approved these changes

2022-12-15 11:56 UTC, merged