[dados] br_ipea_avs
basedosdados/mais pull request #1530
Opened 2023-01-16 18:57 UTC by tricktx

2023-01-17 11:31 UTC, gabrielle-carv commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      is_in_staging: yes
hmm, em geral a resposta de `is_in_staging` e `is_partition`, vem como `true` ou `false`

2023-01-17 11:37 UTC, gabrielle-carv commented on bases/br_ipea_avs/municipio/table_config.yaml
> +spatial_coverage: sa.br
por padrão deixar o `spatial_coverage` no formato do exemplo:
``` 
spatial_coverage:
    - sa.br
```

2023-01-17 11:40 UTC, gabrielle-carv commented on bases/br_ipea_avs/municipio/table_config.yaml
> +update_frequency: ten_years
a pesquisa acontece msm de dez em dez anos? se não ocorrer acho que deixaria como  `uncertain`

2023-01-17 11:42 UTC, gabrielle-carv commented on bases/br_ipea_avs/municipio/table_config.yaml
> +data_cleaning_code_url:
adicionar ao PR a pasta `code` e a url do código aqui

2023-01-17 11:51 UTC, gabrielle-carv commented on bases/br_ipea_avs/municipio/table_config.yaml
> +description: A plataforma oferece um panorama da vulnerabilidade e da exclusão social dos municípios e estados. Sua relevância vem justamente da capacidade de fornecer informações sobre a unidade pol
hmm, aqui vc repetiu a descrição do conjunto no da tabela, acho que nessa descrição você pode ser mais sucinto se quiser, e explicar sobre os dados que a tabela em si fornece

2023-01-17 11:54 UTC, gabrielle-carv commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    ckan_user:
talvez vc ainda não tenha `ckan_user`, mas caso tiver adicionar

2023-01-17 11:55 UTC, gabrielle-carv reviewed
:)

2023-01-17 12:58 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +data_cleaning_description:
aqui não sei se vale colocar o `-` 
Vai que dá problema. Tente colocar numa linha só. Finaliza com ponto `.`

2023-01-17 12:59 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      temporal_coverage:
temporal coverage seria 2000(10)2010

2023-01-17 12:59 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      temporal_coverage:
acredito eu

2023-01-17 13:01 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    - name: idhm_e
eu não vi a tabela de arquitetura... Mas, esses nomes aqui não são interessantes. seria idhm_educação. 
Não abreviamos nome na BD

2023-01-17 13:02 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    - name: idhm_r
mesma coisa aqui

2023-01-17 13:02 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Porcentagem dos ocupados sem rendimento - 18 anos ou mais
tira o `-`

2023-01-17 13:03 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    - name: proporcao_vulneravel
acho que esse nome seria proporcao_pessoas_vulneravel

2023-01-17 13:04 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: População vulnerável de 15 a 24 anos
Patrick, se atente nas descrições. Ali em cima vc coloca proporção e aqui vc não coloca. Tem que colocar se é proporção

2023-01-17 13:04 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Mortalidade até 5 anos de idade
atenção nas descrições

2023-01-17 13:05 UTC, gustavoalcantara reviewed
deixei alguns comentários. Atente-se às descrições e o preenchimento dos temporal_coverage. De resto tá ok. Parabéns. Qualquer dúvida nos envie mensagem.

2023-01-17 13:06 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Mortalidade até 5 anos de idade
se é proporção é proporção

2023-01-17 13:24 UTC, arthurfg commented on bases/br_ipea_avs/municipio/table_config.yaml
> +          - 2000, 2010
As colunas que tem o msm temporal_coverage da tabela ficam como `- (1)`. Ai o comentário vale para as outras colunas tb

2023-01-17 13:24 UTC, arthurfg commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      bigquery_type:
faltou preencher os metadados para essa coluna

2023-01-17 13:24 UTC, arthurfg commented on bases/br_ipea_avs/municipio/table_config.yaml
> +data_cleaning_code_url:
`https://github.com/basedosdados/mais/tree/master/bases/br_ipea_avs/code`

2023-01-17 14:44 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +       entity: state
o nível de observação não é o município?

2023-01-17 17:20 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    ckan_user:
Ainda não tenho.

2023-01-17 17:33 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    ckan_user:
tem sim querido, é o usuário no site da bd

2023-01-17 17:35 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      temporal_coverage:
hmm nesse caso do pr eu acho que o ideal seria na vdd colocar o (1) já que a cobertura temporal é igual da tabela

2023-01-17 18:07 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    - name: idhm_e
Nessas abreviações, conversei com o Lucas e ele tinha dito que era para deixar dessa forma porque dialoga com a base de idhm que tem na BD.

2023-01-17 19:15 UTC, gustavoalcantara commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: População vulnerável de 15 a 24 anos
ah e se é proporção, então é float64

2023-01-18 21:19 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Sigla da Unidade Federativa
Sigla da Unidade da Federação

2023-01-18 21:26 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Situação do domicílio
Localização do domicílio

2023-01-18 21:33 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    - name: proporcao_pessoa_vulneravel
Pode deixar `proporcao_vulneravel`

2023-01-18 21:34 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      observations:
Salário base ano de 2010

2023-01-18 21:35 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +          - 2010
(1)

2023-01-18 21:38 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Proporção de 5 a 6 anos na escola
Proporção de alunos

2023-01-18 21:39 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: proporção de crianças que vivem em domicílios em que nenhum dos
Começar com letra maiúscula

2023-01-18 21:40 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Proporção de 11 a 13 anos nos anos finais do fundamental ou com
Proporção de que ? Adicionar na descrição.

2023-01-18 21:41 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Proporção de 15 a 17 anos com fundamental completo
Proporção de que ? Adicionar na descrição.

2023-01-18 21:41 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Proporção de 18 anos ou mais com fundamental completo
Proporção de que ? Adicionar na descrição.

2023-01-18 21:41 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Proporção de 18 a 20 anos com médio completo
Proporção de que ? Adicionar na descrição.

2023-01-18 21:42 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: BRL_2010 / person
Por que BRL_2010?

2023-01-18 21:42 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +          - 2010
(1)

2023-01-18 21:43 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Proporção de empregados com carteira com 18 anos ou mais
carteira de trabalho?

2023-01-18 21:44 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Proporção de empregados sem carteira com 18 anos ou mais
carteira assinada

2023-01-18 21:47 UTC, crislanealves requested changes
Aprovar pós ajustes.

2023-01-19 11:27 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      - (1)
A gente coloca o `- (1)` quando o temporal coverage da coluna é igual da tabela, mas a a tabela sempre tem que ter descrito quais anos ela cobre.

2023-01-19 11:30 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Índice da dimensão Infraestrutura Urbana
padronizar a descrição com os demais  ivs_capital_humano, ivs_renda_trabalho

2023-01-19 14:51 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      description: Situação do domicílio
Verifiquei no site da BD situação parecida com essa coluna e achei o Sinopses Estatísticas da Educação Básica. 
A qual o nome da variável permanece "localizacao" e a descrição "Localização (e.g. zona urbana, zona rural)", eu acho que é a melhor forma.

2023-01-19 15:14 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: BRL_2010 / person
O salário base é referente ao ano de 2010.

2023-01-25 17:04 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: BRL_2010 / percent
essa unidade aqui me parece estranha. Acho que é só percent mesmo pq no final é um percentual de pessoas não uma quantidade de dinheiro.

2023-01-25 17:11 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: person
se é uma taxa não é número de pessoas, então fica sem unidade

2023-01-25 17:11 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: person
se representa um percentual tem que ser `percent`

2023-01-25 17:11 UTC, laura-l-amaral commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: BRL_2010 / person
não é um percentual esse aqui tbm?

2023-01-25 21:05 UTC, crislanealves commented on bases/br_ipea_avs/municipio/table_config.yaml
> +    - name: porporcao_vulnerabilidade_socioeconomica
proporcao

2023-01-26 04:12 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: BRL_2010 / percent
Coloquei dessa forma, uma vez que o valor tem como salário mínimo base de 2010 e é medido por percent. Irei reavaliar cada linha que tem esse formato. 
Muito obrigado. :)

2023-01-26 04:33 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: BRL_2010 / percent
Alterei as medidas que estavam com BRL_2010 / percent, coloquei: "Salário mínimo base referente ao ano de 2010" no campo da observations, dessa forma, fica bem detalhado para o usuário.

2023-01-26 04:38 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit: BRL_2010 / person
Não, Lauris. Segue a descrição: "População ocupada vulnerável à pobreza (com renda per capita igual ou inferior a meio salário mínimo de agosto de 2010) e que retornam diariamente do trabalho ao domicílio. São considerados apenas domicílios particulares permanentes. " 
Fiz da forma que descrevi a baixo, deixei só person e coloquei a seguinte observations: "Salário mínimo base referente ao ano de 2010".

2023-01-26 21:19 UTC, tricktx commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      measurement_unit:
year

2023-01-27 14:41 UTC, lucasnascm commented on bases/br_ipea_avs/dataset_config.yaml
> +notes: A plataforma oferece um panorama da vulnerabilidade e da exclusão social dos municípios e estados. Sua relevância vem justamente da capacidade de fornecer informações sobre a unidade político-
A plataforma oferece um panorama da vulnerabilidade e da exclusão social dos municípios e estados. Sua relevância vem justamente da capacidade de fornecer informações sobre a unidade político-administrativa mais próxima do cotidiano dos cidadão**s**, o município. Além disso, o AVS permite conhecer as desigualdades a nível intramunicipal das diversas espacialidades de uma mesma região metropolitana

2023-01-27 14:41 UTC, lucasnascm commented on bases/br_ipea_avs/municipio/table_config.yaml
> +description: A tabela oferece um panorama da vulnerabilidade e da exclusão social dos municípios e estados.
Aqui só do município. Pensando na reunião de ontem, acho que valeria descrever mais. "A tabela oferece um panorama da vulnerabilidade e da exclusão social dos municípios brasileiros nos anos dos últimos Censos (2000 e 2010). O índice de vulnerabilidade social é gerado a partir da análise de variáveis socioeconômicas, tais como, escolaridade, mortalidade, expectativa de vida, etc.

2023-01-27 14:41 UTC, lucasnascm commented on bases/br_ipea_avs/municipio/table_config.yaml
> +partitions:
Uai, n tá particionado por ano e sigla_uf?

2023-01-27 14:41 UTC, lucasnascm commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      is_partition: false
true

2023-01-27 14:41 UTC, lucasnascm commented on bases/br_ipea_avs/municipio/table_config.yaml
> +      is_partition: false
true

2023-01-27 15:11 UTC, lucasnascm approved these changes

2023-01-30 21:12 UTC, crislanealves approved these changes

2023-01-30 21:12 UTC, merged