[dados]br_ibge_estadic.indicadores
basedosdados/mais pull request #1535
Opened 2023-01-17 17:52 UTC by gabrielle-carv

2023-01-18 20:35 UTC, tricktx commented on bases/br_ibge_estadic/indicadores_perfil_gestor/table_config.yaml
> +data_cleaning_code_url:
adicionar ao PR a pasta `code` e a url do código aqui.

2023-01-18 20:39 UTC, gabrielle-carv commented on bases/br_ibge_estadic/indicadores_perfil_gestor/table_config.yaml
> +data_cleaning_code_url:
deixei comentado aqui em cima, não tem código de limpeza

2023-01-20 20:47 UTC, gustavoalcantara reviewed
pode subir

2023-01-25 12:52 UTC, laura-l-amaral requested changes

2023-01-25 12:52 UTC, laura-l-amaral commented on bases/br_ibge_estadic/indicadores_perfil_gestor/table_config.yaml
> +observation_level:
tem que incluir o tema aqui

2023-01-25 12:52 UTC, laura-l-amaral commented on bases/br_ibge_estadic/indicadores_quantidade_vinculo/table_config.yaml
> +observation_level:
incluir aqui as categorias que identificam cada linha unicamente (acho que os tipos)

2023-01-30 02:29 UTC, laura-l-amaral approved these changes

2023-01-30 02:34 UTC, merged