Dados de sócios da Receita Federal.
basedosdados/mais pull request #155
Opened 2020-10-24 17:42 UTC by rdahis

2020-10-24 18:50 UTC, fernandascovino commented on bases/br_me_socios/cnae_cnpj/table_config.yaml
> +partitions: # REQUIRED
não deveria conter as próximas 3 linhas aqui? https://github.com/basedosdados/mais/blob/2dfd24b9a9ee8fa9498afb9b89a12bbeb8d0b027/basedosdados/configs/templates/table/table_config.yaml#L70

2020-10-24 18:53 UTC, fernandascovino commented on bases/br_me_socios/cnae_secundaria/table_config.yaml
> +partitions: # REQUIRED
mesmo comentário anterior

2020-10-24 20:49 UTC, rdahis commented on bases/br_me_socios/cnae_cnpj/table_config.yaml
> +partitions: # REQUIRED
Não entendi. Quais 3 linhas?

2020-10-24 21:08 UTC, rdahis commented on bases/br_me_socios/cnae_cnpj/table_config.yaml
> +partitions: # REQUIRED
Ah não, não aparece não. Quando não tem partições fica vazio mesmo.

2020-10-27 17:29 UTC, fernandascovino commented
![image](https://user-images.githubusercontent.com/20743819/97338889-a8a14380-1860-11eb-8a57-c0f6d5fddcb7.png)

aqui em `basedosdados.br_me_socios.cnae_cnpj` é t mesmo? acho que faz mais sentido usar 1/0 e `in_primaria`

2020-10-27 17:38 UTC, fernandascovino requested changes

2020-10-27 17:38 UTC, fernandascovino commented on bases/br_me_socios/empresa/table_config.yaml
> +columns: # REQUIRED
adicionar a explicação das categorias em:

identificador_matriz_filial - o que é 1 e 2?
motivo_situacao_cadastral - o que são os numeros?
qualificacao_do_responsavel - o que são os numeros?
opcao_pelo_MEI - indicadora?
opcao_pelo_simples - indicadora?

consertar:

situacao_cadastral - é string mesmo, não é int?

2020-10-27 17:38 UTC, fernandascovino commented on bases/br_me_socios/holding/table_config.yaml
> +columns: # REQUIRED
adicionar a explicação das categorias em:

identificador_matriz_filial - o que é 1 e 2?
motivo_situacao_cadastral - o que são os numeros?
qualificacao_do_responsavel - o que são os numeros?
opcao_pelo_MEI - indicadora?
opcao_pelo_simples - indicadora?

consertar:

situacao_cadastral - é string mesmo, não é int?

2020-10-29 23:15 UTC, fernandascovino commented on bases/br_me_socios/empresa/publish.sql
> +SAFE_CAST(situacao_cadastral AS STRING) situacao_cadastral,
opa, é aqui sobre o tipo de `situacao_cadastral`

2020-11-16 18:13 UTC, merged