Abre PR do conjunto br_bcb_estban
basedosdados/mais pull request #1561
Opened 2023-02-02 21:15 UTC by folhesgabriel

Abre PR do conjunto br_bcb_estban

closes #650

2023-02-07 10:21 UTC, gabrielle-carv commented on bases/br_bcb_estban/agencia/table_config.yaml
> +    - 1988(1)2022
como é mensal inclui aqui tbm o mês que a base cobre

2023-02-07 10:22 UTC, gabrielle-carv commented on bases/br_bcb_estban/agencia/table_config.yaml
> +    data: '2023-02-02'
em `data` tbm entra hora

2023-02-07 10:26 UTC, gabrielle-carv commented on bases/br_bcb_estban/dataset_config.yaml
> +groups: economia
as respostas em `groups` entram no mesmo formato que as de `tags`, ficando:
```
groups:
    - economia```

2023-02-07 10:28 UTC, gabrielle-carv commented on bases/br_bcb_estban/municipio/table_config.yaml
> +    - 1988(1)2022
add aqui tbm o mês de cobertura

2023-02-07 10:30 UTC, gabrielle-carv commented on bases/br_bcb_estban/municipio/table_config.yaml
> +    data: '2023-02-02'
add a hora em `data`

2023-02-07 14:08 UTC, laura-l-amaral commented on bases/br_bcb_estban/dicionario/table_config.yaml
> +spatial_coverage:
querido segundo nosso manual não preenchemos alguns campos de metadados de dicionarios
<img width="509" alt="image" src="https://user-images.githubusercontent.com/100051996/217267595-4dc5c944-5873-4a72-bccd-bbafe519aff7.png">

2023-02-07 14:15 UTC, laura-l-amaral commented on bases/br_bcb_estban/agencia/table_config.yaml
> +       entity: municipality
acho que nesse caso município não entra no nível de observação pq uma agencia não tem como estar em 2 municipios diferentes né? `id_municipio `acaba sendo uma característica da agencia não uma variável que diferencia cada linha

2023-02-07 17:14 UTC, folhesgabriel commented on bases/br_bcb_estban/agencia/table_config.yaml
> +       entity: municipality
Ops, copiei do dataset de `municipios` e esqueci de apagar

2023-02-09 00:06 UTC, laura-l-amaral approved these changes

2023-02-09 00:13 UTC, laura-l-amaral requested changes
fui ver no BQ e o campo valor tem alguns valores bem baixos, ta certo isso? Será que a unidade tá em reais mesmo?

![image](https://user-images.githubusercontent.com/100051996/217681124-a13e9c23-5dd1-44f1-8ce1-964439a7ec6f.png)

2023-02-10 18:40 UTC, lucasnascm commented on bases/br_bcb_estban/agencia/table_config.yaml
> +          table_id: ano
A tabela chama mes, as únicas colunas na tabela de ano são ano e bissexto

2023-02-10 18:40 UTC, lucasnascm commented on bases/br_bcb_estban/agencia/table_config.yaml
> +      observations: Das 422.034.993 milhões de linhas com id_municipio, existem 3.682.911 (0,87%) que possuiam a coluna de id_municipio, do IBGE de 7 dígitos ou o id_municipio do Banco Central preenc
O que identifica cada observação é o cnpj da agencia e não o id_municipio em si, certo?! Eu colocaria algo do tipo "Do total de observações, em 0,87% (em relação ao tratamento feito até o dia 02-02-2023) não constavam a informação com o código do município de 7 dígitos nos dados originais"

2023-02-10 18:44 UTC, folhesgabriel commented on bases/br_bcb_estban/agencia/table_config.yaml
> +      observations: Das 422.034.993 milhões de linhas com id_municipio, existem 3.682.911 (0,87%) que possuiam a coluna de id_municipio, do IBGE de 7 dígitos ou o id_municipio do Banco Central preenc
Realmente, lendo agora ficou super confuso.

2023-02-10 18:45 UTC, folhesgabriel commented
> fui ver no BQ e o campo valor tem alguns valores bem baixos, ta certo isso? Será que a unidade tá em reais mesmo?
> 
> ![image](https://user-images.githubusercontent.com/100051996/217681124-a13e9c23-5dd1-44f1-8ce1-964439a7ec6f.png)

2023-02-11 01:57 UTC, laura-l-amaral commented on bases/br_bcb_estban/agencia/table_config.yaml
> +      observations:
incluir nas observações desse campo que foi feita a correção de unidade monetária e qual padrão seguimos

2023-02-11 01:59 UTC, laura-l-amaral commented on bases/br_bcb_estban/agencia/table_config.yaml
> +     - country: br
pode tirar esse aqui, só colocamos o country quando precisamos indicar uma unidade espacial. Quando colocamos o country antes de municipio é pra indicar que são as municipalidade limitadas aquele país

2023-02-13 12:33 UTC, laura-l-amaral approved these changes

2023-02-13 12:34 UTC, merged