[dados] br_ans_beneficiario.informacao_consolidada
basedosdados/mais pull request #1582
Opened 2023-03-02 03:15 UTC by guissalustiano

resolves #1078

2023-03-02 22:24 UTC, tricktx commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +    release:
Adicionar o release, pode repetir a data de cima.

2023-03-02 22:27 UTC, tricktx commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +data_cleaning_description:
Eu não sei se o ckan aceita a descrição dessa forma, @guissalustiano. Aconselho a separar por ; dessa forma:
data_cleaning_description: A coluna NM_MUNICIPIO, DT_CARGA e ID_CMPT_MOVEL foi apagada; as demais colunas foram renomeadas em lowercase e snake_case; A coluna TP_VIGENCIA_PLANO foi expandida

2023-03-02 22:30 UTC, tricktx commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +number_rows:
Colocar a quantidade de linhas que a tabela contém.

2023-03-02 22:35 UTC, tricktx commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +      observations: "'Individual ou familiar', 'Coletivo empresarial', 'Coletivo por adesão', 'Individual ou Familiar + Coletivo Empresarial', 'Individual ou Familiar + Coletivo por Adesão', 'Coletiv
Precisaremos fazer um dicionário para essas e demais colunas com mais de uma variável, @guissalustiano. Eu tinha começado a fazer o dicionário, eu irei procurar para você, tudo bem? Até amanhã eu lhe retorno com essa resposta.

2023-03-02 23:45 UTC, tricktx commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +observation_level: other
O nível de observação dessa base é município.

2023-03-02 23:47 UTC, tricktx commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +      observations: "'Individual ou familiar', 'Coletivo empresarial', 'Coletivo por adesão', 'Individual ou Familiar + Coletivo Empresarial', 'Individual ou Familiar + Coletivo por Adesão', 'Coletiv
Da uma olhada nesse dicionário, amigo. 

https://docs.google.com/spreadsheets/d/1MhCtA-qX1dwb2DOk048jRfhxE-TeceY49I4CDXS4-kk/edit#gid=0

2023-03-02 23:51 UTC, tricktx commented on bases/br_ans_beneficiario/dataset_config.yaml
> +tags:
Colocas as tags

2023-03-03 12:24 UTC, guissalustiano commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +      observations: "'Individual ou familiar', 'Coletivo empresarial', 'Coletivo por adesão', 'Individual ou Familiar + Coletivo Empresarial', 'Individual ou Familiar + Coletivo por Adesão', 'Coletiv
Mas qual a vantagem de ter um dicionario nessas colunas? Já que o dado sempre vai ser lido junto acredito que já faz sentido guardar desnormalizado

2023-03-03 12:24 UTC, guissalustiano commented on bases/br_ans_beneficiario/dataset_config.yaml
> +tags:
Ideias de quais tags coloca?

2023-03-06 01:55 UTC, tricktx commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +      observations: "'Individual ou familiar', 'Coletivo empresarial', 'Coletivo por adesão', 'Individual ou Familiar + Coletivo Empresarial', 'Individual ou Familiar + Coletivo por Adesão', 'Coletiv
Fala, Guilherme. Tudo bem?

Aqui na BD a gente sempre preza pela compatibilização e padronização. A própria ANS fornece um dicionário (https://dadosabertos.ans.gov.br/FTP/PDA/informacoes_consolidadas_de_beneficiarios/dicionario/) para algumas variáveis. Além disso, prezando também por uma otimização de armazenamento, é melhor fornecer um dicionário e um dataset mais enxuto (com menos observações textuais), sem typos, padronizado e compatibilizado entre anos. Eu posso te ajudar, se quiser. Fique a vontade também para aparecer na nossa reunião de dados toda quarta às 17hrs lá no nosso canal do discord.

2023-03-06 01:57 UTC, tricktx commented
Em relação a sua tabela no BQ, eu estou recebendo a seguinte mensagem quando tento acessa-la: "Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. patrick.teixeira@basedosdados.org does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist). Please make sure gs://basedosdados_stag_guissalustiano/staging/br_ans_beneficiario/informacao_consolidada/* is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator." Poderia liberar para que eu possa ter acesso, Guilherme?

Agradeço desde já.

2023-03-06 12:12 UTC, guissalustiano commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +      observations: "'Individual ou familiar', 'Coletivo empresarial', 'Coletivo por adesão', 'Individual ou Familiar + Coletivo Empresarial', 'Individual ou Familiar + Coletivo por Adesão', 'Coletiv
Opa! Obrigado pela resposta!
Mesmo fornecendo o dicionario os dados originais não são "label encoding", eles estão sem typos, padronizados e compatibilizados entre os anos mas nas suas próprias colunas. 
Eu estou subindo os dados em parquet, logo não terá nenhuma otimização de armazenamento, pelo contrario, apenas gastaria mais processamento para fazer o join no bigquery.
Se mesmo assim preferirem por criar o dicionario eu consigo gerar aqui!

2023-03-06 12:23 UTC, guissalustiano commented
@tricktx te dei acesso como database owner e bucket owner, não consegui configurar corretamente para acesso externo
Fique a vontade pra mexer nas permissões

2023-03-22 04:54 UTC, guissalustiano commented
Alguma atualização @tricktx? Queria apagar esses CSVs da minha máquina

2023-04-19 11:51 UTC, laura-l-amaral requested changes
Oi Gui! Tá execelente o trabalho

Precisamos ainda ajustar o table_config e o publish.sql pra acompanhar os arquivos que vc subiu o Google Cloud

Abraços

2023-04-19 11:51 UTC, laura-l-amaral commented on bases/br_ans_beneficiario/informacao_consolidada/publish.sql
> +SAFE_CAST(qtd_beneficiario_ativo AS INT64) qtd_beneficiario_ativo,
arrumar aqui no publish as variáveis tbm

2023-04-19 11:51 UTC, laura-l-amaral commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +    - name: qtd_beneficiario_ativo
e aqui no table_config

2023-04-19 17:16 UTC, guissalustiano commented on bases/br_ans_beneficiario/informacao_consolidada/publish.sql
> +SAFE_CAST(qtd_beneficiario_ativo AS INT64) qtd_beneficiario_ativo,
Opa, corrigido!

2023-04-19 17:16 UTC, guissalustiano commented on bases/br_ans_beneficiario/informacao_consolidada/table_config.yaml
> +    - name: qtd_beneficiario_ativo
Corrigido!

2023-07-22 13:22 UTC, guissalustiano commented
Essa base ficou fechada para o BDplus

2023-07-22 13:22 UTC, closed without merging