[dados-atualizacao] br_ms_cnes.estabelecimentos
basedosdados/mais pull request #1588
Opened 2023-03-07 16:23 UTC by folhesgabriel

Atualiza tabela `estabelecimentos` do conjunto `br_ms_cnes`

2023-03-07 17:11 UTC, laura-l-amaral commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
> +data_cleaning_code_url: ttps://github.com/basedosdados/mais/tree/master/bases/br_ms_cnes/code
colocar o code no pr tbm

2023-03-07 17:52 UTC, gabrielle-carv commented on bases/br_ms_cnes/dicionario/table_config.yaml
> +data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_ms_cnes/code
pode apagar a `url` aqui

2023-03-07 17:53 UTC, gabrielle-carv commented on bases/br_ms_cnes/dicionario/table_config.yaml
> +version: ''
add a `version`

2023-03-07 18:05 UTC, gabrielle-carv commented on bases/br_ms_cnes/dicionario/table_config.yaml
> +metadata_modified: '2022-12-23T10:24:34.821307'
precisa att o `metadata_modified`, fui olhar na api, parece que existem dois dicionários agr já não sei mais se ficaria 
```
metadata_modified:  "2023-03-03T01:06:40.988153" 
````
ou
``` 
metadata_modified: "2023-03-03T01:07:01.144762"

2023-03-07 19:03 UTC, gabrielle-carv commented on bases/br_ms_cnes/dicionario/table_config.yaml
> +metadata_modified: '2022-12-23T10:24:34.821307'
okay, agr já foi excluído um dos dicionários hahaha pode att para:
```
metadata_modified: "2023-03-07T19:00:00.561772"

2023-03-08 20:24 UTC, gustavoalcantara commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
>      email: gustavo.tiago@basedosdados.org
acho válido tirar esse e-mail aqui. O Gustavo não tá mais na BD. Insere só o usuário do github https://github.com/gustavoairestiago

2023-03-08 20:25 UTC, gustavoalcantara reviewed
dá uma olhada no que inseri aqui, Pisa

2023-03-10 21:42 UTC, laura-l-amaral commented on bases/br_ms_cnes/dicionario/table_config.yaml
> +data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_ms_cnes/code
pq?

2023-03-10 21:47 UTC, laura-l-amaral commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
> +description: Tabela que define as informações sobre administração do estabelecimento
eu vi que essa difinição já tava de antes, mas acho que tá meio esquisita a formação de frase? Joguei no chatgpt e ele deu uma que achei melhor "A tabela fornece informações sobre a gestão e operação dos estabelecimentos de saúde brasileiros"

2023-03-10 21:51 UTC, laura-l-amaral requested changes
Só fazer esses pequenos ajustes e fazer o publish dos metadados em staging pra gente fechar o pr uhuuuul \o/

2023-03-13 12:23 UTC, folhesgabriel commented on bases/br_ms_cnes/dicionario/table_config.yaml
> +data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_ms_cnes/code
Tbm não entendi

2023-03-13 12:27 UTC, folhesgabriel commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
> +description: Tabela que define as informações sobre administração do estabelecimento
Opa, concordo!

2023-03-16 14:26 UTC, gabrielle-carv commented on bases/br_ms_cnes/dicionario/table_config.yaml
> +data_cleaning_code_url: https://github.com/basedosdados/mais/tree/master/bases/br_ms_cnes/code
pq é o dicionário, achei que não entrava a url do código de limpeza nele, vale a pena colocar ?

2023-03-20 13:52 UTC, rdahis commented
Esses dados do CNES já estão em pipelines/runners?

2023-03-21 11:54 UTC, laura-l-amaral commented
ainda não @rdahis

2023-03-22 17:50 UTC, arthurfg submitted a review, later dismissed
acho que é só isso pisa, tirou onda

2023-03-22 17:50 UTC, arthurfg commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
> +    - name: banco
no bq essa coluna tá como `string` mas está com o `.0` no final

2023-03-22 17:50 UTC, arthurfg commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
> +      bigquery_type: string
aqui é só uma dúvida, é de boa deixar o `cpf_cnpj` como `0` mesmo né? Qualquer coisa muda no `publish.sql` pra deixar vazio os que forem 0, pra n precisar subir tudo dnv.

2023-03-22 17:50 UTC, arthurfg commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
> +      bigquery_type: string
ai vale para os outros campos com cnpj tb

2023-03-22 17:50 UTC, arthurfg commented on bases/br_ms_cnes/estabelecimento/table_config.yaml
> +      is_partition: false
aqui ficou um espaço

2023-04-12 21:49 UTC, laura-l-amaral approved these changes

2023-04-12 21:56 UTC, merged