[dados] br_bd_diretorios_brasil.cep
basedosdados/mais pull request #1613
Opened 2023-04-11 21:10 UTC by gabrielle-carv

2023-04-11 21:35 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +      covered_by_dictionary: no
amiga, nao vai entrar o diretórios aqui?

2023-04-11 21:37 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +      description: Ponto geográfico (latitude e longitude) do CEP
Centróide acho melhor

2023-04-11 21:37 UTC, gustavoalcantara reviewed
breves comentários aqui

2023-04-11 21:49 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +      description: Ponto geográfico (latitude e longitude) do CEP
amiga, e a coluna eu chamaria de geometria... porque é um ponto e todas as nossas tabelas seguem esse padrão quando é wkt

2023-04-11 21:59 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +      description: Ponto geográfico (latitude e longitude) do CEP
amiga, além disso, você plotou esses pontos? algum deles cai no oceano ou em outro país? Se sim, acho que vale uma observação

2023-04-12 12:09 UTC, gabrielle-carv commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +      covered_by_dictionary: no
migo, tentei usar os outros diretórios como base e eles não tinham, ai optei por não colocar

2023-04-12 12:27 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +      covered_by_dictionary: no
boa

2023-04-12 12:45 UTC, laura-l-amaral commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +title: CEP (Código de Endereçamento Postal)
acho que deixa o contrário aqui Nome Completo (Sigla)

2023-04-12 12:50 UTC, laura-l-amaral requested changes

2023-04-12 13:00 UTC, gustavoalcantara commented on bases/br_bd_diretorios_brasil/cep/table_config.yaml
> +    - name: geometria
mas é pq os demais dados tudo que tem lat/long a gente tá chamando de geometria...

2023-04-14 18:19 UTC, laura-l-amaral approved these changes

2023-04-14 18:21 UTC, merged