[dados] br_inep_indicador_nivel_socioeconomico
basedosdados/mais pull request #1622
Opened 2023-04-14 12:43 UTC by vilelaluiza

2023-04-14 13:13 UTC, gustavoalcantara reviewed
só uma observação: 
- Existe algumas linhas na coluna INSE que possuem vários números depois da vírgula. Veja: 
![image](https://user-images.githubusercontent.com/26544494/232053052-97907a64-ab01-4fc0-bd13-08e3b3a1146f.png)
essa linha em especifico tá apresentando o número `4.5600000000000005`. 
Talvez seja legal refletir à respeito disso e normalizar para duas/três casas decimais. 
De resto, acredito que esteja ok. Parabéns pelo primeiro PR.

2023-04-14 20:36 UTC, laura-l-amaral requested changes
Está excelente! Parabéns! Foi muito bem assessorada. 

Eu só percebi uma coisa que é necessário mudar, o campo de 'has_sensitive_data' em alguns arquivos não ta alinhado com os demais campos, isso faz com que o código não consiga ler o yaml pra construir os arquivos de metadado no Ckan.

Além disso, quando a cobertura temporal da coluna é igual a cobertura temporal da tabela o mais correto é preencher com (1) ao invés de colocar igual ao temporal_coverage da tabela. Mas isso é o ideal,  pq facilita algumas coisas depois, não é exatamente necessário.

2023-04-17 14:36 UTC, laura-l-amaral commented on bases/br_inep_indicador_nivel_socioeconomico/escola/table_config.yaml
> +metadata_modified: '2022-10-23T22:51:01.369542'
como ele não ta no ckan é como se a tabela não existisse, aí tem que deixar em branco

2023-04-18 18:11 UTC, laura-l-amaral approved these changes

2023-04-18 18:12 UTC, merged