[dados-atualizacao] br_rj_isp_estatisticas_seguranca
basedosdados/mais pull request #1627
Opened 2023-04-17 21:03 UTC by folhesgabriel

- PR **draft** do br_rj_isp_estatisticas_seguranca
- tabelas:
  - `evolucao_mensal_cisp `
  - `taxa_evolucao_mensal_uf`
  - `taxa_evolucao_anual_uf`
  - `evolucao_mensal_municipio`
  - `taxa_evolucao_mensal_municipio`
  - `taxa_evolucao_anual_municipio`
  - `evolucao_mensal_upp`
  - `armas_apreendidas_mensal`
  - `armas_fogo_apreendidas_mensal`
  - `evolucao_policial_morto_servico_mensal`
  - `feminicidio_mensal_uf`
  - `taxa_letalidade`

2023-04-19 23:01 UTC, laura-l-amaral requested changes
Um PR de respeito! Algunas coisinhas que percebi:

- Arrumar alguns publish.sql que não estão com os datatypes corretos. 
- Revisar o observation level. O que define cada linha unicamente?
- Para além disso só vi alguns campos de year que estavam com measurement_unit: day, que acho que vale checar nas demais tabelas

2023-04-20 13:13 UTC, tricktx commented on bases/br_rj_isp_estatisticas_seguranca/evolucao_mensal_upp/table_config.yaml
> +observation_level:
Minha querida, coloquei:
    - entity: neighborhood
      columns:
          - id_upp 
          
Cada id_upp representa um Bairro na cidade do Rio de Janeiro, acho que é justo.

2023-04-20 13:24 UTC, tricktx commented on bases/br_rj_isp_estatisticas_seguranca/evolucao_mensal_cisp/table_config.yaml
> +observation_level:
Nesse caso, eu coloquei: 
    - entity: other
      columns:
          - id_cisp
          - id_aisp
          - id_risp

2023-04-20 13:30 UTC, tricktx commented on bases/br_rj_isp_estatisticas_seguranca/armas_fogo_apreendidas_mensal/table_config.yaml
> +      entity: municipality
Eu acho que nesse caso, eu posso incluir os ids. Acabei de achar as definições mais completa de cada um dos ids: 

As Circunscrições Integradas de Segurança Pública - CISP, correspondem às áreas territoriais de atuação e responsabilidade conjunta das delegacias distritais da Secretaria de Estado de Polícia Civil (SEPOL) e das companhias integradas da Secretaria de Estado de Polícia Militar (SEPM). As CISP têm como princípio básico o conceito de que a responsabilidade pelo policiamento de uma subárea da companhia de Polícia Militar deverá coincidir com a circunscrição de uma delegacia de Polícia Civil. Nesse sentido, as CISP constituem a esfera de integração territorial, em nível operacional, das Companhias Integradas da SEPM com as Delegacias de Polícia da SEPOL. As CISP caracterizam, segundo este modelo de integração geográfica, a menor instância de apuração dos indicadores de criminalidade.

As Áreas Integradas de Segurança Pública - correspondem, geograficamente, às áreas de atuação de um batalhão da SEPM e às circunscrições das delegacias da SEPOL contidas na área de cada batalhão. As AISP foram criadas através da Resolução SSP N. 263 de 27 de julho de 1999, como parte de uma política de segurança pública que tinha por objetivo estreitar a ligação entre as Polícias Civil e Militar, bem como destas com as comunidades abrangidas pelas AISP, por meio da gestão participativa na identificação e resolução dos problemas locais de segurança pública. A atual divisão territorial do estado do Rio de Janeiro contempla um total de 39 AISP, conforme a Resolução SESEG nº 478 de 31/05/2011, que visou adequar os limites geográficos de atuação das unidades da Polícia Civil e Militar, de forma a torná-las compatíveis aos objetivos da gestão territorial da segurança pública, segundo RISP, AISP e CISP.

As Regiões Integradas de Segurança Pública (RISP) objetivam a articulação territorial regional, no nível tático, da SEPOL com a SEPM. A adequação geográfica entre as circunscrições territoriais de atuação das Polícias, no contexto das RISP, se consolida em termos práticos ao nível dos Departamentos de Polícia de Área (DPA) da SEPOL e dos Comandos de Policiamento de Área (CPA) da SEPM. Os diretores dos DPA e os comandantes dos CPA, além das atribuições internas inerentes às suas respectivas instituições, também são responsáveis pelo estabelecimento de estratégias de integração e cooperação regionais; pela instituição de um fórum permanente de análise, compartilhamento de informações e ações conjuntas; pela adequação dos recursos humanos e logísticos às necessidades regionais; pelo acompanhamento e avaliação das ações realizadas; assim como pela promoção de uma rotina de reuniões e monitoramento do cumprimento das metas operacionais e administrativas pertinentes à sua região. O estado do Rio de Janeiro está dividido em sete RISP, conforme as seguintes abrangências territoriais:

• 1ª RISP Capital (Zona Sul, Centro e parte da Norte)
• 2ª RISP Capital (Zona Oeste e parte da Norte)
• 3ª RISP Baixada Fluminense
• 4ª RISP Grande Niterói e Região dos Lagos.
• 5ª RISP Sul Fluminense
• 6ª RISP Norte Fluminense e Noroeste
• 7ª RISP Região Serrana

2023-04-24 21:11 UTC, laura-l-amaral approved these changes

2023-04-24 21:11 UTC, merged