[dados] br_inep_sinopse_estatistica_educacao_basica
basedosdados/mais pull request #1639
Opened 2023-04-26 15:17 UTC by lucasnascm

Reestrutura conjunto já existente e inclui novos dados

2023-04-26 16:08 UTC, laura-l-amaral requested changes
Ajustar os `is_in_staging` e `is_partition`

2023-04-26 17:42 UTC, gabrielle-carv commented on bases/br_inep_sinopse_estatistica_educacao_basica/tempo_ensino/publish.sql
> +SAFE_CAST(quantidade_matricula AS STRING) quantidade_matricula
`quantidade_matricula` acabou subindo como `string`

2023-04-26 17:42 UTC, gabrielle-carv commented on bases/br_inep_sinopse_estatistica_educacao_basica/tempo_ensino/publish.sql
> +SAFE_CAST(quantidade_matricula AS STRING) quantidade_matricula
e `ano` tbm

2023-04-26 17:44 UTC, gabrielle-carv commented on bases/br_inep_sinopse_estatistica_educacao_basica/faixa_etaria/table_config.yaml
> +metadata_modified: '2022-12-20T18:47:38.481695'
apagar o `metadata_modified` em todas as tabelas novas

2023-04-26 18:20 UTC, laura-l-amaral commented on bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
> +title: Sinopses Estatísticas da Educação Básica
como não vai mexer no datasetconfig pode deletar esse arquivo aqui

2023-04-26 18:33 UTC, laura-l-amaral requested changes
Tá ótimo!

Agora acho que é só ver um problema de encoding que deu e acho que seria bacana padronizar a parte do tratamento

2023-04-26 18:33 UTC, laura-l-amaral commented on bases/br_inep_sinopse_estatistica_educacao_basica/etapa_ensino_serie/table_config.yaml
> +data_cleaning_description: Junção das diferentes planilhas originais, reshape pro formato long, partição por UF
Estamos tentando padronizar essa parte de descrição, aí seria bom numerar as etapas. Acho bacana pra facilitar pro usuário e pra gente mesmo ter mais clareza do que aconteceu. Vou colocar aqui o exemplo da estban que to usando como referencia pra todos:

data_cleaning_description: 1. Retirar acentos da coluna de instituicoes; 2. Criar coluna id_municipio; 3. Dropar colunas 'MUNICIPIO', 'CODMUN_IBGE', 'CODMUN' originais da base descenessarias ou substituidas; 4. Tranformar a base do formato wide para o formato long para transformar 55 colunas de verbetes em uma única; 5. Corrigir unidades monetárias; 6. Criar regex para extrair identificador dos verbetes; 7. Criar colunas de ano e mês

2023-04-27 14:57 UTC, gustavoalcantara commented on bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
>  # As máximas unidades espaciais que a tabela cobre.
a @laura-l-amaral mencionou, mas aparentemente deu problema de encode real. Pelo menos pra mim tá

2023-04-28 19:54 UTC, laura-l-amaral approved these changes

2023-04-28 19:54 UTC, merged

2023-05-10 19:09 UTC, laura-l-amaral commented
closes #1514, #1515, #1516, #1512