Inclui tabela de cadastro de militares do Portal da Transparência
basedosdados/mais pull request #182
Opened 2020-11-27 20:04 UTC by hsxavier

Incluindo tabela de cadastro dos servidores federais militares (na verdade um view para o gabinete-compartilhado).

2020-12-22 05:51 UTC, rdahis commented
@hsxavier acho que você precisa dar permissão para eu poder mexer no pull request dado que vem de um fork na tua conta. Quero tentar publicar no BQ e ver se precisa de ajustes.

2020-12-27 15:29 UTC, fernandascovino commented on bases/br_cgu_servidores_executivo_federal/servidores_militares_cadastro/table_config.yaml
> +    - id_servidor
o que torna cada linha única aqui, também não seria por `id_atividade`?
```suggestion
    - id_servidor
    - id_atividade
```

2020-12-27 15:31 UTC, fernandascovino commented on bases/br_cgu_servidores_executivo_federal/servidores_militares_cadastro/table_config.yaml
> +    code_url: https://github.com/basedosdados/mais/tree/master/bases/br_cgu_servidores_executivo_federal/code # REQUIRED
Adicionar a pasta `code` - ela não existe em `br_cgu_servidores_executivo_federeal`!

Precisa ter:
- pasta `code` sempre com no mínimo um arquivo `readme`
- caso não tenha código de tratamento, deixar explícito isso no `readme`
- caso tenha código, subir na pasta `code` e adicionar observações no `readme` caso necessário

2020-12-27 15:31 UTC, fernandascovino commented on bases/br_cgu_servidores_executivo_federal/servidores_militares_cadastro/table_config.yaml
> +    A descrever no futuro.
Se não foi feito nenhum tratamento, deixar com `<A descrever>`

2020-12-27 15:34 UTC, fernandascovino requested changes
Para mudar:
- [ ] Adicionar pasta `code` com `readme`
- [ ] Adicionar mínimo de colunas que identificam uma linha única em `observation_level` - é somente `id_servidor` ou esse pode se repetir entre linhas com diferentes `id_atividade`?
- [ ] Verificar comentários e sugestões adicionais

2020-12-27 15:40 UTC, fernandascovino commented
> @hsxavier acho que você precisa dar permissão para eu poder mexer no pull request dado que vem de um fork na tua conta. Quero tentar publicar no BQ e ver se precisa de ajustes.

Sim, não achei a base no BigQuery para testar os dados...

2021-01-04 01:35 UTC, rdahis commented
É para fechar essa PR então, dado a PR versão nova?

2021-01-04 16:04 UTC, closed without merging