Add view do DOU a partir do gabinete-compartilhado
basedosdados/mais pull request #184
Opened 2020-11-27 23:41 UTC by hsxavier

Acho que esse commit inclui a adição da base de militares (não voltei ao estágio anterior antes de fazer esse branch).

2020-11-28 00:00 UTC, rdahis approved these changes

2020-11-28 00:00 UTC, rdahis commented on bases/br_imprensa_nacional_dou/original/publish.sql
> +SELECT
Os tipos aqui já estão todos resolvidos? Não precisa do SAFE_CAST?

2020-12-02 15:10 UTC, hsxavier commented on bases/br_imprensa_nacional_dou/original/publish.sql
> +SELECT
Sim. O tratamento já foi feito com SQL em views do gabinete-compartilhado.

2020-12-08 03:59 UTC, fernandascovino requested changes
@hsxavier está pendente aqui ainda resolver sobre a query no BQ, correto? não está rodando... vou deixar aqui bloqueado enquanto isso

2020-12-14 22:40 UTC, fernandascovino commented
@hsxavier carregou aqui depois de 2min haha
![image](https://user-images.githubusercontent.com/20743819/102144355-1a027900-3e44-11eb-9bb8-eb532d60b8f9.png)

2021-01-04 01:34 UTC, rdahis commented
É para fechar essa PR então, dado a versão nova?

2021-01-04 23:29 UTC, closed without merging