censo2010
basedosdados/mais pull request #188
Opened 2020-11-30 18:48 UTC by d116626

Informações do censo2010 por setor censitário

2020-12-23 01:57 UTC, rdahis requested changes
Basicamente tudo ótimo, exceto alguns detalhes de nomes de variável, escopo, etc que se repetem entre todas as tabelas. E uma coisa de mover a tabela básica para uma tabela de diretório em outro dataset.

2020-12-27 15:19 UTC, fernandascovino commented on bases/br_ibge_censo2010/alfabetizacao_homens_mulheres_setor_censitario/publish.sql
> +SAFE_CAST(cod_setor AS INT64) cod_setor,
@d116626 por padrao nao usamos `cod` , mas sim `id` - mais padroes aqui: https://docs.google.com/spreadsheets/d/1r4UqWx3d2jaRpoqp3ZkmJ07kerVP6KRO0unfchrOIuY/edit?usp=sharing

2020-12-27 15:19 UTC, fernandascovino commented on bases/br_ibge_censo2010/alfabetizacao_homens_mulheres_setor_censitario/table_config.yaml
> +    - BR
```suggestion
    - brasil
```

2020-12-27 15:22 UTC, fernandascovino commented on bases/br_ibge_censo2010/alfabetizacao_total_setor_censitario/schema-prod.json
> +[{"name": "cod_setor", "description": "C\u00f3digo do setor censit\u00e1rio", "is_in_staging": true, "is_partition": false, "type": "INTEGER", "mode": "NULLABLE"}, {"name": "sigla_uf", "description":
mudar para id_setor_censitario

2020-12-27 15:25 UTC, fernandascovino requested changes

2020-12-27 15:25 UTC, fernandascovino commented on bases/br_ibge_censo2010/alfabetizacao_total_setor_censitario/schema-staging.json
> +[{"name": "cod_setor", "description": "<descri\u00e7\u00e3o da coluna>", "is_in_staging": true, "is_partition": false, "type": "STRING"}, {"name": "situacao_setor", "description": "<descri\u00e7\u00e
mudar para id_setor_censitario

2020-12-27 15:25 UTC, fernandascovino commented on bases/br_ibge_censo2010/alfabetizacao_total_setor_censitario/table_config.yaml
> +    - name: cod_setor
```suggestion
    - name: id_setor_censitario
```

2020-12-27 15:25 UTC, fernandascovino commented on bases/br_ibge_censo2010/alfabetizacao_total_setor_censitario/table_config.yaml
> +    - cod_setor
```suggestion
    - id_setor_censitario
```

2020-12-27 15:25 UTC, fernandascovino commented on bases/br_ibge_censo2010/basico_setor_censitario/publish.sql
> +/*
não sei se entendi aqui @rdahis , você tiraria da organização IBGE para BD? Por quê?

2021-01-04 00:58 UTC, rdahis commented on bases/br_ibge_censo2010/basico_setor_censitario/publish.sql
> +/*
Sim! Porque estritamente falando esses não são dados do censo. São mais gerais sobre setores censitários.

E vamos construindo diretórios para cada nível de observação possível (setor censitário, município, uf, políticos, etc).

2021-01-27 09:50 UTC, d116626 commented
@rdahis  e @fernandascovino, acho que esse ultimo commit resolve todas as questões levantadas.

2021-01-27 12:23 UTC, d116626 commented on bases/br_ibge_censo2010/alfabetizacao_homens_mulheres_setor_censitario/publish.sql
> +/*
Acabei seguindo o mesmo esquema de tabelas do IBGE por causa dos arquivos de referência.

2021-02-16 22:56 UTC, d116626 commented
@fernandascovino @rdahis aquiiiiiii!!!! (;

2021-02-21 15:24 UTC, d116626 commented
@rdahis @fernandascovino deem uma olhadinha nesse PR pf. (;

2021-02-22 01:10 UTC, fernandascovino commented on bases/br_ibge_censo2010/basico_setor_censitario/publish.sql
> +/*
@d116626 essa tabela deveria existir ainda?

2021-02-22 01:26 UTC, d116626 commented on bases/br_ibge_censo2010/basico_setor_censitario/publish.sql
> +/*
Sim, só separei os identificadores que apareciam em todas as tabelas e criei uma tabela `setor_censitario` no dataset `br_bd_diretorios_brasil`, que mapeia todas as outras tabelas pelo `id_setor_censitario`.

2021-02-23 06:51 UTC, rdahis commented
Meu último comentário é só: vamos unificar as tabelas `entorno*_setor_censitario` em `entorno_setor_censitario`? Tem centenas de colunas mas tudo bem. De resto tá ótimo.

No futuro vamos ter que dar uma reformulada nos nomes de datasets de censo. Já estou subindo o `br_ibge_censo_demografico` com microdados. Depois unificamos com o nível de setor censitário, município, etc.

2021-02-27 18:37 UTC, d116626 commented
@rdahis Feito! Também atualizei as configs pra verão 1.4.* e subi pro basedosdados-dev

2021-02-27 19:49 UTC, rdahis commented on bases/br_bd_diretorios_brasil/setor_censitario/publish.sql
> +/*
Tem que tirar esses arquivos daqui dado que você abriu o PR #306?

2021-02-27 19:51 UTC, rdahis commented
Pode deletar a base no `basedosdados` antes de darmos o merge?

2021-02-27 19:53 UTC, d116626 commented on bases/br_bd_diretorios_brasil/setor_censitario/publish.sql
> +/*
Já foi deletado

2021-02-27 19:53 UTC, rdahis approved these changes

2021-02-27 21:49 UTC, merged