Sobe bens_candidato e atualiza códigos do dataset.
basedosdados/mais pull request #202
Opened 2020-12-23 20:38 UTC by rdahis

2020-12-27 15:14 UTC, fernandascovino requested changes
Quanto aos códigos de `bens_candidato`:
- [ ] Adicionar coluna identificadora de `item`
- [ ] Adicionar `readme` na pasta `code` indicando quais tabelas/conjuntos estão ou não sendo tratados, dado que já existem outros
- [ ] Corrigir colunas de identificação de abrangência - nenhuma existe na tabela
- [ ] Verificar comentários e sugestões adicionais

Vou ainda verificar as demais mudanças em outras tabelas.

2020-12-27 15:14 UTC, fernandascovino commented on bases/br_tse_eleicoes/bens_candidato/table_config.yaml
> +    code_url: https://github.com/basedosdados/mais/tree/master/bases/br_tse_eleicoes/code # REQUIRED
Tem tratamento dessa tabela na pasta `code`? Sinto que falta um `readme` lá com alguma indicação de quais tabelas estão sendo tratadas com o código, pois já tem várias desse conjunto de dados

2020-12-27 15:14 UTC, fernandascovino commented on bases/br_tse_eleicoes/bens_candidato/table_description.txt
> +Website:
Não deveria ter algo aqui?
```suggestion
Website: https://basedosdados.org/dataset/br-tse-eleicoes
```

2020-12-27 15:14 UTC, fernandascovino commented on bases/br_tse_eleicoes/bens_candidato/table_description.txt
> +Github: https://github.com/basedosdados/mais/
E aqui também:
```suggestion
Github: https://github.com/basedosdados/mais/tree/master/bases/br_tse_eleicoes
```

2020-12-27 15:14 UTC, fernandascovino commented on bases/br_tse_eleicoes/bens_candidato/table_config.yaml
> +    - candidato
**1.859.974 resultados da tabela com `id_tipo_item` nulo** - não pode ser um identificador, não existe um identificador único do item aqui correto? Teríamos que criar aqui

2020-12-27 15:39 UTC, fernandascovino commented on bases/br_tse_eleicoes/bens_candidato/table_description.txt
> +Website:
[Vi agora que vem de `url_ckan`](https://github.com/basedosdados/mais/blob/18be284a45b35094d249684026e79f7676a37cab/basedosdados/configs/templates/dataset/dataset_description.txt) - tem muitas bases sem esse campo preenchido... abro um issue?

2021-01-04 01:19 UTC, rdahis commented on bases/br_tse_eleicoes/bens_candidato/table_config.yaml
> +    - candidato
Pois é. Mesma discussão do outro PR da RAIS com vínculos. Não tem identificador na base original, e não vejo tanta utilidade criar um para item aqui.

2021-01-04 01:21 UTC, rdahis commented on bases/br_tse_eleicoes/bens_candidato/table_description.txt
> +Website:
Isso é aquele problema que mencionei em outro lugar, que o site no .yaml não tá sendo convertido pro table_description.txt.

2021-01-04 01:22 UTC, rdahis commented on bases/br_tse_eleicoes/bens_candidato/schema-prod.json
> +[{"name": "tipo_eleicao", "description": "Tipo da Elei\u00e7\u00e3o", "is_in_staging": true, "is_partition": false, "type": "STRING", "mode": "NULLABLE"}, {"name": "sequencial_candidato", "descriptio
É isso aí mesmo! Essas colunas aparecem no `schema-prod.json` depois já que são partições.

2021-01-04 01:30 UTC, rdahis commented
Vou deixar essa PR aberta até o @d116626 criar as tabelas de financiamento de campanha para checarmos se está faltando coisas aqui ou não.

2021-01-04 15:59 UTC, fernandascovino commented on bases/br_tse_eleicoes/bens_candidato/table_config.yaml
> +    - candidato
Respondi lá com algumas opções. Podemos bater o martelo em cima delas - se for o caso de deixar como nível algo que "não é observável" no dado, colocamos junto na descrição da tabela a explicação sobre o nível.

2021-01-11 19:53 UTC, rdahis commented
Deixando alguns comentários e dúvidas a serem esclarecidas antes de um merge:

- [ ] Por que quebraram receitas entre candidato e candidato_doador_originario pós 2018? A solução é só um append?
- [ ] Como lidar com as quebras de arquivos em diferentes entidades ao longo dos anos?
  - 2002, 2004, 2006, 2008: candidato, comitê
  - 2010, 2012, 2014 (receitas/despesas): candidato, comitê, partido
  - 2018, 2020: candidato (candidato / doador_originario), orgão partidario, CNPJ de campanha
- [ ] Por que só tem arquivos suplementares em 2014 e 2016?

2021-02-13 00:47 UTC, d116626 approved these changes
Já vou deixar aprovado, pode dar o merge e checar se o table-approve vai funcionar (;

2021-02-13 01:26 UTC, closed without merging