Adiciona microdados SRAG 2020.
basedosdados/mais pull request #216
Opened 2021-01-11 20:13 UTC by rdahis

Falta fazer:
- [ ] Escrever todas as descrições de variáveis.
- [ ] Gerar agregações interessantes a nível de município e UF.

2021-01-22 03:01 UTC, d116626 commented on bases/br_ms_srag2020/microdados/table_config.yaml
> +columns: # REQUIRED
todas as colunas estão sem descrição

2021-01-22 03:06 UTC, d116626 reviewed
- Todas as colunas estão sem descrição
- Rodei a query no staging e foi tudo normal, porem no basedosdados recebi o erro: `Unrecognized name: sigla_uf_notificacao; Did you mean semana_notificacao?; failed to parse view 'basedosdados.br_ms_srag2020.microdados' at [6:11]`

2021-02-04 03:00 UTC, fernandascovino commented on bases/br_ms_srag2020/dataset_config.yaml
> +    - COVID-19
@rdahis nao vale mais tags aqui? `problemas respiratorios`, `sistema de saude`, etc

2021-02-04 03:08 UTC, fernandascovino requested changes
falta adicionar as descrições e ver os demais comentários ;)

2021-02-04 03:08 UTC, fernandascovino commented on bases/br_ms_srag2020/microdados/table_config.yaml
> +columns: # REQUIRED
@rdahis aqui!

2021-02-04 03:08 UTC, fernandascovino commented on bases/br_ms_srag2020/microdados/table_config.yaml
> +columns: # REQUIRED
@rdahis vale inclusive indicar nas colunas que mudamos alguma coisa (`sexo`, `fator_risco`) o que mudamos exatamente.

2021-02-04 03:08 UTC, fernandascovino commented on bases/br_ms_srag2020/microdados/table_description.txt
> +- 2020
@rdahis são somente 2020 mesmo? a galera usa de + tempo: https://twitter.com/Capyvara/status/1331253346007703552

2021-08-18 12:49 UTC, closed without merging