Adicionando a base da Pesquisa Agrícola Municipal (br_ibge_pam)
basedosdados/mais pull request #228
Opened 2021-01-20 06:04 UTC by mavalentim

Tentando adicionar a base da PAM via Pull Request. A base da PAM contém dados municipais anuais de mais de 70 produtos agrícolas. Acredito que está com a compartimentação adequada com relação às outras bases.

2021-01-22 06:49 UTC, rdahis requested changes
Ótimo começo! Deixei comentários marcando uns detalhes que vão ser importantes pra replicar pras próximas tabelas que você for subir também.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/code/lavouras_permanentes_f.R
> +perca_dedcolheita1 <- read.csv("C:/Users/Matheus/Desktop/bdmais/agro2/percdedcol/percdedcol1.csv", header=FALSE, comment.char="#")
Mesmo comentário de path.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/code/lavouras_permanentes_f.R
> +perca_dedcolheita2 <- read.csv("C:/Users/Matheus/Desktop/bdmais/agro2/percdedcol/percdedcol2.csv", header=FALSE, comment.char="#")
Mesmo comentário de path.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/code/lavouras_permanentes_f.R
> +perc_valor_prod3 <- read.csv("C:/Users/Matheus/Desktop/bdmais/agro2/percvalorprod/w3.csv", header=FALSE, comment.char="#")
Mesmo comentário de path.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(ano AS DATE) ano,
`ano` entra como INT64

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(a_colhida AS INT64) a_colhida,
Cuidado com a consistência na nomeação de variáveis. Aqui tem que ser `area_colhida`.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(area_ded_colheita AS INT64) area_ded_colheita,
O que `ded` significa?

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(perc_a_dedcolheita AS FLOAT64) perc_a_dedcolheita,
Em vez de `perc` a gente usa `prop`. E os valores são entre 0-100, ao invés de 0-1.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(perca_colhida AS FLOAT64) perca_colhida,
Aqui seria `prop_area_colhida`.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(rend_medio AS INT64) rend_medio,
`rend` é pra ser `rendimento`? Pode pecar sempre por nomes mais explicativos do que abreviações. Para abreviações e prefixos, veja o nosso manual de estilo [aqui](https://docs.google.com/spreadsheets/d/1r4UqWx3d2jaRpoqp3ZkmJ07kerVP6KRO0unfchrOIuY/edit#gid=0).

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(perc_valor_prod AS FLOAT64) perc_valor_prod,
`perc` pra `prop`.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
> +        description: Identifica a qual ano aquela observação pertence, varia entre 1974 e 2019.
Só "Ano" aqui.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
> +        description: Identifica o município utilizando o código do IBGE de 7 dígitos.
Olha os descriptions no diretório de municípios brasileiros pra copiar pra cá. Nesse caso é "ID Município - IBGE 7 Dígitos"

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
> +        description: Identifica a qual produto agrícola aquela observação se refere.
Pode tirar esses verbos no começo, como "identifica a", "refere-se a", etc de todas as colunas.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_temporarias/publish.sql
> +SAFE_CAST(ano AS DATE) ano,
Mesmos comentários aqui do outro publish.sql.

2021-01-22 06:49 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
> +        description: Identifica o município utilizando o código do IBGE de 7 dígitos.
Mesmos comentários para descriptions.

2021-01-22 16:06 UTC, d116626 commented on bases/br_ibge_pam/code/lavouras_permanentes_f.R
> +a_dedcolheita1 <- read.csv("C:/Users/Matheus/Desktop/bdmais/agro2/dedcol/dedcol1.csv", header=FALSE, comment.char="#")
Uma dica boa pro futuro seria utilizar funções quando tem muitas repetições de código. Outra forma de diminuir repetição seria importar os arquivos separados de uma vez só, [como nesse exemplo](https://stackoverflow.com/questions/11433432/how-to-import-multiple-csv-files-at-once).

2021-02-01 20:32 UTC, fernandascovino commented
@rdahis verificar aqui as alteracoes, @mavalentim  favor sempre colocar uma comentario marcando a pessoa depois de alterar! :)

2021-02-01 20:34 UTC, fernandascovino commented
> Tentando adicionar a base da PAM via Pull Request. A base da PAM contém dados municipais anuais de mais de 70 produtos agrícolas. Acredito que está com a compartimentação adequada com relação às outras bases.

Não gosto de tentar: você está **adicionando**! :) vou fazer as revisões aqui

2021-02-01 20:47 UTC, fernandascovino approved these changes
Por mim está fechado! @rdahis sófaltou a parte da área que está em hectares, subimos assim mesmo?

2021-02-01 20:47 UTC, fernandascovino commented on bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
> +        description: Área, em hectares, dedicada ao plantio.
@mavalentim por padrao usamos km2, @rdahis ele troca direto nessa coluna ou add uma nova?

2021-02-01 20:47 UTC, fernandascovino commented on bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
> +        description: Área, em hectares, dedicada ao plantio.
padrão: https://docs.google.com/spreadsheets/d/1r4UqWx3d2jaRpoqp3ZkmJ07kerVP6KRO0unfchrOIuY/edit#gid=0

2021-02-01 20:47 UTC, fernandascovino commented on bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
> +        name: area_colhida
mesmo comentário da `area_plantada`

2021-02-01 20:47 UTC, fernandascovino commented on bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
> +        description: Área, em hectares, dedicada ao plantio.
mesmo comentário sobre km2

2021-02-01 20:47 UTC, fernandascovino commented on bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
> +        name: area_colhida
mesmo cmentario sobre km2

2021-02-06 18:44 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/table_config.yaml
> +        description: Área, em hectares, dedicada ao plantio.
Que nem falamos na reunião de dados, eu voto em o padrão ser disponibilizarmos uma única coluna em `km2`. E esse continuar sendo o padrão no repositório inteiro.

2021-02-06 18:56 UTC, rdahis requested changes
Faltou:

- [ ] Dar o `table publish` para vermos o produto final.
- [ ] Mudar todas células com valores `-` ou `...` para vazio.

2021-02-06 18:56 UTC, rdahis commented on bases/br_ibge_pam/code/permanente_otimizado.R
> +# ADENDOS -------------------
Tá mais bonito o código :-). Pode tirar o `otimizado` dos nomes porque é contra o espírito de versionamento de arquivos.

2021-02-06 18:56 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_permanentes/publish.sql
> +SAFE_CAST(moeda_do_valor_da_prod AS STRING) moeda_do_valor_da_prod
Fiquei confuso com essa variável.

1. Vamos renomear para `moeda_valor_producao`.
2. Por que tem valores `Mil reais`? A moeda deveria ser só `Real`, `Cruzeiro`, etc. E as variáveis de valor são sempre em unidades de 1, não de 1000. Se tiver em 1000 tem que mudar.

2021-02-06 18:56 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_temporarias/publish.sql
> +SAFE_CAST(moeda_do_valor_da_prod AS STRING) moeda_do_valor_da_prod
Mesmos comentários para a outra variável de moeda acima.

2021-02-06 18:56 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
> +        description: Ano.
Só `Ano`, sem ponto.

2021-02-06 18:56 UTC, rdahis commented on bases/br_ibge_pam/municipio_lavouras_temporarias/table_config.yaml
> +        description: Estado onde o município se localiza através dos dois primeiros dígitos do id_municipio.
Segue a descrição dos diretórios. Acho que é só `ID Unidade da Federação - IBGE 2 Dígitos`.

2021-02-12 23:51 UTC, rdahis commented
@mavalentim termina por favor esses comentários para podermos aprovar o PR? antes de mergulhar nos dados de educação.

2021-02-17 21:58 UTC, rdahis commented
@mavalentim Acho que você subiu um commit de dados da SEDUC aqui nesse PR? Dá uma olhada e caso sim, tem que reverter e criar um PR separado.

2021-02-23 01:06 UTC, closed without merging

2021-02-23 01:06 UTC, mavalentim commented
fechando o PR para abrir um via branch