Upload dos dados referente a pesquisa pecuária municipal
basedosdados/mais pull request #229
Opened 2021-01-20 18:35 UTC by crislanealves

Upload dos dados referente a pesquisa pecuária municipal do ibge

2021-01-22 23:04 UTC, rdahis requested changes
Ótimo começo! Deixei comentários gerais que vão se repetir em futuras bases também.

2021-01-22 23:04 UTC, rdahis commented on bases/br_ibge_ppm/code/ppm.R
> +for ( i in 1:1537044) {
Melhor tirar esse número `1537044` hardcoded assim pra se mudar no futuro. Vê como botar parâmetro do número de linhas do arquivo.

2021-01-22 23:04 UTC, rdahis commented on bases/br_ibge_ppm/code/ppm.R
> +                "excluir2", "producao_aquicultura_quilogramas"),
Pode tirar `quilogramas` aqui e botar a unidade na descrição da variável no `table_config.yaml`. Aqui e no resto do código.

2021-01-25 20:57 UTC, d116626 commented on bases/br_ibge_ppm/code/ppm.R
> +
Uma dica pro futuro seria utilizar funções quando tem muitas repetições de código.

2021-01-28 21:10 UTC, crislanealves commented
Todas as alterações sugeridas foram realizadas.

2021-02-01 20:32 UTC, fernandascovino commented
@rdahis verificar aqui as alteracoes, @crislanealves favor marcar sempre a pessoa! :)

2021-02-01 20:55 UTC, fernandascovino commented on bases/br_ibge_ppm/dataset_config.yaml
> +    name: Instituto Brasileiro de Geografia e Estatística
é da SIDRA, mas todas as bases da SIDRA estão como ibge no catalogo: https://basedosdados.org/dataset/?q=sidra

2021-02-01 21:03 UTC, fernandascovino approved these changes
No geralaprovado, rever pequenos detalhes marcados nos comentários

2021-02-01 21:03 UTC, fernandascovino commented on bases/br_ibge_ppm/efetivo_rebanhos/table_config.yaml
> +treatment_description: |
@crislanealves houve algum passo de tratamento? "Juntei as tabelas de diferentes anos ...." por favor adicionara aqui.

2021-02-01 21:03 UTC, fernandascovino commented on bases/br_ibge_ppm/producao_origem_animal/publish.sql
> +SAFE_CAST(valor_producao_percentual_total_geral AS FLOAT64) valor_producao_percentual_total_geral,
@rdahis aqui seria `prop_valor_producao` nao?
```suggestion
SAFE_CAST(prop_valor_producao AS FLOAT64) prop_valor_producao,
```

2021-02-06 18:25 UTC, rdahis commented on bases/br_ibge_ppm/producao_origem_animal/publish.sql
> +SAFE_CAST(valor_producao_percentual_total_geral AS FLOAT64) valor_producao_percentual_total_geral,
Acho que sim!

2021-02-06 18:41 UTC, rdahis requested changes
Comentários gerais, além dos específicos na revisão:

- Fiquei confuso sobre se precisa da tabela `dados_pecuaria` separada. Esses dados não estão dentro das outras tabelas?De qualquer jeito, vamos renomear essa tabela para algo mais informativo. Talvez `producao_pecuaria`?

- [x] Dar o `table publish` pra vermos como vai ficar o produto final, com todas descrições e tipos de variáveis ajustados.
- [x] Mudar vírgula para ponto nos divisores de decimal para todas variáveis `FLOAT64`.

2021-02-06 18:41 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(producao_aquicultura AS INT64) producao_aquicultura,
Mudar para só `producao`.

2021-02-06 18:41 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(valor_producao_mil_reais AS INT64) valor_producao_mil_reais,
Mudar para `valor_producao` e multiplicar por 1000 para a unidade ficar em 1 real.

2021-02-06 18:41 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(valor_producao_percentual_total_geral AS FLOAT64) valor_producao_percentual_total_geral
Mudar pra `prop_valor_producao`.

2021-02-06 18:41 UTC, rdahis commented on bases/br_ibge_ppm/producao_origem_animal/publish.sql
> +SAFE_CAST(tipo_de_produto_origem_animal AS STRING) tipo_de_produto_origem_animal,
Mudar para `tipo_produto`.

2021-02-06 18:41 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(valor_producao_mil_reais AS INT64) valor_producao_mil_reais,
Aqui não tem a variável `moeda`?

2021-02-06 18:41 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(tipo_de_produto AS STRING) tipo_de_produto,
Renomear para `tipo_produto`.

2021-02-11 13:44 UTC, crislanealves commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(valor_producao_mil_reais AS INT64) valor_producao_mil_reais,
Posso adicionar se considerar necessário, mas moeda é a mesma.

2021-02-11 18:59 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(valor_producao_mil_reais AS INT64) valor_producao_mil_reais,
Eu criaria para consistência entre tabelas. E vamos mudar também essa variável para `valor_producao` para consistência também.

2021-02-11 19:09 UTC, crislanealves commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(valor_producao_mil_reais AS INT64) valor_producao_mil_reais,
Desculpa. Veja se compreendi. É para (1) adicionar um coluna ``moeda`` e (2) alterar o ``valor_producao_mil_reais`` para `` valor_producao``. É isso?

2021-02-12 17:08 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/publish.sql
> +SAFE_CAST(valor_producao_mil_reais AS INT64) valor_producao_mil_reais,
Isso :-)

2021-02-12 23:53 UTC, rdahis commented
@crislanealves prioriza fechar os últimos comentários aqui por favor para podermos aprovar esse PR?

2021-02-14 23:47 UTC, crislanealves commented
**Principais alterações:** @rdahis 

- [x] Mudar vírgula para ponto nos divisores de decimal para todas variáveis ```FLOAT64```.
- [x] Mudar de ```valor_producao_mil_reais``` para ```valor_producao``` e multiplicar por 1000 para a unidade ficar em 1 real.
- [x] Alterar colunas ```valor_producao_percentual_total_geral``` para ```prop_valor_producao```.
- [x] Alterar colunas ```tipo_de_produto``` para ```tipo_produto```.
- [x] Adicionar a variável ```moeda``` nas tabelas necessárias.

2021-02-15 05:03 UTC, rdahis requested changes
Quase pronto!

- Só mais um comentário de nível da observação abaixo.
- Faltou dar um `table publish` com `--if_exists replace` porque agora no BQ está faltando os tipos e descrições das variáveis.

<img width="591" alt="Screen Shot 2021-02-14 at 9 02 45 PM" src="https://user-images.githubusercontent.com/6617207/107907278-1c4a8780-6f08-11eb-9204-ceb3a1fe8d2c.png">

2021-02-15 05:03 UTC, rdahis commented on bases/br_ibge_ppm/producao_aquicultura/table_config.yaml
> +    - ano
Faltou `produto` aqui né?

2021-02-15 13:07 UTC, crislanealves commented
@rdahis  dei o ```table_publish``` mas tá assim agora. É normal ? 
![WhatsApp Image 2021-02-15 at 10 07 01](https://user-images.githubusercontent.com/58278652/107950541-99f8ac80-6f75-11eb-94d3-5eca824d7605.jpeg)

2021-02-15 17:54 UTC, rdahis commented
Não. Tá dando algum problema com encoding. @JoaoCarabetta @Hellcassius @d116626

2021-02-23 07:30 UTC, rdahis commented
Vamos esperar resolver o PR #286 para você publicar de novo e darmos o merge.

2021-02-26 02:10 UTC, crislanealves commented
- [x] ``table publish``
- [x] ``dataset update``

@rdahis parece que ficou tudo certo lá no BQ.

2021-02-26 04:39 UTC, rdahis approved these changes

2021-02-26 04:42 UTC, merged