Subindo dados do INEP para o Github
basedosdados/mais pull request #234
Opened 2021-01-25 20:38 UTC by Hevilyn

2021-01-25 20:47 UTC, d116626 commented on bases/br_inep_indicadores_educacionais/media_horas_aula_diaria/publish.sql
> +SAFE_CAST(id_municipio AS STRING) id_municipio,
ajustar os tipos das colunas, por exemplo id_municipo é INT64 .

2021-01-25 22:24 UTC, fernandascovino requested changes
@Hevilyn @rdahis tem que mudar o nome dessa tabela para `media_horas_aula_diaria_municipio` ou esses dados vão ser adicionados na tabela `br_inep_indicadores_educacionais.municipio`? 

porque esses são somente a nível municipio, e tem tambemescolas, ufs, brasil, regiao

2021-01-25 22:24 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/media_horas_aula_diaria/table_config.yaml
> +treatment_description: |
@Hevilyn pode descrever mais aqui: Normalização de nomes de colunas, etc. Descreve também como você juntou bases de diferentes anos, quais colunas tiveram que ser alteradas... :)

2021-01-25 22:24 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/media_horas_aula_diaria/table_config.yaml
> +description: |  # REQUIRED
@Hevilyn tem alguma descrição da tabela do próprio INEP? Se tiver, colocar aqui!

2021-01-25 22:29 UTC, Hevilyn commented
> @Hevilyn @rdahis tem que mudar o nome dessa tabela para `media_horas_aula_diaria_municipio`ou esses dados vão ser descritos na tabela `br_inep_indicadores_educacionais.municipio`?
> 
> porque esses são somente a nível municipal, e tem tambemescolas, ufs, brasil, região

2021-01-25 22:29 UTC, closed without merging

2021-01-25 22:37 UTC, Hevilyn commented
> @Hevilyn @rdahis tem que mudar o nome dessa tabela para `media_horas_aula_diaria_municipio`ou esses dados vão ser descritos na tabela `br_inep_indicadores_educacionais.municipio`?
> 
> porque esses são somente a nível municipal, e tem tambemescolas, ufs, brasil, região



> @Hevilyn @rdahis tem que mudar o nome dessa tabela para `media_horas_aula_diaria_municipio` ou esses dados vão ser adicionados na tabela `br_inep_indicadores_educacionais.municipio`?
> 
> porque esses são somente a nível municipio, e tem tambemescolas, ufs, brasil, regiao

Eu acho que no table create ele criou uma nova tabela ao invés de incluir em município, faço o BQ de novo ?

2021-01-27 18:10 UTC, rdahis commented
> Eu acho que no table create ele criou uma nova tabela ao invés de incluir em município, faço o BQ de novo ?

Vamos refazer a tabela `municipio` do zero já incluindo todos os indicadores, como havíamos falado. Aí teremos que ter aquele cuidado com os prefixos (tipo `atu`) para ficar consistente.

2021-01-27 18:11 UTC, rdahis commented
Assim teremos uma tabela para cada nível de observação: brasil, regiao, uf, municipio, escola.