[dados] br_mobilidados_indicadores
basedosdados/mais pull request #265
Opened 2021-02-10 23:41 UTC by crislanealves

Indicadores mobilidados.

2021-02-15 00:10 UTC, crislanealves commented
- [ ] diminuir o código.

2021-02-15 05:27 UTC, rdahis requested changes
Legal, ótimo trabalho. Várias tabelas!

- [ ] Deletar o arquivo `bases/br_ibge_ppm/code/.Rhistory`.
- [x] Incluir as seguintes linhas no topo de todos os `table_config.yaml`, por conta da versão 1.4.
    - source_bucket_name: basedosdados-dev
    - project_id_staging: basedosdados-dev
    - project_id_prod: basedosdados-dev
- [x] Prestar atenção nos campos dos `table_config`. Em todos faltou nível da observação, tava com o v1.0 com <>, e com o `sigla_uf` desnecessário em todos os `primary_keys`.
- [ ] Rodar o `table publish` com todas as tabelas, porque estão todas sem as informações lá no bigquery.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tx_motorizacao/publish.sql
> +/*
Vamos chamar essa tabela de `taxa_motorizacao`.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/emissoes_CO2_material_particulado/publish.sql
> +/*
Todo nome de tabela tem que ser com letras minúsculas. Então `emissoes_co2_material_particulado`.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/emissoes_CO2_material_particulado/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_domicilios_infra_urbana/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_domicilios_infra_urbana/table_config.yaml
> +    -
Aqui é:

- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/table_config.yaml
> +    -
Seria

- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_mortes_negras_acidente_transporte/table_config.yaml
> +
Deletar essa linha em branco.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_pessoas_prox_infraestrutura_cicloviaria/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_pessoas_prox_infraestrutura_cicloviaria/table_config.yaml
> +    -
- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_pessoas_próximas_pnt/publish.sql
> +SAFE_CAST(prop_pnt AS FLOAT64) prop_pnt
O que é `pnt`? Vale deixar a palavra por extenso?

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_pessoas_próximas_pnt/table_config.yaml
> +-
- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tempo_deslocamento_casa_trabalho/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tempo_deslocamento_casa_trabalho/table_config.yaml
> +    -
- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tempo_deslocamento_casa_trabalho/table_config.yaml
> +    - sigla_uf;
Pra todas as tabelas, tira o `sigla_uf` aqui. Porque `id_municipio` e `ano` já identificam cada linha unicamente.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/transporte_media_alta_capacidade/table_config.yaml
> +    -
- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/transporte_media_alta_capacidade/table_config.yaml
> +    - sigla_uf
Tirar `sigla_uf`.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tx_motorizacao/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tx_motorizacao/table_config.yaml
> +    - sigla_uf
Tirar o `sigla_uf`.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tx_motorizacao/table_config.yaml
> +    -
- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/tx_motorizacao/publish.sql
> +SAFE_CAST(taxa_motorizacao_capitais AS INT64) taxa_motorizacao_capitais
Podemos chamar a variável só de `taxa_motorizacao` dado que as capitais já estão identificadas nas linhas da tabela?

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/proporcao_pessoas_próximas_pnt/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
> +    - sigla_uf
Tirar `sigla_uf`.

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
> +    -
- municipio
- ano

2021-02-15 05:27 UTC, rdahis commented on bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
> +version: <v1.0> # REQUIRED
Tirar o <>.

2021-02-17 22:48 UTC, crislanealves commented on bases/br_mobilidados_indicadores/proporcao_pessoas_próximas_pnt/publish.sql
> +SAFE_CAST(prop_pnt AS FLOAT64) prop_pnt
Boa questão. PNT é a sigla para _People Near Transit_. Neste caso é o ``Percentual de pessoas próximas da rede de transporte de média e alta capacidade``. Pode ser ``pessoas_prox_transporte`` ?

2021-02-19 20:11 UTC, crislanealves commented
@rdahis realizei as modificações sugeridas. Ainda não dei o ``table publish`` porque ainda apresenta aquele problema de ``encoding``.

2021-02-23 07:34 UTC, rdahis commented
Tá ótimo. Esperando resolver com o PR #286.

2021-02-26 02:12 UTC, crislanealves commented
- [x] ``table publish``
- [x] ``dataset update``

@rdahis parece que ficou tudo certo lá no BQ.

2021-02-26 05:53 UTC, rdahis requested changes
Pequenos comentários mais.

2021-02-26 05:53 UTC, rdahis commented on bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/publish.sql
> +SAFE_CAST(comprotimento_salario_minimo AS INT64) comprotimento_salario_minimo,
Typo aqui para `comprometimento`.

2021-02-26 05:53 UTC, rdahis commented on bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
> +        name: comprotimento_salario_minimo
Aqui também.

2021-02-26 05:53 UTC, rdahis commented on bases/br_mobilidados_indicadores/divisao_modal/table_config.yaml
> +    - municipio
Aqui é `sigla_uf` né?

2021-02-26 05:53 UTC, rdahis commented on bases/br_mobilidados_indicadores/divisao_modal/table_config.yaml
> +primary_keys:
Faltou `sigla_uf` também.

2021-02-26 05:58 UTC, d116626 requested changes
@crislanealves tem que adicionar os campos abaixo antes do `table_id` de todos os `table_config.yaml`

```
source_bucket_name: basedosdados-dev
project_id_staging: basedosdados-dev
project_id_prod: basedosdados-dev
```

2021-02-26 13:08 UTC, crislanealves commented on bases/br_mobilidados_indicadores/divisao_modal/table_config.yaml
> +primary_keys:
Em ``primary_keys`` precisa? Você solicitou exclusão em todos na correção anterior.

2021-02-26 13:10 UTC, crislanealves commented on bases/br_mobilidados_indicadores/divisao_modal/table_config.yaml
> +    - municipio
pode deixa com "_" nesse campo? ou é só **sigla uf**

2021-02-26 15:33 UTC, rdahis commented on bases/br_mobilidados_indicadores/divisao_modal/table_config.yaml
> +    - municipio
Ops bem observado. Quando é pra estado assim acho que estamos botando `uf`.

2021-02-26 20:07 UTC, d116626 commented
Aquele mesmo erro @crislanealves, na tabela `proporcao_domicilios_infra_urbana` 
![image](https://user-images.githubusercontent.com/8954716/109349370-9a862280-7854-11eb-8004-e4a94eee0639.png)

2021-02-26 21:01 UTC, d116626 commented
@rdahis só falta seu aprrove quanto aos configs e descrições

2021-03-01 18:36 UTC, rdahis requested changes

2021-03-01 18:36 UTC, rdahis commented on bases/br_mobilidados_indicadores/prop_pessoas_proximas_pnt/publish.sql
> +/*
Vamos chamar essa tabela de `proporcao_pessoas_proximas_pnt` para ficar consistente com as outras.

2021-03-02 03:28 UTC, crislanealves commented on bases/br_mobilidados_indicadores/prop_pessoas_proximas_pnt/publish.sql
> +/*
- [x] "- Vamos chamar essa tabela de ``proporcao_pessoas_proximas_pnt`` para ficar consistente com as outras."

Modifiquei o nome da coluna também. De ``prop_pnt`` para ``prop_pessoas_proximas_pnt``. Acho que fica mais objetivo assim. @rdahis

2021-03-02 04:50 UTC, rdahis approved these changes

2021-03-02 04:52 UTC, rdahis commented
Dando merge agora. Os comentários do review do @d116626 já foram resolvidos.

2021-03-02 04:53 UTC, merged