Adiciona base das leis de Feira de Santana (BA)
basedosdados/mais pull request #266
Opened 2021-02-11 07:28 UTC by anapaulagomes

Closes #259.

2021-02-14 18:38 UTC, rdahis requested changes
Boa! Ótimo ver a primeira subida de dados. Alguns comentários extras além dos específicos?

- O que é o arquivo `bases/br_ba_feiradesantana/input/leis.json`? Se for os dados originais pode deletar. Estamos criando ainda uma infra pra arquivos originais.

2021-02-14 18:38 UTC, rdahis commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +coverage_time:
Faltou preencher a cobertura temporal aqui.

2021-02-14 18:38 UTC, rdahis commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +coverage_geo:
Boa! Certinho =)

2021-02-14 18:38 UTC, rdahis commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +observation_level: #REQUIRED
Acho que o nível da observação é uma lei né? Ou projeto de lei?

2021-02-14 18:38 UTC, rdahis commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +version: <vA.B> # REQUIRED
Pode botar `v1.0`.

2021-02-14 18:38 UTC, rdahis commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +table_id: leis # AUTO GENERATED
@d116626 tem que atualizar esses metadados pra versão v1.4?

2021-02-14 18:38 UTC, rdahis commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +description: |  # REQUIRED
Começando em qual ano?

2021-02-14 18:38 UTC, rdahis commented
@d116626 @JoaoCarabetta como fazemos para testar as queries num projeto externo? O projeto necessariamente tem que ser público no bigquery?

2021-02-14 19:04 UTC, d116626 commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +table_id: leis # AUTO GENERATED
Isso, tem que adicionar as seguintes informações no topo do `table_config.yaml`: 
```
source_bucket_name: <bucket_name>
project_id_staging: <bigquery_project_staging>
project_id_prod: <bigquery_project_prod>
```
Que são respectivamente, `bucket_name`, `[gcloud-projects.staging][name]` e `[gcloud-projects.prod][name]`, que se encontram no arquivo `config.toml`, na pasta `~/.basedosdados`.

Ao atualizar o pacote do basedosdados pra versão 1.4.0 essas informações serão preenchidas automaticamente quando os arquivos de metadados forem gerados.

2021-02-14 19:06 UTC, d116626 commented
> @d116626 @JoaoCarabetta como fazemos para testar as queries num projeto externo? O projeto necessariamente tem que ser público no bigquery?

Acredito que sim, o @JoaoCarabetta pode saber melhor.

2021-02-14 21:44 UTC, mavalentim commented on bases/br_ba_feiradesantana/README.md
> +O projeto Dados Abertos de Feira conseguiu via Lei de Acesso à Informação
acho que ficaria mais claro especificar o que o projeto conseguiu, completar com "os dados" ou "os arquivos"

2021-02-14 21:44 UTC, mavalentim commented on bases/br_ba_feiradesantana/dataset_config.yaml
> +# É necessário registrar um usuário para baixar os dados originais?
aqui eu acho que seria "sim" por que o acesso à informação requer cadastro.

2021-02-14 21:44 UTC, mavalentim commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +        name: titulo
ana, aqui é mais uma dúvida do que qualquer coisa, mas teria como ter o número da Lei, talvez retirando do nome completo? O número ajuda muito porque é mais universal né? Talvez nao tenha como, posso estar querendo demais.

2021-02-14 23:58 UTC, crislanealves approved these changes

2021-02-16 17:51 UTC, anapaulagomes commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +coverage_time:
Infelizmente eu não tenho essa informação. 😳 O dado é muito desestruturado. Não temos nem a data; pra responder essa pergunta teríamos que parsear tudo e ainda assim não seria preciso. #Comofas?

2021-02-16 17:53 UTC, anapaulagomes commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +table_id: leis # AUTO GENERATED
Mas se eu rodar agora os arquivos serão sobreescritos, né?

Essas seções ficarão na raiz, abaixo de `table_id` então?

2021-02-16 17:55 UTC, anapaulagomes commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +        name: titulo
Rapaz, o problema é que não tem um padrão :( Seria ótimo mas o dado é meio cagado, então preferimos deixar do jeito que veio (o que garantiria melhor a integridade a essa altura).

2021-02-16 22:05 UTC, d116626 commented on bases/br_ba_feiradesantana/leis/table_config.yaml
> +table_id: leis # AUTO GENERATED
Isso, mas a gente pode inserir manualmente aqui, só passar os nomes que eu posso colocar. É só ir em `~/.basedosdados/config.toml` e ver `bucket_name`, `[gcloud-projects.staging][name]` e `[gcloud-projects.prod][name]`.

2021-02-22 15:52 UTC, crislanealves approved these changes

2021-02-23 07:33 UTC, rdahis commented
O projeto `dados-abertos-de-feira` no BigQuery tá público? Queria rodar uma query nos dados antes de aprovar.

2021-02-23 08:23 UTC, anapaulagomes commented
As permissões são a padrão da CLI do Base dos Dados. Preciso mudar algo mais? Em `dataViewers` tem o `allUsers`. @rdahis

2021-02-23 14:01 UTC, d116626 commented
> As permissões são a padrão da CLI do Base dos Dados. Preciso mudar algo mais? Em `dataViewers` tem o `allUsers`. @rdahis

Só confirma pra gente se o  bucket do Storage onde estão os dados é publico (`allUsers`), para conseguirmos copiar os dados para o nosso Storage.

2021-02-23 16:08 UTC, anapaulagomes commented
@d116626 não estava. Adicionei `allUsers` com `Storage Object Viewer`.

2021-02-23 18:03 UTC, rdahis commented
Ainda não consigo achar o `dados-abertos-de-feira` quando tento "pin a project". @d116626 onde a @anapaulagomes precisa mudar essa config?

2021-02-23 22:30 UTC, d116626 commented
> Ainda não consigo achar o `dados-abertos-de-feira` quando tento "pin a project". @d116626 onde a @anapaulagomes precisa mudar essa config?
pra mim está aparecendo

2021-02-24 01:34 UTC, rdahis commented
@anapaulagomes vamos aprovar! Só falta dar o `basedosdados table publish` pra termos a tabela pronta com descrições no Bigquery.

2021-02-24 11:16 UTC, anapaulagomes commented
Rodei e recebi um `Table `br_ba_feiradesantana.leis` was published in BigQuery`. E agora? 😅  @rdahis

2021-02-24 16:32 UTC, rdahis commented
@d116626 tá dando aquele problema de o `table publish` dizer que foi publicado mas não aparecer em produção. Isso está apontado no issue #276.

@anapaulagomes vamos esperar resolvermos esse issue que damos o merge desse PR tá?

2021-03-19 16:17 UTC, closed without merging