[dados] br_ibge_censo_demografico
basedosdados/mais pull request #277
Opened 2021-02-14 19:32 UTC by rdahis

Adiciona microdados do Censo Demográfico para 1970-2010.

- [ ] Preencher todos os arquivos de metadados.

2021-03-25 04:44 UTC, mavalentim requested changes
Marquei uma ou outra que pode estar errado, mas eu posso ter me equivocado também! Sempre bom checar, de qualquer jeito :)

2021-03-25 04:44 UTC, mavalentim commented on bases/br_ibge_censo_demografico/microdados_domicilio_1970/table_config.yaml
> +    - domicilio
aqui está só domicilio e abaixo está id_domicilio e id_municipio! Foi proposital?

2021-03-25 04:44 UTC, mavalentim commented on bases/br_ibge_censo_demografico/microdados_domicilio_1970/table_config.yaml
> +        description: Sigla da unidade da federação
Não sei o quão detalhista é para ser mas o padrão nas outras bases é com letra maiúscula: Sigla da Unidade da Federação

2021-03-25 04:44 UTC, mavalentim commented on bases/br_ibge_censo_demografico/microdados_domicilio_1980/table_config.yaml
>  primary_keys:
aqui acho que faltou colocar as primary keys, algo como id_domicilio talvez!

2021-03-25 04:44 UTC, mavalentim commented on bases/br_ibge_censo_demografico/microdados_pessoa_1970/publish.sql
>  SAFE_CAST(v001 AS STRING) v001,
aqui como STRING fiquei em duvida se é isso mesmo já que todas as outras são INT

2021-03-25 05:01 UTC, d116626 reviewed
Testei todas as tabelas no Bigquery e parece tá tudo ok. Deixei alguns comentários sobre algumas colunas.

2021-03-25 05:01 UTC, d116626 commented on bases/br_ibge_censo_demografico/microdados_pessoa_2010/publish.sql
> +SAFE_CAST(situacao_setor AS INT64) situacao_setor,
Coluna inteira NULL

2021-03-25 13:04 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_domicilio_1970/publish.sql
> +SAFE_CAST(v004 AS INT64) v004,
Aqui é ```string``` mesmo? Ficou descrito como código, mas tá tudo ok quando roda a query.

2021-03-25 13:14 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_domicilio_1970/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
prestação.

2021-03-25 13:15 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_domicilio_1970/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
Televisão

2021-03-25 13:30 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_domicilio_1991/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
``float`` não?

2021-03-25 14:31 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_1991/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
Sem trema aqui

2021-03-25 14:31 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_1991/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
frequenta

2021-03-25 14:32 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_1991/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
frequenta

2021-03-25 14:32 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_1991/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
frequenta

2021-03-25 14:42 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/publish.sql
> +from basedosdados-dev.br_ibge_censo_demografico_staging.microdados_pessoa_2000 as t
é quase tudo ``string`` mesmo?  Algumas colunas estão preenchidas em caixa alta.

2021-03-25 14:45 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
frequenta

2021-03-25 14:45 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
frequenta

2021-03-25 14:50 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_domicilio_1980/table_config.yaml
>  primary_keys:
Não tem `id_domicilio` nessa tabela. E não tem colunas identificando linhas unicamente.

2021-03-25 14:52 UTC, rdahis commented on bases/br_ibge_censo_demografico/dataset_config.yaml
> +dataset_id: br_ibge_censo_demografico # AUTO GENERATED
Isso. É porque eu comecei esse PR antes de você subir os dados de setor censitário. Eu vou resolver esse conflito do PR na hora do merge.

2021-03-25 15:01 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +
Acho que não tem vírgula aqui.

2021-03-25 15:03 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +
- Na semana ajudou, sem remuneração, no trabalho exercido por pessoa moradora do domicílio, ou como aprendiz/estagiário.

ou 

- Na semana, ajudou, sem remuneração, no trabalho exercido por pessoa moradora do domicílio, ou como aprendiz/estagiário.

Talvez o mais correto seria:

Ajudou, sem remuneração, no trabalho exercido por pessoa moradora do domicílio, ou como aprendiz/estagiário (na semana de referência).

2021-03-25 15:04 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +
Na semana ajudou, sem remuneração, no trabalho exercido por pessoa moradora do domicílio em atividade.

2021-03-25 15:06 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +
Não tem vírgula. Acho que seria:

- Quantos trabalhos **tinham** na semana de 23 a 29 de julho de 2000

2021-03-25 15:11 UTC, crislanealves commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +        is_partition: True # Bool [True, False], whether the column is a partition.
uso da vírgula: ", em salários mínimos", ", mulheres", ", homens", é proposital ? Acho que é possível substituir por ( )

2021-03-25 15:14 UTC, Hevilyn commented on bases/br_ibge_censo_demografico/microdados_pessoa_2010/table_config.yaml
> +
vazio mesmo?

2021-03-25 15:41 UTC, crislanealves requested changes
Esse bichinho aqui tem algum significado?  

![image](https://user-images.githubusercontent.com/58278652/112500406-1c3f7200-8d67-11eb-8dff-291c8b8470fe.png)

2021-03-25 16:09 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_domicilio_2000/table_config.yaml
> +        name: id_mesorregiao
Vou propor uma política pra essas decisões de quais identificadores manter, tirar, ou acrescentar lá no grupo. Por enquanto está meio arbitrário mesmo. Por enquanto vou manter aqui só para acelerar.

2021-03-25 16:31 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_domicilio_2010/publish.sql
> +SAFE_CAST(situacao_setor AS INT64) situacao_setor,
Estranho mesmo mas voltei nos dados limpos originais do DataZoom e está assim lá também.

2021-03-25 16:40 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_domicilio_1970/publish.sql
> +SAFE_CAST(v003 AS STRING) v003,
Boa. Tinha deixado como STRING meio por precaução. A coisa dos valores mudarem deve ser só o BigQuery mostrando valores em ordem aleatória.

2021-03-25 16:46 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/publish.sql
> +from basedosdados-dev.br_ibge_censo_demografico_staging.microdados_pessoa_2000 as t
Good catch.

2021-03-25 16:50 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_pessoa_2000/table_config.yaml
> +        is_partition: True # Bool [True, False], whether the column is a partition.
No geral estou seguindo as descrições dos dicionários originais do Censo. Mas são bons pontos.

2021-03-25 16:52 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_domicilio_1991/table_config.yaml
> +primary_keys:
Sim porque não tem colunas que identificam unicamente uma linha nessas tabelas.

2021-03-25 16:52 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_pessoa_2010/table_config.yaml
> +
Mesma resposta acima.

2021-03-25 16:58 UTC, rdahis commented
> Esse bichinho aqui tem algum significado?
> 
> ![image](https://user-images.githubusercontent.com/58278652/112500406-1c3f7200-8d67-11eb-8dff-291c8b8470fe.png)

Olha só. Não sei se excluí esse arquivo sem querer nesse commit. Quando der um PR, se excluir eu subo de novo.

2021-03-25 17:04 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_domicilio_2000/table_config.yaml
> +        name: id_regiao_metropolitana
Mesma resposta acima.

2021-03-25 17:05 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_pessoa_2010/publish.sql
> +SAFE_CAST(situacao_setor AS INT64) situacao_setor,
Mesma resposta acima.

2021-03-26 13:19 UTC, crislanealves approved these changes
@rdahis acho que tudo ok. Fiquei com duas dúvidas só:
- Esse PR não veio com a pasta ``code``, isso é porque essa tabela já existia ? 
- A descrição do ``data_update_frequency`` não deveria ser 10 anos?

2021-03-26 17:09 UTC, rdahis commented
> * Esse PR não veio com a pasta `code`, isso é porque essa tabela já existia?

Tava faltando mesmo. Sempre esqueço do subir o código =O

> * A descrição do `data_update_frequency` não deveria ser 10 anos?

Botei `único` porque as tabelas estão separadas por ano, sabe? Então cada tabela em si não atualiza. Mas se fizermos uma tabela compatibilizada, aí sim ela atualizaria no intervalo.

2021-03-26 18:26 UTC, rdahis commented
@mavalentim @d116626 @hevsouza aprovado pra merge?

2021-03-26 21:20 UTC, mavalentim approved these changes

2021-03-26 21:21 UTC, merged

2021-03-26 21:24 UTC, hevsouza approved these changes

2023-02-28 15:33 UTC, gdocesp commented
Os Censos de 1980 e 1991 estão sem as chaves id_domicilio para juntar as bases de domicílios e pessoas...