PR inep.transicao_de_para_anual
basedosdados/mais pull request #288
Opened 2021-02-19 18:31 UTC by Hevilyn

2021-02-19 19:01 UTC, d116626 commented
@Hevilyn tem dois PR idênticos abertos, só que o outro esta na branch `inep.curso_de_para` do seu fork. Faz esse commit [3a19efe](https://github.com/Hevilyn/mais/commit/3a19efe7fce2e774954ec2b84173ade8e4d8be20) na branch `inep.curso_de_para` , que ai eu fecho esse PR.

2021-02-20 00:58 UTC, d116626 commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +version: <vA.B> # REQUIRED
pode colocar v1.0

2021-02-20 00:58 UTC, d116626 commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +    - 2010 - 2019
Se a tabela vai de 2010 a 2019 tem que colocar da seguinte forma:
```
  - 2010
  - 2011
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019
```

2021-02-20 00:59 UTC, d116626 commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        name: id_municipio
Se essa coluna for o ID Município - IBGE 7 Dígitos que tem no `basedosdados.br_bd_diretorios_brasil.municipios`, então pode remover as colunas `id_uf` e `id_regiao`, pois conseguimos mapear essas informações só com o `id_municipio`. Caso não seja, ai tem que mudar no nome da coluna, pq `id_municipio` está padronizado como ID Município - IBGE 7 Dígitos.

2021-02-22 01:32 UTC, fernandascovino requested changes

2021-02-22 01:32 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +table_id: curso_de_para_anual # AUTO GENERATED
@Hevilyn qual o nome dessa tabela no site do inep? http://portal.inep.gov.br/indicadores-educacionais

seria o `fluxo_ensino_superior`? melhor mantermos a nomenclatura não? 

@rdahis adicionar o link externo no CKAN: https://basedosdados.org/dataset/br-inep-indicadores-educacionais

2021-02-22 01:32 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        name: qtde_desistencia
@Hevilyn não usamos `qtde` e sim `quantidade`, está na tabela de padrões BD+: https://docs.google.com/spreadsheets/d/1r4UqWx3d2jaRpoqp3ZkmJ07kerVP6KRO0unfchrOIuY/edit#gid=0
```suggestion
        name: quantidade_desistencia
```

2021-02-22 01:32 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        name: qtde_desistencia
editar nos demais campos

2021-02-22 01:32 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        description: Taxa de Permanência
Anual?

2021-02-22 01:32 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        description: Taxa de Conclusão Acumulada
Acumulada no ano?

2021-02-22 01:32 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        description: Taxa de Desistência Acumulada
Acumulada no ano?

2021-02-22 15:28 UTC, crislanealves commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +
Acho que pode excluir essas linhas a mais.

2021-02-22 15:29 UTC, crislanealves commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +
7 dígitos ? Acho que tem que descrever.

2021-02-22 15:33 UTC, crislanealves commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +
Faltou add seu ``email``. Acho que em ``website`` você colocar seu perfil do github.

2021-02-22 15:44 UTC, crislanealves requested changes
@Hevilyn Uma dúvida: Nenhum dos seus``primary_keys`` estão preenchidos. É isso mesmo? Porque talvez realmente não tenham identificadores.

Outra coisa, acho que tem que colocar os arquivos ``.R`` na pasta ``code``.

2021-02-22 17:05 UTC, fernandascovino requested changes

2021-02-22 17:05 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +    - 2007/2008
@Hevilyn colocar somente um ano e não com /

2021-02-22 17:05 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +        name: ano_de
o que é de? @rdahis @Hevilyn é isso mesmo o nome da coluna?

2021-02-22 17:05 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +        name: ano_de
melhor deixar como `ano_base` e `proximo_ano` não? por que tem a coluna `ano_para` inclusive, não é sempre referente ao próximo?

2021-02-22 17:05 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +primary_keys:
aqui tem que adicionar `id_municipio`, `rede`, `ano_base` e `localizacao`

2021-02-22 17:05 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +        name: situacao
`situacao` e `localizacao` são coisas diferentes nas tabelas do Inep, esse campo refere-se a qual das duas?

2021-02-22 18:23 UTC, Hevilyn commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +    - 2010 - 2019
Então, essa tabela é de fluxo da educação superior, então cada arquivo é referente a um ano 2011/2019, 2012/2019 e etc., por isso coloquei desse jeito. Mudo assim mesmo?

2021-02-22 18:25 UTC, Hevilyn commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +table_id: curso_de_para_anual # AUTO GENERATED
isso, fernanda! vou mudar

2021-02-22 18:26 UTC, Hevilyn commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +    - 2007/2008
A tabela é de transição, cada linha é uma observação das taxas de transição de um ano para o outro, por isso coloquei dessa forma. Como eu poderia indicar isso?

2021-02-22 18:28 UTC, Hevilyn commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +        name: ano_de
isso, é sim! gostei da sugestão do nome, vou mudar.

2021-02-22 20:02 UTC, Hevilyn commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        description: Taxa de Permanência
No documento dizia que apenas as taxas de conclusão e a de desistência eram anuais.

2021-02-22 20:52 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +    - 2010 - 2019
sim, melhor deixar somente os anos referentes ao `ano_base`

2021-02-22 20:53 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/curso_de_para_anual/table_config.yaml
> +        description: Taxa de Permanência
estranho isso... consegue perguntar ao Andre la no discord?

2021-02-22 20:54 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +    - 2007/2008
coloca isso na descricao da coluna, `Taxa de conclusão do ano base para o próximo ano` por exemplo

2021-02-23 07:18 UTC, rdahis commented
@Hevilyn alguns comentários:

- Publicar a tabela `municipio` dentro do `basedosdados-dev`.
- Na tabela `transicao_de_para_anual` eu voltaria com os nomes `ano_de` e `ano_para`. Concordo que não é um nome ótimo, mas prefiro esses do que `ano_base` e `proximo_ano` @fernandascovino. Ainda não pensei em outras alternativas.
- Vamos repetir a tabela `municipio` para todas as outras: `brasil`, `regiao`, `uf`, `escola`. Já pode ir começando.

2021-02-23 07:29 UTC, rdahis requested changes

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/fluxo_educacao_superior/table_config.yaml
> +version: <1.0> # REQUIRED
Botar `v1.0`.

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/fluxo_educacao_superior/table_config.yaml
> +    - regiao
Pode tirar `regiao` e `uf` porque `municipio` já é uma unidade abaixo desses.

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/fluxo_educacao_superior/table_config.yaml
> +    - Brasil
`brasil` com "b" minúsculo.

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
>      - municipio
É município e ano, certo?

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
>      - 2009
Vai até 2019, certo?

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
> +        description: édia de Horas-Aula diária - Ensino Médio Não Seriado
`Média`

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
> +        description: Regularidade do Corpo Docente
A descrição está incompleta pra essas variáveis de regularidade abaixo. Falta diferenciar o que é o que.

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +version: <1.0> # REQUIRED
`v1.0`

2021-02-23 07:29 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/transicao_de_para_anual/table_config.yaml
> +primary_keys:
Faltou o `ano_para` (além do `ano_de`).

2021-02-23 17:39 UTC, Hevilyn commented on bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
>      - municipio
sim, verdade

2021-02-24 19:34 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
>      - 2009
@Hevilyn faltou ajustar aqui até 2019.

2021-02-24 19:35 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/municipio/publish.sql
> +SAFE_CAST(ano AS INT64) ano
Reordena essa variável pra cima. Faz em ordem: `id_municipio`, `localizacao`, `rede`, `ano`, etc.

2021-02-25 13:33 UTC, fernandascovino requested changes
@Hevilyn todos os arquivos `trabasicao_de_para_anual` tem que ser excluidos, não? tem 6 ainda aqui!

![image](https://user-images.githubusercontent.com/20743819/109160662-d6d25980-7754-11eb-8395-ca8f62e2cd2e.png)

2021-02-25 13:33 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/fluxo_educacao_superior/table_config.yaml
> +version: <1.0> # REQUIRED
```suggestion
version: v1.0 # REQUIRED
```

se tiver entre <> não aparece

2021-02-25 13:33 UTC, fernandascovino commented on bases/br_inep_indicadores_educacionais/fluxo_educacao_superior/table_config.yaml
> +    - regiao
@Hevilyn falta jeitar aqui ainda

2021-03-02 19:58 UTC, closed without merging