[dados] br_sp_seduc
basedosdados/mais pull request #293
Opened 2021-02-24 16:56 UTC by mavalentim

Adicionando bases da seduc

2021-02-24 18:19 UTC, rdahis requested changes
Ótimo! Pedi algumas mudanças só.

2021-02-24 18:19 UTC, rdahis commented on bases/br_sp_seduc/dataset_config.yaml
> + O datset abrange todas as tabelas disponibilizadas pela Secretaria de Educação de São Paulo. Nas tabelas, tem-se dados diversas características das escolas, desde
Muda `datset` para `base`.

2021-02-24 18:19 UTC, rdahis commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +SAFE_CAST(id_inep AS INT64) id_inep,
Muda para `id_escola`.

2021-02-24 18:19 UTC, rdahis commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +SAFE_CAST(nom_escola AS STRING) nom_escola,
Muda para `nome_escola`.

2021-02-24 18:19 UTC, rdahis commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +SAFE_CAST(municipio AS STRING) municipio,
Vamos adicionar a coluna `id_municipio` aqui. Para isso, ou (1) damos um merge com o diretório de escolas que já tenha a variável, ou (2) faz um string matching com o diretório de municípios pela variável `municipio`.

2021-02-24 18:19 UTC, rdahis commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +SAFE_CAST(ano AS INT64) ano,
Muda a ordem. Coloca: `ano`, `id_municipio`, `municipio`, `diretoria`, `id_escola`, `id_escola_sp`, `nome_escola`, `nivel_ensino`, `nota_idesp`.

2021-02-24 18:20 UTC, rdahis commented
@mavalentim já abre um PR também para a tabela `br_bd_diretorios_brasil.escola`. Como conversamos, nela você já adiciona `id_escola`, `id_escola_sp`, `nome_escola`, `id_municipio`, etc.

2021-02-24 19:19 UTC, mavalentim commented on bases/br_sp_seduc/dataset_config.yaml
> + O datset abrange todas as tabelas disponibilizadas pela Secretaria de Educação de São Paulo. Nas tabelas, tem-se dados diversas características das escolas, desde
Aqui ficaria "As bases abrangem..." porque não sei se fica claro, talvez "o conjunto de bases"?

2021-02-24 19:20 UTC, mavalentim commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +SAFE_CAST(municipio AS STRING) municipio,
fiquei em dúvida aqui se faço isso já na base do R ou no publish somente

2021-02-24 19:24 UTC, rdahis commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +SAFE_CAST(municipio AS STRING) municipio,
Vamos fazer o seguinte. Vou criar o diretório de escolas e depois você faz um join já direto pelo `publish.sql`.

2021-02-24 19:25 UTC, rdahis commented on bases/br_sp_seduc/dataset_config.yaml
> + O datset abrange todas as tabelas disponibilizadas pela Secretaria de Educação de São Paulo. Nas tabelas, tem-se dados diversas características das escolas, desde
Acho "A base abrange ..." tranquilo. Uma base tem várias tabelas.

2021-02-25 20:05 UTC, Hellcassius commented
@mavalentim estavamos fazendo uns testes, tem que ver essa coluna `nota_idesp` o separador do decimal deveria ser ponto e aqui aparece vírgula
![image](https://user-images.githubusercontent.com/77297729/109210334-70b4f900-778b-11eb-8945-6ea11edb5440.png)

2021-02-26 03:37 UTC, crislanealves commented on bases/br_sp_seduc/dataset_config.yaml
> +
Aqui acho que é 'socioeconômico'.

2021-02-26 03:42 UTC, crislanealves commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +from basedosdados-dev.br_sp_seduc_staging.idesp_escolas as t
Mais uma dúvida aqui, ``nota`` é FLOAT mesmo?

2021-02-26 03:48 UTC, crislanealves reviewed
@mavalentim um detalhe bem trivial. Faltou preencher o ``treated_by`` em alguns campos.

2021-03-01 16:59 UTC, mavalentim commented on bases/br_sp_seduc/dataset_config.yaml
> +
boa miga! vou mudar

2021-03-01 17:00 UTC, mavalentim commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +from basedosdados-dev.br_sp_seduc_staging.idesp_escolas as t
É pq tem que ter duas casas! O INT64 não pode ter decimal pelo que eu entendo

2021-03-01 18:21 UTC, rdahis commented on bases/br_sp_seduc/idesp_escolas/publish.sql
> +from basedosdados-dev.br_sp_seduc_staging.idesp_escolas as t
Isso aí.

2021-03-02 21:42 UTC, rdahis approved these changes

2021-03-02 21:43 UTC, merged