[dados] br_sp_alesp | atualização e adição de novos dados
basedosdados/mais pull request #320
Opened 2021-03-12 15:07 UTC by d116626

Ainda vou adicionar tabelas de tramitação

2021-03-12 21:49 UTC, rdahis requested changes
Bem legal. Comentários gerais.

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/assessores_lideranca/publish.sql
> +SAFE_CAST(partido AS STRING) partido
Tenho chamado essa variável de `sigla_partido`.

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/assessores_parlamentares/publish.sql
>  SAFE_CAST(partido AS STRING) partido,
`sigla_partido`

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/code/data/gastos/despesas_gabinete/delete_this_file.txt
> +delete_this_file
É pra ter esses arquivos `delete_this_file.txt` aqui?

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/deputados/publish.sql
>  SAFE_CAST(aniversario AS STRING) aniversario,
Botar no formato `MM-DD`?

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/deputados/publish.sql
> +SAFE_CAST(matricula AS INT64) matricula,
Conseguimos mapear as variáveis `matricula`, `id_deputado`, e `id_spl` com a `id_candidato_bd` no diretório de candidatos?

Temos que pensar naquela infra do `id_candidato_bd` mudar a cada atualização dos dados de eleições.

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/deputados/publish.sql
>  SAFE_CAST(partido AS STRING) partido,
`sigla_partido`

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/deputados/publish.sql
> +SAFE_CAST(deputado AS STRING) deputado,
Mudar para `nome_deputado`.

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/deputados/publish.sql
> +SAFE_CAST(numero_deputados AS INT64) numero_deputados,
Que variável é essa? Varia no nível do deputado?

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete/publish.sql
>  SAFE_CAST(deputado AS STRING) deputado,
`nome_deputado`

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete/publish.sql
>  SAFE_CAST(cnpj AS STRING) cnpj,
Por que as linhas tem diferentes tamanhos? CNPJs podem não ter 14 dígitos? Ou isso mistura CNPJ com outras coisas?

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
> +source_bucket_name: basedosdados-dev
A tabela `despesas_gabinete` passa a incluir os dados dessa `atual` conforme passa o tempo? Não é melhor já criar uma tabela única incluindo os dados históricos e atuais?

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
> +    - Deputado
Botar como minúscula aqui.

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
> +    - 2020
2021 também?

2021-03-12 21:49 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete/table_config.yaml
> +        description: Valor da despesa
Botar sempre `(R$)` na descrição se for tudo em reais. Se for em outras moedas pode acrescentar uma coluna `moeda`.

2021-03-12 22:20 UTC, d116626 commented on bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
> +    - 2020
ainda n tem 2021

2021-03-12 22:21 UTC, d116626 commented on bases/br_sp_alesp/deputados/publish.sql
> +SAFE_CAST(matricula AS INT64) matricula,
são campos específicos da ALESP

2021-03-12 22:22 UTC, d116626 commented on bases/br_sp_alesp/code/data/gastos/despesas_gabinete/delete_this_file.txt
> +delete_this_file
é so pra criar uma estrutura de pastas usada pelos scritps

2021-03-13 00:06 UTC, rdahis commented on bases/br_sp_alesp/deputados/publish.sql
> +SAFE_CAST(matricula AS INT64) matricula,
Esse mapeamento teria que ser na mão mesmo então né.

2021-03-13 13:03 UTC, d116626 commented on bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
> +source_bucket_name: basedosdados-dev
A despesas_gabinete contem a atual, só criei uma tabela separada pq uso ela em um projeto e pode vir a ser útil pra quem só estiver interessado nesse mandato

2021-03-13 19:12 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete_atual/table_config.yaml
> +source_bucket_name: basedosdados-dev
Entendi. Fair enough!

2021-03-15 13:56 UTC, d116626 commented on bases/br_sp_alesp/deputados/publish.sql
> +SAFE_CAST(numero_deputados AS INT64) numero_deputados,
era uma variável interna minha, já removi

2021-03-15 13:57 UTC, d116626 commented on bases/br_sp_alesp/despesas_gabinete/publish.sql
>  SAFE_CAST(cnpj AS STRING) cnpj,
pode ser o CNPJ ou o CPF de um beneficiário

2021-03-15 15:07 UTC, d116626 commented
Resolvido @rdahis

2021-03-15 15:43 UTC, rdahis commented on bases/br_sp_alesp/despesas_gabinete/publish.sql
>  SAFE_CAST(cnpj AS STRING) cnpj,
Saquei. Eu chamaria de `cpf_cnpj` então?

2021-03-16 02:31 UTC, rdahis approved these changes

2021-03-16 02:35 UTC, merged