[infra] Fix issues #68 and #151
basedosdados/mais pull request #333
Opened 2021-03-15 18:42 UTC by Hellcassius

Resolve os issues:
- #68 Adiciona index=False na função download, já testado contra os testes refeitos.
- #151 Muda o argumento partitions to is_partition em Storage.upload() e remove #TODO's das docstrings de copy_table e delete_table, dado as versões que estão na master atualmente.

2021-03-15 22:28 UTC, d116626 commented
Não teria os que mudar o `partitions` to `is_partition` aqui tbm? 

https://github.com/basedosdados/mais/blob/512e34e2924e4a7227f88782846016f43da4b110/basedosdados/cli.py#L229-L250

2021-03-16 19:08 UTC, JoaoCarabetta approved these changes
Errei o review

2021-03-16 19:09 UTC, JoaoCarabetta requested changes

2021-03-16 19:09 UTC, JoaoCarabetta commented on basedosdados/storage.py
> +        is_partition=None,
Tem que desmudar isso

2021-03-16 22:59 UTC, Hellcassius commented on basedosdados/storage.py
> +        is_partition=None,
Resolvido no commit 4c1453d

2021-03-19 14:07 UTC, JoaoCarabetta commented on basedosdados/storage.py
> +        partition=None,
acho que é melhor manter o `partitions` mesmo, ao inves de `partition`. Senão vai quebrar coisas em lugares misteriosos.

2021-03-19 19:48 UTC, Hellcassius commented on basedosdados/storage.py
> +        partition=None,
Resolvido no commit 5a3775a

2021-03-22 20:42 UTC, JoaoCarabetta approved these changes
LGTM!

2021-03-22 20:42 UTC, merged