[dados] br_ibge_pam
basedosdados/mais pull request #335
Opened 2021-03-16 05:00 UTC by mavalentim

Adicionando a nova PAM, particionada por ano e UF, ainda vou mudar o código da primeira base pois está muito grande e repetitivo!

2021-03-16 05:15 UTC, rdahis commented
Boa. Tá faltando as outras tabelas né?

E vamos renomear essa para `municipio_lavouras_temporarias`?

2021-03-17 14:28 UTC, crislanealves commented on bases/br_ibge_pam/dataset_config.yaml
> +
Migo, besteira aqui, mas acho que pode tirar esse "-". Fica aparecendo como ``None`` no dev.

2021-03-17 14:37 UTC, crislanealves commented on bases/br_ibge_pam/municipios_lavouras_temporarias/table_config.yaml
> +
é 1.4 mesmo?

2021-03-17 14:38 UTC, crislanealves commented on bases/br_ibge_pam/municipios_lavouras_temporarias/table_config.yaml
> +
Faltou preencher aqui.

2021-03-17 14:47 UTC, crislanealves commented on bases/br_ibge_pam/municipios_lavouras_temporarias/table_config.yaml
> +
- Os dados foram aglomerados.
Sugestão:
-  Por fim, a tabela foi exportada de forma particiona para facilitar e diminuir os custos de uma eventual consulta.

2021-03-17 14:52 UTC, crislanealves commented on bases/br_ibge_pam/municipios_lavouras_temporarias/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
Acho que Km2 aqui, mas é melhor o @rdahis confirmar.

2021-03-17 14:56 UTC, crislanealves commented on bases/br_ibge_pam/municipios_lavouras_temporarias/table_config.yaml
> +        description: Sigla do Estado
Sigla da Unidade da Federação.

2021-03-18 18:05 UTC, rdahis requested changes

2021-03-23 15:09 UTC, Hevilyn approved these changes

2021-03-23 21:06 UTC, mavalentim commented on bases/br_ibge_pam/municipio_lavouras_temporarias/publish.sql
> +SAFE_CAST(moeda_valor_prod AS STRING) moeda_valor_prod,
mudei!

2021-03-23 21:28 UTC, rdahis approved these changes

2021-03-23 21:29 UTC, merged