[dados] br_sp_seduc_idesp
basedosdados/mais pull request #341
Opened 2021-03-17 08:32 UTC by mavalentim

Adicionando as bases da SEDUC relacionadas ao IDESP!!

2021-03-17 15:31 UTC, crislanealves commented on bases/br_sp_seduc_idesp/dataset_config.yaml
> +
Índice.

2021-03-17 15:38 UTC, crislanealves commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +
Esse espaço do ``from`` é proposital ?

2021-03-17 15:38 UTC, crislanealves commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +from basedosdados-dev.br_sp_seduc_idesp_staging.escola as t
Esse espaço do ``from`` é proposital ?

2021-03-17 15:41 UTC, crislanealves commented on bases/br_sp_seduc_idesp/escola/table_config.yaml
> +
Estado

2021-03-18 18:14 UTC, rdahis requested changes

2021-03-18 18:14 UTC, rdahis commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +SAFE_CAST(codigo_diretoria AS INT64) codigo_diretoria,
* Mudar nome para `id_diretoria`?
* Nos dados está tudo nulo. Algum problema com o tipo da variável?

2021-03-18 18:14 UTC, rdahis commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +/*
Só vai até 2017 mesmo?

2021-03-18 18:14 UTC, rdahis commented on bases/br_sp_seduc_idesp/diretoria/table_config.yaml
> +    - 2018
Nos dados parece que vai só até 2017. Tá certo isso?

2021-03-18 18:14 UTC, rdahis commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +SAFE_CAST(municipio AS STRING) municipio,
Remover a variável `municipio`.

2021-03-18 18:14 UTC, rdahis commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +SAFE_CAST(nota_idesp AS FLOAT64) nota_idesp,
Parece ter uma vírgula a mais aqui que daria errado a query. É isso mesmo?

2021-03-18 18:14 UTC, rdahis commented on bases/br_sp_seduc_idesp/estado/publish.sql
> +/*
Eu mudaria o nome da tabela para `uf` para ficar consistente com o resto do repositório.

2021-03-23 01:29 UTC, mavalentim commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +/*
ricardo, demorei mas cheguei, aqui ta normal 
[Captura de tela de 2021-03-22 22-29-07](https://user-images.githubusercontent.com/75315649/112078951-1165c100-8b5e-11eb-8c38-d8090d0e7e98.png)

2021-03-23 14:59 UTC, Hevilyn requested changes

2021-03-23 14:59 UTC, Hevilyn commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +SAFE_CAST(nome_escola AS STRING) nome_escola,
Vi que no outro dataset o Dahis pediu pra remover nome_escola, talvez aqui seja melhor remover também.

2021-03-23 18:31 UTC, rdahis commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +SAFE_CAST(nome_escola AS STRING) nome_escola,
Boa

2021-03-23 20:26 UTC, mavalentim commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +SAFE_CAST(nome_escola AS STRING) nome_escola,
tirei de todos gal! esse minimalismo eu apoio

2021-03-23 21:21 UTC, rdahis requested changes

2021-03-23 21:21 UTC, rdahis commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +SELECT
Faltou passar todos os tipos aqui para INT64 ou FLOAT64.

2021-03-23 21:21 UTC, rdahis commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +SAFE_CAST(id_diretoria AS INT64) id_diretoria,
Cheio de nulo aqui. É isso mesmo?

2021-03-24 00:12 UTC, mavalentim commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +SAFE_CAST(id_diretoria AS INT64) id_diretoria,
sim! infelizmente id_diretoria ta meio faltosa mesmo na base original

2021-03-24 04:29 UTC, mavalentim commented on bases/br_sp_seduc_idesp/escola/publish.sql
> +SELECT
vou subir mais uma corrigindo

2021-03-24 18:18 UTC, mavalentim commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +SAFE_CAST(id_diretoria AS INT64) id_diretoria,
Dei um jeito de colocar ricardo! Depois podemos conversar sobre incluir id_diretoria no diretorio de escolas ou algo do tipo que permita maior interconectividade entre as bases

2021-03-24 18:26 UTC, rdahis commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +SAFE_CAST(id_diretoria AS INT64) id_diretoria,
Adiciona como tarefa no Trello per favore.

2021-03-24 18:29 UTC, rdahis approved these changes

2021-03-24 18:29 UTC, mavalentim commented on bases/br_sp_seduc_idesp/diretoria/publish.sql
> +SAFE_CAST(id_diretoria AS INT64) id_diretoria,
si segnore

2021-03-24 18:34 UTC, rdahis commented
Fechando dado que os comentários da @Hevilyn foram endereçados.

2021-03-24 18:59 UTC, merged