[dados] br_sp_seduc_inse
basedosdados/mais pull request #342
Opened 2021-03-17 08:42 UTC by mavalentim

Adicionando dados das bases da SEDUC relacionadas ao INSE!

2021-03-17 15:51 UTC, crislanealves commented on bases/br_sp_seduc_inse/dataset_config.yaml
> +
Socioeconômico.

Excluir "varia de 0 a 10, sendo 10 a escola com o nível socioeconômico mais baixo e 0 a escola com nível mais alto" do início ou do final da descrição.

2021-03-17 15:53 UTC, crislanealves commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +
socioeconômico

2021-03-17 15:54 UTC, crislanealves commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +
outras

2021-03-17 15:56 UTC, crislanealves commented on bases/br_sp_seduc_inse/escola/publish.sql
> +from basedosdados-dev.br_sp_seduc_inse_staging.escola as t
Faltou editar.

2021-03-18 18:21 UTC, rdahis requested changes

2021-03-18 18:21 UTC, rdahis commented on bases/br_sp_seduc_inse/escola/publish.sql
> +SAFE_CAST(municipio AS STRING) municipio,
Excluir as variáveis `municipio` e `nome_escola`. Se quiser dá um join com os diretórios pra puxar de lá as strings com nomes.

2021-03-18 18:21 UTC, rdahis commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +    - id_escola_sp
Vamos botar `id_escola` pra ficar mais generalizado com outras tabelas.

2021-03-18 18:21 UTC, rdahis commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +    - 2018
Só 2018 mesmo?

2021-03-18 18:21 UTC, rdahis commented on bases/br_sp_seduc_inse/escola/publish.sql
> +SAFE_CAST(nivel_socio_economico AS STRING) nivel_socio_economico,
Parece ter uma vírgula a mais aqui. Não dá problema não?

2021-03-19 18:14 UTC, mavalentim commented on bases/br_sp_seduc_inse/escola/publish.sql
> +SAFE_CAST(nivel_socio_economico AS STRING) nivel_socio_economico,
nao deu! mas vou tirar rs

2021-03-19 18:14 UTC, mavalentim commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +    - 2018
sim! ela tem dados só de 2018

2021-03-19 18:41 UTC, mavalentim commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +
EU NÃO SEI ESCREVER ISSO NUNCA AA

2021-03-19 18:43 UTC, mavalentim commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
nao é possivel cara

2021-03-19 18:57 UTC, rdahis requested changes

2021-03-19 18:57 UTC, rdahis commented on bases/br_sp_seduc_inse/escola/publish.sql
>  SAFE_CAST(id_escola_sp AS STRING) id_escola_sp,
Mudar para `INT64`, né?

2021-03-19 18:57 UTC, rdahis commented on bases/br_sp_seduc_inse/escola/publish.sql
> +SAFE_CAST(nivel_socio_economico AS STRING) nivel_socio_economico
Aqui é `FLOAT64`?

2021-03-19 20:36 UTC, crislanealves commented on bases/br_sp_seduc_inse/escola/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
Não fica assim. Eu acredito em você, amigo. #tmj

2021-03-23 14:50 UTC, Hevilyn requested changes

2021-03-23 14:50 UTC, Hevilyn commented on bases/br_sp_seduc_inse/dataset_config.yaml
> +    A base contém a tabela sobre o Indicador Socioeconomico das Escolas do Estado de São Paulo, o INSE. O indicador varia de 0 a 10, sendo 10 a escola com o nível socioeconômico mais baixo e 0 a esco
Indicador Socioeconômico aqui

2021-03-23 18:12 UTC, mavalentim commented on bases/br_sp_seduc_inse/dataset_config.yaml
> +    A base contém a tabela sobre o Indicador Socioeconomico das Escolas do Estado de São Paulo, o INSE. O indicador varia de 0 a 10, sendo 10 a escola com o nível socioeconômico mais baixo e 0 a esco
corrigido abaixo seus paladino da acentuação

2021-03-23 18:12 UTC, mavalentim commented on bases/br_sp_seduc_inse/escola/publish.sql
>  SAFE_CAST(id_escola_sp AS STRING) id_escola_sp,
certissimo

2021-03-23 18:13 UTC, mavalentim commented on bases/br_sp_seduc_inse/escola/publish.sql
> +SAFE_CAST(nivel_socio_economico AS STRING) nivel_socio_economico
corrigido!

2021-03-23 18:20 UTC, rdahis approved these changes

2021-03-23 18:21 UTC, rdahis commented
Aprovando dado que os comentários da @Hevilyn foram endereçados também.

2021-03-23 18:22 UTC, merged