Inep indicadores - novas tabelas e tabela de município atualizada para 2020
basedosdados/mais pull request #343
Opened 2021-03-17 19:16 UTC by Hevilyn

2021-03-18 19:13 UTC, rdahis requested changes

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/brasil/table_config.yaml
> +    - ano
Faltou `rede` e `localizacao` também nee.

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/brasil_remuneracao_docentes/table_config.yaml
> +    - pais
Aqui é `ano`, `rede`, e `escolaridade` né.

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/municipio/table_config.yaml
> +    - 2020
Em `observation_level`, faltou `rede` e `localizacao` também.

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/regiao/table_config.yaml
> +    - ano
Faltou `localizacao` e `rede`.

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf/table_config.yaml
> +    - ano
Faltou `localizacao` e `rede`.

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf_remuneracao_docentes/table_config.yaml
> +        name: uf
`sigla_uf`?

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf_remuneracao_docentes/table_config.yaml
> +        description: Estado da Federação
`Sigla da Unidade da Federação`

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf_remuneracao_docentes/table_config.yaml
> +    - estado
`unidade da federação`

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf_remuneracao_docentes/table_config.yaml
> +    - regiao
Pode tirar `regiao` dado que `sigla_uf` está abaixo disso.

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf_remuneracao_docentes/table_config.yaml
> +
Faltou `rede` e `escolaridade`.

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf_remuneracao_docentes/publish.sql
> +SELECT
Essa query está diferente do que está publicado no bigquery. Exemplo: tá faltando a variável `sigla_uf` aqui mas tem lá.

Faltou atualizar o arquivo aqui no PR?

2021-03-18 19:13 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/uf_remuneracao_docentes/table_config.yaml
> +    Padronização dos nomes das colunas.
Colocar o "- " para ficar um bullet list.

2021-03-19 00:17 UTC, crislanealves requested changes

2021-03-19 17:41 UTC, mavalentim approved these changes

2021-03-22 02:25 UTC, rdahis commented
Show. Falta só:

- [ ] Dar um `table update --mode=prod` pra todas as alterações aparecerem no BigQuery.
- [ ] Subir a tabela `escola` (e alguma mais a nível de escola?).

2021-03-22 20:07 UTC, rdahis requested changes

2021-03-22 20:07 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/escola_nivel_socioeconomico/publish.sql
> +SAFE_CAST(inse_valor_absoluto AS FLOAT64) inse_valor_absoluto,
- [ ] Algum motivo para os valores de 2014 terem muitas casas decimais e os valores de 2015 terem só 2?
- [ ] Podemos renomear essa variável para `inse`, ou `valor_inse`?

2021-03-22 20:07 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/escola_nivel_socioeconomico/publish.sql
> +SAFE_CAST(quantidade_alunos_inse AS INT64) quantidade_alunos_inse,
Renomear para `inse_quantidade_alunos`?

2021-03-22 20:07 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/escola/table_config.yaml
> +    - localizacao
Aqui pode tirar `localizacao` e `rede`. Cada escola só está em uma localização e uma rede, né?

2021-03-22 20:07 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/escola/table_config.yaml
> +    - rede
Tirar `rede` e `localizacao` também.

2021-03-22 20:07 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/escola_nivel_socioeconomico/table_config.yaml
> +observation_level: #REQUIRED
Aqui é só `escola` e `ano` eu acho.

2021-03-22 20:07 UTC, rdahis commented on bases/br_inep_indicadores_educacionais/escola_nivel_socioeconomico/table_config.yaml
> +primary_keys:
Só `id_escola` e `ano`.

2021-03-22 20:30 UTC, Hevilyn commented on bases/br_inep_indicadores_educacionais/escola_nivel_socioeconomico/publish.sql
> +SAFE_CAST(inse_valor_absoluto AS FLOAT64) inse_valor_absoluto,
No arquivo de 2015 os valores estão arredondados para 2 casas decimais, já no de 2014 eles colocaram todas as casas decimais mesmo.
Acho que` valor_inse` é bom

2021-03-23 16:43 UTC, rdahis approved these changes

2021-03-23 19:44 UTC, merged