[dados] br_ipea_acesso_oportunidades
basedosdados/mais pull request #355
Opened 2021-03-23 23:25 UTC by JoaoCarabetta

Estou preparado para o escrutínio

2021-03-23 23:54 UTC, rdahis requested changes

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(quantidade_pessoas AS FLOAT64) quantidade_pessoas,
Essa variável na tabela parece ser a `modo_transporte`.

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(quantidade_pessoas_brancas AS FLOAT64) quantidade_pessoas_brancas,
Todas essas variáveis de `quantidade` vamos botar tipo `INT64`.

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(nome_municipio AS STRING) nome_municipio,
Nossa prática tem sido tirar variáveis de nome e deixar só o `id_municipio`.

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/table_config.yaml
> +    - municipio
Aqui é só `hexagono` eu acho. Cada hexágono é único e pertence a um município só né?

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/table_config.yaml
> +    - municipio
Ou a tabela está a nível de hexágono-modo_transporte-horario_pico? Caso sim, então alinha aqui também.

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(se_horario_de_pico AS FLOAT64) se_horario_de_pico,
Eu renomearia para `horario_pico`.

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/table_config.yaml
> +        description:  Código 7 dígitos IBGE do município
`ID Município - IBGE 7 Dígitos`

2021-03-23 23:54 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/dataset_config.yaml
> +    - https://www.ipea.gov.br/acessooportunidades/en/dados/
Botar a url da versão em português.

2021-03-23 23:56 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(id_grid_h3 AS STRING) id_grid_h3,
Podemos renomear para `id_hexagono`?

2021-03-24 17:15 UTC, JoaoCarabetta commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(id_grid_h3 AS STRING) id_grid_h3,
deixei assim pq tem vários sistemas de grid: h3, bing, s2, quadtree etc.

pensei que id_grid_<nome_sistema> pudesse ser um standard

2021-03-24 18:38 UTC, JoaoCarabetta commented
@rdahis Separei em 2 tabelas, `estatísticas` com as stats de população, saude etc. E `indicadores` com os indicadores de acessibilidade

2021-03-24 18:57 UTC, rdahis requested changes

2021-03-24 18:57 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/estatisticas_2019/publish.sql
> +SAFE_CAST(quintil_de_renda AS FLOAT64) quintil_de_renda,
É `INT64`.

2021-03-24 18:57 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/estatisticas_2019/publish.sql
> +SAFE_CAST(decil_de_renda AS FLOAT64) decil_de_renda,
É `INT64`.

2021-03-24 18:57 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/indicadores_2019/publish.sql
> +SAFE_CAST(CMATT15 AS FLOAT64) CMATT15,
Essas variáveis daqui pra baixo são "número" mesmo? Não vi nenhum valor acima de 1.0. Parece que são uma proporção? Caso sim, multiplica tudo por 100 para ficar entre 0-100.

2021-03-24 18:58 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(id_grid_h3 AS STRING) id_grid_h3,
Interessante! É, temos que pensar pra entender essa arquitetura. `grid` é a palavra usada para quando são polígonos/pontos assim?

2021-03-24 19:02 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/indicadores_2019/publish.sql
> +SAFE_CAST(CMATT15 AS FLOAT64) CMATT15,
Tem sido o nosso padrão. Faz aí vai =)

2021-03-24 19:05 UTC, JoaoCarabetta commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(id_grid_h3 AS STRING) id_grid_h3,
O nome oficial é `geospatial indexing systems` mas todo mundo chama de `grid`.

São sempre polígonos que dividem o mundo de alguma maneira estruturada.

Veja o BabelGrid que eu criei para lidar com diferentes grids, https://github.com/EL-BID/BabelGrid. Na documentação tem um exemplo de uso de cada grid

2021-03-24 19:12 UTC, JoaoCarabetta commented on bases/br_ipea_acesso_oportunidades/indicadores_2019/publish.sql
> +SAFE_CAST(CMATT15 AS FLOAT64) CMATT15,
reclamei mas fiz

2021-03-24 19:15 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/hexagonos_2019/publish.sql
> +SAFE_CAST(id_grid_h3 AS STRING) id_grid_h3,
Que coisa bonita. Vou estudar.

2021-03-24 19:16 UTC, rdahis commented on bases/br_ipea_acesso_oportunidades/indicadores_2019/publish.sql
> +SAFE_CAST(CMATT15 AS FLOAT64) CMATT15,
Boa =) Sobe o commit e vambora.

2021-03-24 19:22 UTC, rdahis approved these changes

2021-03-24 19:22 UTC, rdahis commented
Faça as honras @JoaoCarabetta.

2021-03-24 19:49 UTC, JoaoCarabetta commented
uhul!

2021-03-24 19:49 UTC, merged