[dados] br_me_caged
basedosdados/mais pull request #380
Opened 2021-04-01 22:17 UTC by d116626

Adiciona microdados e arquivos de ajuste do CAGED. Ainda estou dando append de outros anos, quanto os dados estiverem completos aviso aqui.

2021-04-03 18:05 UTC, rdahis requested changes

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo/publish.sql
> +SAFE_CAST(cnae_20 AS STRING) cnae_20,
`cnae_2`

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo/publish.sql
> +SAFE_CAST(cnae_20_subclasse AS STRING) cnae_20_subclasse,
`cnae_2_subclasse`

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo/publish.sql
> +SAFE_CAST(raca AS INT64) raca,
`raca_cor` :-)

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cbo_94 AS STRING) cbo_94,
`cbo_1994`

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cnae_10 AS STRING) cnae_10,
`cnae_1`

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cnae_20_subclasse AS STRING) cnae_20_subclasse,
`cnae_2_subclasse`

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(raca AS INT64) raca,
`raca_cor` :-) [2]

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo/table_config.yaml
> +    Microdados públicos do CAGED de 2007 a 2019.
Pode tirar esses anos aqui dado que tá na cobertura temporal abaixo.

2021-04-03 18:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo/table_config.yaml
> +    - <primeira coluna>
Aqui é `movimentação` né?

2021-04-04 16:15 UTC, rdahis requested changes
Coisa de ordem de variáveis que só percebi agora XD

2021-04-04 16:15 UTC, rdahis commented on bases/br_me_caged/microdados_antigo/publish.sql
> +SAFE_CAST(cbo_2002 AS STRING) cbo_2002,
Só me toquei disso agora. Pode inverter a ordem aqui para ficar `cbo_2002`, `cnae_1`, `cnae_2`, `cnae_2_subclasse`?

2021-04-04 16:15 UTC, rdahis commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cbo_1994 AS STRING) cbo_1994,
Pode inverter a ordem aqui para ficar `cbo_1994`, `cbo_2002`, `cnae_1`, `cnae_2_subclasse`? E não tem `cnae_2` nessa tabela?

2021-04-04 21:22 UTC, d116626 commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cbo_1994 AS STRING) cbo_1994,
nop, não veio, mas acho que o subclasse deve mapear o classe.

2021-04-04 23:37 UTC, rdahis commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cbo_1994 AS STRING) cbo_1994,
Pode criar pelo próprio `publish.sql` com um substring? Aí fica bonito igual ao `microdados_antigo`. Última coisa, prometo =)

2021-04-05 00:07 UTC, d116626 commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cbo_1994 AS STRING) cbo_1994,
Parece que n rola fazer pelo BQ, tem varios null entre elas.

2021-04-05 01:05 UTC, rdahis commented on bases/br_me_caged/microdados_antigo_ajutes/publish.sql
> +SAFE_CAST(cbo_1994 AS STRING) cbo_1994,
A regra parece ser os cinco primeiros dígitos, incluindo o zero à esquerda, né?

2021-04-05 01:05 UTC, rdahis commented
Já damos um merge ou ainda vai subir o CAGED novo nesse PR?

2021-04-05 01:08 UTC, d116626 commented
> Já damos um merge ou ainda vai subir o CAGED novo nesse PR?

Vou deixar o CAGED NOVO pra outro PR. Acho que da até pra divulgar essa e solta o novo daqui umas semanas.

2021-04-05 13:49 UTC, crislanealves approved these changes

2021-04-05 15:05 UTC, rdahis commented
> > Já damos um merge ou ainda vai subir o CAGED novo nesse PR?
> 
> Vou deixar o CAGED NOVO pra outro PR. Acho que da até pra divulgar esse e solta o novo daqui umas semanas.

Eu preferiria deixar esse PR aberto até termos o novo também, mas de boas.

2021-04-05 15:05 UTC, rdahis approved these changes

2021-04-05 16:11 UTC, rdahis commented
Tá faltando um `s` no nome da tabela `microdados_antigo_ajutes`.

2021-04-06 15:32 UTC, rdahis commented
O `s` faltando era no nome da tabela na palavra `ajutes`. Vê lá.

2021-04-06 23:18 UTC, merged

2021-04-06 23:23 UTC, rdahis commented
Deu pau no `table approve` da tabela de ajustes @d116626!