[dados] br_inep_saeb.escola
basedosdados/mais pull request #392
Opened 2021-04-08 15:20 UTC by hevsouza

Arquivos .yaml e publish para revisão.
No dev só possui as primeiras 4000 linhas.
O código vou colocar depois.
As últimas descrições das colunas do questionário vou colocar depois também.

2021-04-08 17:12 UTC, crislanealves commented on bases/br_inep_saeb/microdados_escola_2019_2013/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
ID.

2021-04-08 17:19 UTC, crislanealves requested changes
@hevsouza quantas colunas, menina kkkkk. 
Só marquei uma besteirinha.

2021-04-08 20:42 UTC, hevsouza commented
> @hevsouza quantas colunas, menina kkkkk.
> Só marquei uma besteirinha.

kkkkkkkk mais uma base com mais de 200 colunas

2021-04-12 13:39 UTC, mavalentim requested changes

2021-04-12 13:39 UTC, mavalentim commented on bases/br_inep_saeb/dataset_config.yaml
> +API: <sim/não>
faltou aqui amiga

2021-04-12 13:39 UTC, mavalentim commented on bases/br_inep_saeb/microdados_escola_2019_2013/table_config.yaml
> +        description: <descrição da coluna>
só essas colunas aqui que faltaram a descrição amore, que tabela enorme jesus, mandou bem demais

2021-04-13 15:40 UTC, rdahis requested changes

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/publish.sql
> +SAFE_CAST(formacao_docente_ensino_fund_inicial AS STRING) formacao_docente_ensino_fund_inicial,
Melhor trocar `inicial` para `anos_iniciais` para ficar consistente com outras tabelas né.

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/publish.sql
> +SAFE_CAST(formacao_docente_ensino_fund_final AS STRING) formacao_docente_ensino_fund_final,
`anos_finais`

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/publish.sql
> +SAFE_CAST(tx_resp_q007 AS STRING) tx_resp_q007,
Mudar `tx_resp` para `taxa_resposta` em todas.

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/publish.sql
> +SAFE_CAST(media_5_ensino_fund_lp AS STRING) media_5_ensino_fund_lp,
Vamos fazer o padrão ser `ef` e `em` em tudo, ao invés de `ensino_fund` e `ensino_medio`.

(Vou adicionar uma tarefa para padronizarmos os nomes em outras tabelas do Inep)

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/publish.sql
> +SAFE_CAST(nivel_10_mt_emt AS STRING) nivel_10_mt_emt,
Em parte das variáveis você pôs `mt_emt` e em outra pôs `emt_mt`. Escolhe uma ordem só e padroniza todas.

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/publish.sql
> +SAFE_CAST(nivel_10_mt_emt AS STRING) nivel_10_mt_emt,
O mesmo vale para `lp`, etc.

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/table_config.yaml
> +    Resultados do SAEB e indicadores por Escola.
escola

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/table_config.yaml
> +    Compatibilização dos dados entre os anos de 2019 e 2013.
Põe `-` aqui para ficar como uma lista.

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/table_config.yaml
> +        description: Indicador de Adequação da Formação Docente (Informação referente ao Grupo 1, para os Anos Iniciais do EF)
Nessas descrições deixa por extenso `ensino fundamental`, `ensino médio`, etc.

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/table_config.yaml
> +        description: Razão entre o total de alunos presentes no SAEB e o total de alunos cadastrados no Censo Escolar que são público alvo do SAEB
Faltou dizer que é no 9o ano também.

2021-04-13 15:40 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2019_2013/publish.sql
> +SAFE_CAST(nivel_0_lp9 AS STRING) nivel_0_lp9,
Põe um `_` antes do `9` para separar `mt` do 9o ano. E vê a ordem para ficar consistente com todas as outras variáveis também.

2021-04-22 19:43 UTC, closed without merging