[dados] br_inep_saeb microdados_escola_2007_2019
basedosdados/mais pull request #401
Opened 2021-04-22 19:53 UTC by hevsouza

Oi amigxs
Subindo a nova tabela do saeb, agora com mais anos.
O código vou subir depois, vou tentar deixar menos feio hahah

2021-04-26 15:12 UTC, crislanealves approved these changes

2021-04-26 15:56 UTC, rdahis reviewed
Estou olhando mas vai ser muito mais fácil entender o PR com a tabela de arquitetura que você montou! Sobe ela no Drive que finalizamos isso, pode ser?

2021-04-26 15:56 UTC, rdahis commented on bases/br_inep_saeb/microdados_escola_2007_2019/table_config.yaml
> +        description: ID Escola
`ID Escola - Inep`

2021-04-26 19:03 UTC, hevsouza commented
> Estou olhando mas vai ser muito mais fácil entender o PR com a tabela de arquitetura que você montou! Sobe ela no Drive que finalizamos isso, pode ser?

Acabei de subir lá na pasta `dados`

2021-04-29 19:19 UTC, hevsouza commented
Subi outra tabela @rdahis @mavalentim @crislanealves

2021-05-11 02:00 UTC, mavalentim requested changes

2021-05-11 13:43 UTC, hevsouza commented on bases/br_inep_saeb/microdados_escola_2007_2019/table_config.yaml
> +        description: ID Escola - IBGE
nossa, simmm. mt lerda kkk

2021-05-12 05:12 UTC, rdahis commented
Comentei lá as arquiteturas e dicionário!

2021-05-12 14:39 UTC, crislanealves approved these changes

2021-06-08 17:13 UTC, closed without merging