[dados] br_denatran_frota
basedosdados/mais pull request #409
Opened 2021-05-01 00:17 UTC by pedrocastroo

Base de dados da frota de veículos

Dataset: `br_denatran_frota`

Tabelas:
- `uf_tipo`
- `municipio_tipo`

2021-05-02 20:42 UTC, rdahis commented
Não consegui rodar a query `SELECT * FROM basedosdados-312117.br_denatran_frota.municipio_tipo`. Acho que está privado o projeto (?)

2021-05-02 22:35 UTC, pedrocastroo commented
Agora está público

2021-05-03 14:44 UTC, crislanealves commented on bases/br_denatran_frota/municipio_tipo/table_config.yaml
> +        description: Sigla da Unidade da Federação original da base
@rdahis e @d116626 aqui pode ser só sigla_original ou sigla_uf, não?

2021-05-03 14:55 UTC, crislanealves requested changes
Bem legal =) 
Acredito que, no geral, está tudo certo! 
Só uns comentários/dúvidas gerais:

1. Não encontrei essa tabela no dev, ela ainda será upada?
2. Para as colunas ``ID do município`` e ``Sigla UF``  que estão no padrão IBGE, geralmente nomeamos como: ``ID Município - IBGE 7 Dígitos`` e ``Sigla da Unidade da Federação``.
3. Na tabela ``municipio_tipo`` tem as colunas``municipio_original`` e ``municipio``, este é padrão IBGE? Se sim,  @rdahis e @d116626 , é necessário ter os dois?

2021-05-03 15:29 UTC, rdahis requested changes
Muito bom, valeu! Deixei comentários só para manter a consistência com o resto do repositório.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/dataset_config.yaml
> +    name: Pedro Castro
Aqui seria o departamento original do Denatran, nesse caso.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(uf_original AS STRING) uf_original,
Vamos mudar essa coluna para `sigla_uf`.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio_original AS STRING) municipio_original,
Remover essa coluna.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(data AS STRING) data,
Mudar para `ano_mes`.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(id_uf AS INT64) id_uf,
A partir de agora estamos botando IDs assim como STRING.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(uf AS STRING) uf,
Remover essa coluna.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(id_municipio AS INT64) id_municipio,
Mudar para STRING.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio AS STRING) municipio,
Remover essa coluna. Está coberta pelo nosso diretório de municípios.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/table_config.yaml
> +observation_level: #REQUIRED
Certinho, boa!

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/table_config.yaml
> +    - id_municipio
Faltou `ano_mes`.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/table_config.yaml
> +    - brasil
Aqui é só `brasil`, já que a cobertura é o país inteiro.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/table_config.yaml
> +        description: Sigla da Unidade da Federação original da base
Deixei vários comentários lá no `publish.sql`. Olhar lá.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/uf_tipo/publish.sql
> +SAFE_CAST(uf AS STRING) uf,
Eu trocaria essa coluna `uf` pela `sigla_uf`, por consistência com o resto do repositório.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/uf_tipo/publish.sql
> +SAFE_CAST(id_uf AS INT64) id_uf,
Mudar para STRING.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/uf_tipo/publish.sql
> +SAFE_CAST(data AS STRING) data,
Mudar para `ano_mes`. E talvez quebrar essa coluna em duas: `ano` e `mes`.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(data AS STRING) data,
Ou ainda melhor, podemos quebrar essa coluna em duas: `ano` e `mes`.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/uf_tipo/table_config.yaml
> +    - estado
Aqui é `unidade da federação`.

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/uf_tipo/table_config.yaml
> +    - uf
Tirar `uf` e acrescentar `ano_mes` (ou `ano` & `mes`).

2021-05-03 15:29 UTC, rdahis commented on bases/br_denatran_frota/uf_tipo/table_config.yaml
> +    - estados
Tirar `estados`.

2021-05-03 16:58 UTC, pedrocastroo commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio_original AS STRING) municipio_original,
Os dados originais contém municípios que não existem na tabela de códigos do IBGE. A tabela original tem apenas a sigla da UF e nome do município em uppercase. Se remover a coluna `municipio_original` não será possível fazer uma localização de municípios extintos ou que alteraram o nome (?)

O que você recomenda?

Exemplos:
![image](https://user-images.githubusercontent.com/16160544/116906547-c9cf5c00-ac16-11eb-97c2-f2f9cdb73a1d.png)

2021-05-03 17:18 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio_original AS STRING) municipio_original,
Hm beleza, não tinha visto! Por dois exemplos aqui, parece que esses são municípios com nome diferente do diretório.

SANTA ROSA -> Santa Rosa do Purus, id_municipio='1200435'
LIVRAMENTO DO BRUMADO -> Livramento de Nossa Senhora, id_municipio='2919504'

A solução seria então dar um JOIN com o `br_bd_diretorios_brasil.municipio` em `sigla_uf` e `municipio` para recuperar o `id_municipio` de todos. Em passos:
1. Gerar uma nova coluna `municipio_minusculo` com os nomes minúsculos de todas as linhas (substituindo na mão o que tiver errado).
2. Fazer esse JOIN.
3. Manter só as colunas `sigla_uf`, `id_municipio`, `municipio_original`.

2021-05-03 19:05 UTC, hevsouza commented
Pelo o que eu vi, acho que depois dos comentários do Dahis e da Cris já fique tudo certinho : )

2021-05-03 19:06 UTC, hevsouza reviewed
Pelo o que eu vi, acho que depois dos comentários do Dahis e da Cris já fique tudo certinho : )

2021-05-05 19:34 UTC, mavalentim commented on bases/br_denatran_frota/municipio_tipo/table_config.yaml
> +version: v1.0 # REQUIRED
Mandou muito bem pedro! Acho legal só te lembrar que caso você atualize esses configs você alterar esse versionamento aqui, para accountability, principalmente!

2021-05-09 05:49 UTC, pedrocastroo commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(data AS STRING) data,
`ano` e `mes` como int64?

2021-05-10 19:04 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(data AS STRING) data,
Isso.

2021-05-14 05:01 UTC, rdahis commented
Fala @pedrocastroo! Alguma novidade? Podemos ajudar?

2021-05-14 05:20 UTC, pedrocastroo commented
@rdahis tudo certo, finalizo os ajustes neste final de semana.

2021-05-23 18:42 UTC, pedrocastroo commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio_original AS STRING) municipio_original,
Acho que agora está tudo certo.

Municípios que foi necessário alterar:

ASSU, RN -> AÇU, 2400208
BOA SAUDE, RN -> Januário Cicco, 2405306
BOM JESUS, GO -> Bom Jesus de Goiás, 5203500
EMBU, SP -> Embu das Artes, "3515004"
ITABIRINHA DE MANTENA, MG -> Itabirinha, 3131802
ITAMARACA, PE -> Ilha de Itamaracá, "2607604"
JAMARI, RO -> Candeias do Jamari, "1100809"
LIVRAMENTO DO BRUMADO, BA -> Livramento de Nossa Senhora, "2919504"
SANTA ROSA, AC -> Santa Rosa do Purus, "1200435"
SAO BENTO DE POMBAL, PB -> São Bentinho, "2513927"
VILA ALTA, PR -> Alto Paraíso, "4128625"
VILA NOVA DO MAMORE, RO -> Nova Mamoré, "1100338"

Somente esses que ficaram como `NA`:

```sql
SELECT sigla_uf, municipio_original, id_municipio, Count(*) FROM `basedosdados-312117.br_denatran_frota.municipio_tipo`
WHERE id_municipio = "NA"
GROUP BY sigla_uf, municipio_original, id_municipio
```

![image](https://user-images.githubusercontent.com/16160544/119272647-6022ec00-bbdd-11eb-88a9-d6412538abe8.png)

2021-05-23 18:44 UTC, pedrocastroo commented on bases/br_denatran_frota/uf_tipo/publish.sql
> +SAFE_CAST(id_uf AS INT64) id_uf,
A coluna `id_uf` foi removida.

2021-05-24 05:15 UTC, rdahis approved these changes
Boa, acho que tá basicamente tudo aí!

2021-05-24 05:16 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/table_config.yaml
> +        description: ID do Município
Mudar para `ID Município - IBGE 7 Dígitos`

2021-05-24 05:18 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio_original AS STRING) municipio_original,
Vamos deletar essas linhas onde `id_municipio=NA` na tabela `municipio_tipo`. A tabela é a nível de município, então temos que tirar o que não é atribuível a lugar algum.

2021-05-24 05:21 UTC, rdahis commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio_original AS STRING) municipio_original,
Fazendo o comentário acima, já pode deletar a coluna `municipio_original` também. Aí fica só `sigla_uf`, `id_municipio`, e `ano` e `mes` identificando as linhas.

2021-05-24 12:34 UTC, pedrocastroo commented on bases/br_denatran_frota/municipio_tipo/publish.sql
> +SAFE_CAST(municipio_original AS STRING) municipio_original,
Done

2021-05-24 18:10 UTC, rdahis commented
Dando merge dado que já respondeu-se todas as questões levantadas.

2021-05-24 18:10 UTC, merged

2021-05-24 18:24 UTC, rdahis commented
@pedrocastroo tá no nosso Discord? Qual teu usuário? :-)

2021-05-24 18:34 UTC, pedrocastroo commented
sim, aspeddro