[infra] Criação de relatório de atualização das tabelas
basedosdados/mais pull request #410
Opened 2021-05-01 14:30 UTC by jptbrandao

#issue309

2021-05-10 22:24 UTC, JoaoCarabetta requested changes
Desacoplar IO (yaml/requests API) da lógica de checagem.

Criar funcões com código repetido.

2021-05-24 22:48 UTC, polvoazul commented
Exemplo de retorno do endpoint (nesse caso ele indexa pelo nome e nao pelo dataset + table id, mas enfim):

https://basedosdados.org/api/3/action/package_show?name_or_id=achados-e-pedidos  (dataset)

https://basedosdados.org/api/3/action/resource_show?id=101c6a8e-4248-440d-8cc4-91c5c094cf0b (resource)

2021-05-24 23:02 UTC, d116626 commented
Exemplo de bdm_table, dataset_id = `br_me_rais` que transforma em `br-me-rais`

https://basedosdados.org/api/3/action/package_show?name_or_id=br-me-rais

2021-05-24 23:19 UTC, d116626 commented
Ckan API guidehttps://docs.ckan.org/en/2.9/api/

2021-07-02 13:43 UTC, rdahis commented
Como tá esse PR aqui? O que falta para aprovar?

2021-07-06 02:40 UTC, vncsna commented
Eu não sei, mas dou uma olhada amanhã.

2021-07-07 03:24 UTC, vncsna commented
Imagino que esteja parado, vou continuar em outro PR

2021-07-07 03:24 UTC, closed without merging