br_inep_saeb microdados_aluno
basedosdados/mais pull request #451
Opened 2021-05-19 17:49 UTC by hevsouza

Subindo as tabelas de alunos nesse PR

2021-05-21 14:13 UTC, crislanealves commented on bases/br_inep_saeb/microdados_aluno_2_ensino_fund/publish.sql
> +SAFE_CAST(conceito_questao_1_lp AS STRING) conceito_questao_1_lp,
Esse valores ``taxa_resposta_bloco_1_mt`` e ``taxa_resposta_bloco_2_mt`` estão com muitos valores em branco (não conferir todos), é isso mesmo ?

2021-05-21 14:14 UTC, crislanealves approved these changes
@hevsouza , Só deixei uma dúvida aqui, mas vou deixar aprovado porque acho que tá tudo certinho.

2021-05-26 19:40 UTC, mavalentim requested changes

2021-05-26 19:40 UTC, mavalentim commented on bases/br_inep_saeb/microdados_aluno_2_ensino_fund/table_config.yaml
> +version: <vA.B> # REQUIRED
versao mo

2021-05-26 19:40 UTC, mavalentim commented on bases/br_inep_saeb/microdados_aluno_2_ensino_fund/table_config.yaml
> +        name: localizacao
amiga esse localizacao é a que tem possibilidades? tipo é a que assume 1,2,3 ? se for voce consegue por `tipo_localizacao` ? Acho que ai vai casar com o censo!

2021-06-08 17:33 UTC, hevsouza commented
A de aluno_ensino_medio ainda vou preencher com o config

2021-06-22 21:39 UTC, mavalentim approved these changes

2021-07-28 19:19 UTC, hevsouza commented
@d116626 se puder preencher pra mim as tabelas:

aluno_ensino_fundamental_2007_2019 = https://docs.google.com/spreadsheets/d/1vEQmaa0pAQo9X0LJMDjewpXqs-Zjr0ZnFgWMESqaSdA/edit#gid=0

aluno_ensino_medio_2011_2019 = https://docs.google.com/spreadsheets/d/1wkoBJp758d-HXNc-GLciDpZgPWE6wG5mgi2bMEj3Q1s/edit#gid=0

aluno_ef_1995_2005 = https://docs.google.com/spreadsheets/d/10R4fu189_1BgyaqBbDKca3N5pNsHqgFQInmqMPVOjB8/edit#gid=0

aluno_em_1995_2005 = https://docs.google.com/spreadsheets/d/12XdTHT_6YMu-m9Nsjw0m1Xuw2_hHAmqC-qI36yKzAKI/edit#gid=0

2021-07-28 20:33 UTC, d116626 commented
@hevsouza, feito! Confere se ta tudo certo

2021-08-07 14:48 UTC, rdahis commented
@hevsouza está tudo pronto pra merge aqui? Dá um ok?

2021-08-09 14:36 UTC, hevsouza commented
> @hevsouza está tudo pronto pra merge aqui? Dá um ok?

dahis vou só fazer um último commit hoje mais tarde, tenho que mudar o nome de 2 tabelas antigas

2021-08-11 15:08 UTC, hevsouza commented
@rdahis tudo pronto

2021-08-15 12:21 UTC, merged

2021-08-15 12:28 UTC, rdahis commented
@hevsouza deu pau no merge :-( https://github.com/basedosdados/mais/runs/3333317492?check_suite_focus=true

Posso pedir pra você abrir o PR de novo modificando o campo `last_updated` em todos os table_configs? Assim deve funcionar os data checks.