[dados]br_bd_diretorios_brasil instituicao_ensino_superior
basedosdados/mais pull request #458
Opened 2021-05-25 08:34 UTC by mavalentim

Adiciona instituicoes de ensino superior. Não consegui subir a base de cursos por um erro no CLI que vou mandar pra infra amanhã.

2021-05-25 17:02 UTC, rdahis requested changes

2021-05-25 17:02 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(id_municipio AS STRING) id_municipio,
Pode jogar `id_municipio` e `sigla_uf` para o fim da tabela.

2021-05-25 17:02 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/table_config.yaml
> +    Mudança de nome das variáveis
Adiciona um `-` aqui.

2021-05-25 18:51 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(id_dependencia_administrativa AS STRING) id_dependencia_administrativa,
as strings dessa variável são se a instituicao é federal, estadual e por ai vai, é a variável seguinte `rede` . Deixo só a `rede` entao?

2021-05-25 18:52 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(id_dependencia_administrativa AS STRING) id_dependencia_administrativa,
acho que talvez seja uma boa mudar o nome `rede` pensando bem

2021-05-25 22:14 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(id_dependencia_administrativa AS STRING) id_dependencia_administrativa,
Deixa só a versão string dela. Confere se `rede` é o mesmo nome de variável usado nas outras bases do Inep para essa informação.

2021-05-26 15:24 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(nome_ies AS STRING) nome_ies,
não achei ainda :(

2021-05-27 01:53 UTC, mavalentim commented
@rdahis adicionei novos diretorios tambem necessarios para o censo e corrigi o antigo! da uma olhada até domingo!

2021-05-27 06:46 UTC, rdahis requested changes

2021-05-27 06:46 UTC, rdahis commented on bases/br_bd_diretorios_brasil/curso_superior/publish.sql
> +SAFE_CAST(id_curso AS STRING) id_curso,
Põe `id_curso` e `nome_curso` no começo da tabela.

2021-05-27 06:46 UTC, rdahis commented on bases/br_bd_diretorios_brasil/pais/publish.sql
> +CREATE VIEW basedosdados-dev.br_bd_diretorios_brasil.pais AS
Essa tabela é necessária agora mesmo? Porque já estava planejando subir uma versão mais completa dela com códigos padronizados internacionalmente, etc. E talvez ela more em outra base `br_bd_diretorios_mundo` (algo assim).

2021-05-27 06:46 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(tipo_instituicao AS STRING) tipo_instituicao,
Faltou acento no `Pública`.

2021-05-27 06:46 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(id_rede_ies AS STRING) id_rede_ies,
Essa variável é essencial? Me parece que podemos deletá-la e só manter a `rede`.

2021-05-27 06:46 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SELECT
Pode renomear `nome_ies` para `nome`, `rede_ies` para `rede`.

2021-05-27 23:02 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(tipo_instituicao AS STRING) tipo_instituicao,
essa foi proposital achei que daria trabalho ahahah

2021-05-27 23:02 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(id_rede_ies AS STRING) id_rede_ies,
Acho que nao, nem temos ela no resto da BD

2021-05-27 23:03 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SELECT
acho melhor nao mudar para `rede` pois rede é o nome da variavel escolar, que nao é a mesma coisa que essa aí, posso por outro nome se preferir!

2021-05-27 23:05 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SELECT
tambem nao querendo ser chato, mas mudar para nome nao vai deixar muito generico? nao fazemos isso com outras variaveis : deixamos nome_escola, nome_municipio ao invés de só nome nas respectivas tabelas

2021-05-27 23:07 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/pais/publish.sql
> +CREATE VIEW basedosdados-dev.br_bd_diretorios_brasil.pais AS
Cara, acho necessário pois duas tabelas do censo dependem dela. Acho que então a gente deixar essa e futuramente mudar, só para nao compromenter quem quiser usar já agora, muito ruim?

2021-05-29 16:13 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SELECT
É, então. Isso é algo que queria começar a implementar mas ainda tô na dúvida. O padrão em bases normalizadas é esse. Exemplo: na tabela `municipio` a variável `nome` não precisa se chamar `nome_municipio` porque já se sabe que a unidade de observação é um município.

2021-05-29 16:15 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SELECT
Sobre `rede`, se não tiver outra palavra natural para substituir, vamos usar `rede` mesmo. Ainda que seja o mesmo nome para variável escolar, porque isso não é chave primária.

2021-05-29 16:16 UTC, rdahis commented on bases/br_bd_diretorios_brasil/pais/publish.sql
> +CREATE VIEW basedosdados-dev.br_bd_diretorios_brasil.pais AS
Ok!

2021-05-29 16:16 UTC, rdahis commented on bases/br_bd_diretorios_brasil/pais/publish.sql
> +CREATE VIEW basedosdados-dev.br_bd_diretorios_brasil.pais AS
Se no futuro eu tirar essa tabela dessa base, eu atualizo as tabelas de arquitetura dependendo disso.

2021-05-31 18:06 UTC, crislanealves approved these changes

2021-06-02 01:16 UTC, rdahis commented
Finalizado aqui @mavalentim?

2021-06-02 03:38 UTC, mavalentim commented
> Finalizado aqui @mavalentim?

Tudo pronto doutor, só nao consigo mergir por causa do changes requested, ajude nois hahah

2021-06-02 14:03 UTC, hevsouza approved these changes

2021-06-02 18:32 UTC, mavalentim commented
@rdahis dear ricardo,
unblock the blocking,
yours sincerely

2021-06-03 01:18 UTC, rdahis approved these changes

2021-06-03 01:23 UTC, merged