[infra] r-package - metadados das tabelas e datasets
basedosdados/mais pull request #460
Opened 2021-05-25 20:29 UTC by pedrocastroo

Essa PR adiciona duas novas funções para acessar os metadados:

- `view_metadata_table`
- `view_metadata_dataset`

Ambas não retornam nada (`invisible(NULL)`), apenas fornece um interface para visualizar os metadados.

No RStudio abre o Viewer:

```r
basedosdados::view_metadata_table("br_ibge_pib.municipios")
```

![image](https://user-images.githubusercontent.com/16160544/119561772-fab93180-bd7b-11eb-8d87-0d022bc2ed7a.png)

Pelo terminal R, um arquivo HTML é aberto no navegador.

fullscreenshot: https://user-images.githubusercontent.com/16160544/119563850-75834c00-bd7e-11eb-9db6-9e40d93aa37f.png

</details>

2021-05-26 13:29 UTC, JoaoCarabetta commented
Muito bom!

Acho que podemos adicionar algumas funções que já tem no python:

- `list_datasets` --> [docs](https://basedosdados.github.io/mais/reference_api_py/#basedosdados.download.download.list_datasets)
- `list_dataset_tables` --> [docs](https://basedosdados.github.io/mais/reference_api_py/#basedosdados.download.download.list_dataset_tables)

Veja se é possível fazer em R

2021-05-26 14:53 UTC, JoaoCarabetta commented
Pergunta, se o Rstudio carrega qlqr url, podemos carregar a página do base dos dados da tabela?

2021-05-26 15:02 UTC, pedrocastroo commented
O pacote `rstudioapi` carrega apenas arquivo local ou uma página rodando no `localhost`

https://github.com/rstudio/rstudio/issues/2252

2021-05-27 04:57 UTC, pedrocava requested changes
Tá muito bom. Só realmente senti falta de algumas indicações do que está acontecendo no corpo da função principal.

2021-05-27 04:57 UTC, pedrocava commented on r-package/R/metadata.R
> +  ) -> dom
Tudo até agora conseguiu seguir as linhas de code-as-documentation, mas isso tá bem confuso para quem nunca mexeu com o `htmltools`. Acho que vale alguns comentários :)

2021-05-27 04:57 UTC, pedrocava commented on r-package/R/metadata.R
> +  }
Pode explicar por que esse retorno?

2021-05-27 16:24 UTC, pedrocastroo commented on r-package/R/metadata.R
> +  ) -> dom
tô refatorando

2021-05-27 16:38 UTC, pedrocastroo commented on r-package/R/metadata.R
> +  }
é pra finalizar a função, sem um return o Viewer no rstudio e uma aba no navegador (se `browser` path estiver definido) abriria.

2021-05-27 17:12 UTC, pedrocastroo commented
fiz algumas alterações:

- `view_metadata_table` -> `view_meta_table`
- `view_metadata_dataset` -> `view_meta_dataset`

Adicionei duas novas:

- `view_datasets`
- `view_dataset_tables`

Mantive os parâmetros das mesmas funções no python, exceto o param `from_file`.

Não implementei `get_dataset_description` e `get_table_columns` pois `view_meta_table` fornece essas informações (mas se quiser ok):

![image](https://user-images.githubusercontent.com/16160544/119865892-8e147300-bef2-11eb-8890-8c3e37fed9d3.png)

O background e foreground do Viewer é o mesmo do tema do RStudio se `rstudioapi`estiver disponível.

### Possível recurso:

Toda vez que o usuário quiser acessar os metadados de uma tabela ele precisa passar o `dataset_id` e `table_id`:

```r
basedosdados::view_meta_table("br_denatran_frota", "municipio_tipo")
```

As funções que retornam um `data.frame` ou `tibble` pode carregar uma `attr` com o id da tabela:

```r
basedosdados::read_sql("some query for basedosdados.br_ibge_pib.municipios") -> df

df %>% view_meta_table() #abre o metadados de "br_ibge_pib.municipios"
```
Há alguma preferência de como as informações são apresentadas no Viewer?

@JoaoCarabetta estava colocando a lista de dataset com um link, mas para alguns a url estava incorreta pois o `dataset_id` do BQ não é o mesmo do site `https://basedosdados.org/dataset/<id>`

2021-05-27 18:54 UTC, JoaoCarabetta commented
1. Sugestões para o nome das funções para manter a integridade entre os pacotes em R e python

| python                  | R                    |
|-------------------------|----------------------|
| get_dataset_description | get_dataset_metadata |
| get_table_columns       | get_table_metadata   |
| get_table_description   | get_table_metadata   |
| get_table_size          | get_table_size       |
| list_dataset_tables     | list_dataset_tables  |
| list_datasets           | list_datasets        |

Observe que `get_table_columns` e `get_table_description` estão contidas em `get_table_metadata`.

A principio, prefiro manter a consistência entre os pacotes. Mas, se houver algum bom motivo para trocar o nome, estou aberto a discussão.

2. Gostei do recurso proposto para acessar facilmente os metadados. Temos que tomar cuidado por uma query pode conter  + de 1 tabela. Um join, por exemplo. Então, talvez podemos pensar nesse recurso com mais calma no futuro.

3. Estamos reformulando o site para espelhar melhor nossa estrutura de dataset_id e table_id. Podemos fazer essa integração depois.

2021-05-31 11:59 UTC, JoaoCarabetta commented
Ótimo! Acho que agora só faltam os testes, certo?

2021-06-01 04:27 UTC, pedrocava requested changes
Tem mudanças nas docs importantes. Sobre testagem, vamos precisar fazer um snapshot test disso. Uma boa referência está no [site do `testthat`](https://testthat.r-lib.org/articles/snapshotting.html). Enfatizando que nem sempre quem for validar os resultados do snapshot test sabe html. Se isso for necessário para aprovar o output de uma função, documente o que for necessário saber para avaliar.

2021-06-01 04:27 UTC, pedrocava commented on r-package/R/metadata.R
> +#' @param table_id, a character, table id
Sem a vírgula depois do nome do argumento, sem "a character". Melhor ser mais explícito com o que exatamente é o `dataset_id`.

2021-06-01 04:27 UTC, pedrocava commented on r-package/R/metadata.R
> +#' @param query_project_id, a character, which project the table lives. You can change this you want to query different projects. Default is \code{"basedosdados"}
Precisamos mesmo desse parâmetro? Quais são os outros projetos que temos atualmente? Se sim, tirar a vírgula depois do nome e dar uma arrumada no texto.

2021-06-01 04:27 UTC, pedrocava commented on r-package/R/metadata.R
> +                          ...) {
Aumenta o default de `page_size` para 100k por favor. Muitos usuários estão tendo problemas com isso e é melhor subir tudo de uma vez.

2021-06-01 04:27 UTC, pedrocava commented on r-package/R/metadata.R
> +                                ...) {
Subir `page_size`

2021-06-01 04:27 UTC, pedrocava commented on r-package/R/metadata.R
> +}
Por favor incluir mais texto nas docs ou comentários no corpo explicando o que essas funções fazem. Imagine que alguém que nunca mexeu com páginas html na vida precisa fazer manutenção nisso.

2021-06-01 13:23 UTC, JoaoCarabetta commented on r-package/R/metadata.R
> +#' @param query_project_id, a character, which project the table lives. You can change this you want to query different projects. Default is \code{"basedosdados"}
é importante deixar o query_project_id sempre explícito. Isso pq a infra do BD pode ser reproduzida por outras orgs (eu uso ela na secretaria de transportes por exemplo). Desse jeito, o mesmo pacote pode ser usado internamente somente com a mudança do query_project_id

2021-06-01 18:43 UTC, aspeddro commented
> Tem mudanças nas docs importantes. Sobre testagem, vamos precisar fazer um snapshot test disso. Uma boa referência está no [site do `testthat`](https://testthat.r-lib.org/articles/snapshotting.html). Enfatizando que nem sempre quem for validar os resultados do snapshot test sabe html. Se isso for necessário para aprovar o output de uma função, documente o que for necessário saber para avaliar.

As funções retornam `NULL`, para os snapshot tests preciso retornar o html (?). Mantive `NULL` pois a api em python retorna `None`. Fiz alguns testes com `testthat` sempre esperando `invisible(NULL)`

2021-06-18 05:03 UTC, aspeddro commented on r-package/R/metadata.R
> +                          ...) {
`page_size` com 100k da erro, coloquei 99999

```r
> list_datasets(page_size = 100000)
Erro: Invalid value at 'max_results.value' (TYPE_UINT32), "1e+05" [invalid] 
Run `rlang::last_error()` to see where the error occurred.
```

2021-09-22 05:35 UTC, pedrocava commented
Fechando pois acabamos indo pelo lado do CKAN.

2021-09-22 05:35 UTC, closed without merging