[dados] br_ibge_inflacao
basedosdados/mais pull request #475
Opened 2021-06-01 18:17 UTC by aspeddro

Índice Nacional de Preços ao Consumidor Amplo 15 - IPCA-15

dataset_id: `br_ibge_inflacao`
table_id: `ipca15`

#472

2021-06-01 23:14 UTC, mavalentim approved these changes
Boa Pedro! Ficaram ótimos! Dá inclusive para fazer umas visualizações bem legais.

2021-06-02 01:32 UTC, rdahis requested changes
Excelente! Por enquanto não temos infra pra automatizar subir todo mês mas em breve isso chega.

2021-06-02 01:32 UTC, rdahis commented on bases/br_ibge_inflacao/dataset_config.yaml
> +organization: instituto-brasileiro-de-geografia-e-estatistica # REQUIRED
Aqui é `br-ibge`.

2021-06-02 01:32 UTC, rdahis commented on bases/br_ibge_inflacao/ipca15/publish.sql
> +SAFE_CAST(var_mes AS FLOAT64) var_mes,
Vamos trocar `var` por `variacao` em todas as colunas.

2021-06-02 02:19 UTC, d116626 approved these changes
LGTM

2021-06-02 02:24 UTC, merged