[dados] br_inep_censo_escolar.dicionario
basedosdados/mais pull request #485
Opened 2021-06-02 21:20 UTC by mavalentim

Add dicionario de todas as tabelas na BigQuery

2021-06-07 22:23 UTC, hevsouza approved these changes

2021-06-08 12:43 UTC, rdahis requested changes
Simbora!

2021-06-08 12:43 UTC, rdahis commented on bases/br_inep_censo_escolar/dicionario/publish.sql
> +SAFE_CAST(cobertura_temporal AS STRING) cobertura_temporal
Essa coluna vem depois de `chave`.

2021-06-08 12:43 UTC, rdahis commented on bases/br_inep_censo_escolar/dicionario/publish.sql
> +SAFE_CAST(valor AS STRING) valor,
Ainda tem strings com espaços extras à esquerda. Dá um trim na coluna toda pra tirar isso.

2021-06-08 12:43 UTC, rdahis commented on bases/br_inep_censo_escolar/dicionario/table_config.yaml
> +    -Consulta básica de arquivos de dicionário disponibilizados por fontes oficiais.
Põe um espacinho aqui depois de `-` :-)

2021-06-08 12:43 UTC, rdahis commented on bases/br_inep_censo_escolar/dicionario/table_config.yaml
> +    - chave
Inclui `cobertura temporal`.

2021-06-08 12:43 UTC, rdahis commented on bases/br_inep_censo_escolar/dicionario/table_config.yaml
> +    - chave
Inclui `cobertura_temporal`.

2021-06-09 21:33 UTC, crislanealves approved these changes
Tudo certo por aqui, migs.

Só mudar na descrição para ``múltiplos`` e ``têm``.

2021-06-10 16:30 UTC, rdahis commented on bases/br_inep_censo_escolar/dicionario/publish.sql
> +SAFE_CAST(cobertura_temporal AS STRING) cobertura_temporal
Quis dizer entre `chave` e `valor` :-)

2021-06-10 16:31 UTC, rdahis approved these changes

2021-06-10 16:31 UTC, merged