[dados] Revisão br_ana_atlas_esgotos
basedosdados/mais pull request #521
Opened 2021-06-30 19:50 UTC by hevsouza

Também tive que subir uma nova tabela, agora o nome é municipio, no singular.

2021-06-30 20:33 UTC, d116626 approved these changes
LGTM

2021-07-02 03:26 UTC, mavalentim approved these changes

2021-07-05 12:27 UTC, rdahis requested changes

2021-07-05 12:27 UTC, rdahis commented on bases/br_ana_atlas_esgotos/municipio/publish.sql
>  SAFE_CAST(sigla_uf AS STRING) sigla_uf,
Botar `sigla_uf` antes de `id_municipio`.

2021-07-06 23:30 UTC, rdahis approved these changes

2021-07-06 23:30 UTC, merged