[dados] Revisão br_anvisa_medicamentos_industrializados
basedosdados/mais pull request #523
Opened 2021-06-30 20:18 UTC by hevsouza

2021-06-30 20:24 UTC, d116626 approved these changes
LGTM

2021-07-05 12:25 UTC, rdahis requested changes

2021-07-05 12:25 UTC, rdahis commented on bases/br_anvisa_medicamentos_industrializados/microdados/publish.sql
>  SAFE_CAST(sigla_uf AS STRING) sigla_uf,
Aproveita e já põe o `sigla_uf` antes de `id_municipio`. :-)

2021-07-06 23:31 UTC, rdahis approved these changes

2021-07-06 23:31 UTC, merged