[dados] Revisão br_ibge_amc
basedosdados/mais pull request #526
Opened 2021-06-30 23:03 UTC by hevsouza

2021-07-02 03:26 UTC, mavalentim approved these changes

2021-07-02 12:53 UTC, crislanealves approved these changes

2021-07-05 11:38 UTC, rdahis commented on bases/br_ibge_amc/municipio_de_para/table_config.yaml
> +url_ckan: https://basedosdados.org/dataset/br-inep-saeb # AUTO GENERATED
Por que apareceu `br-inep-saeb` aqui? @hevsouza

2021-07-05 11:43 UTC, rdahis commented
Faltou renomear `id_AMC` para `id_amc`. @hevsouza

2021-07-06 02:29 UTC, rdahis requested changes

2021-07-06 02:29 UTC, rdahis commented on bases/br_ibge_amc/municipio_de_para/publish.sql
> +SAFE_CAST(id_AMC AS STRING) id_AMC
Botar minúsculo: `id_amc`.

2021-07-06 19:15 UTC, closed without merging