[dado] Revisão br_inep_ideb
basedosdados/mais pull request #533
Opened 2021-07-02 21:12 UTC by hevsouza

2021-07-05 12:07 UTC, rdahis requested changes
Isso aí! Pequenos comentáriozinhos.

2021-07-05 12:07 UTC, rdahis commented on bases/br_inep_ideb/escola/table_config.yaml
> +        name: nome_escola
Vamos excluir as colunas `nome_escola` e `nome_municipio`.

2021-07-05 12:07 UTC, rdahis commented on bases/br_inep_ideb/escola_ano_escolar/table_config.yaml
> +        name: nome_escola
Excluir variáveis também.

2021-07-06 23:49 UTC, rdahis requested changes
Várias mudanças pra consertar os data checks.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/escola/table_config.yaml
> +    - id_escola
Adicionar `anos_escolares` abaixo.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/escola_ano_escolar/table_config.yaml
> +    - ano_escolar
Adicionar `ano` aqui.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/estado/table_config.yaml
> +    - ensino
Adicionar `anos_escolares` aqui.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/estado_ano_escolar/table_config.yaml
>      - rede
Adicionar `ensino` aqui.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/municipio/table_config.yaml
>      - ensino
Adicionar `anos_escolares` aqui.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/municipio_ano_escolar/table_config.yaml
>      - rede
Adicionar `ensino` aqui.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/regiao/table_config.yaml
> +    - ensino
Adicionar `anos_escolares` aqui.

2021-07-06 23:49 UTC, rdahis commented on bases/br_inep_ideb/regiao_ano_escolar/table_config.yaml
> +    - rede
Adicionar `ensino` aqui.

2021-07-07 12:08 UTC, crislanealves approved these changes

2021-07-07 12:12 UTC, rdahis commented
@crislanealves tem que ser mais exigente nos PRs. Nesse caso tá com vários probleminhas nos data checks.

2021-07-08 19:35 UTC, rdahis commented
No que deu erro falta adicionar `ensino`.

2021-07-09 15:56 UTC, rdahis approved these changes

2021-07-09 15:57 UTC, merged