[dados] Revisão br_mapbiomas_estatisticas
basedosdados/mais pull request #540
Opened 2021-07-05 20:39 UTC by hevsouza

2021-07-06 02:26 UTC, rdahis requested changes

2021-07-06 02:26 UTC, rdahis commented on bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/publish.sql
>  SAFE_CAST(id_classe AS INT64) id_classe,
Esse `id_classe` deveria ser `STRING`, não?

2021-07-06 02:26 UTC, rdahis commented on bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/publish.sql
>  SAFE_CAST(id_classe AS INT64) id_classe,
Pra todas as tabelas.

2021-07-06 02:26 UTC, rdahis commented on bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/publish.sql
>  SAFE_CAST(id_classe AS INT64) id_classe,
E também `de_id_classe` e `para_id_classe`.

2021-07-06 02:30 UTC, rdahis commented
@hevsouza vamos revisar o que está ocorrendo com todos esses erros aqui.

2021-07-06 21:58 UTC, rdahis requested changes

2021-07-06 21:58 UTC, rdahis commented on bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/publish.sql
>  SAFE_CAST(area AS NUMERIC) area
@hevsouza Aqui tem que mudar para `FLOAT64`. Não sei porque eu fiz assim com `NUMERIC` :-/

2021-07-07 12:12 UTC, crislanealves approved these changes

2021-07-07 14:38 UTC, hevsouza commented on bases/br_mapbiomas_estatisticas/cobertura_estado_bioma_classe/publish.sql
>  SAFE_CAST(area AS NUMERIC) area
e eu mudei as outras pra float e esqueci dessa kk

2021-07-07 14:45 UTC, hevsouza commented
@rdahis to confusa com os datachecks, ele diz que a tabela n existe mas ta tudo lá no BQ

2021-07-07 21:32 UTC, rdahis commented
@d116626 o que acha?

2021-07-07 21:56 UTC, d116626 commented
> @rdahis to confusa com os datachecks, ele diz que a tabela n existe mas ta tudo lá no BQ

@vncsna, que acha? Acho que a query ta com problema, 

https://github.com/basedosdados/mais/blob/1485fdfcc5259f5a6bf73b965e6d7e3bd2bf4d94/.github/workflows/data-check/checks.yaml#L1-L19

tem que tirar o `NOT`da query ou mudar a logica do `assert`

2021-07-07 22:08 UTC, vncsna commented
Vou verificar isso

2021-07-08 19:30 UTC, rdahis commented
Nesse que deu erro, tem que mudar `municipio` para `id_municipio`. @hevsouza

2021-07-09 15:53 UTC, rdahis approved these changes

2021-07-09 15:53 UTC, merged