[dados] Revisão br_seeg_emissoes
basedosdados/mais pull request #541
Opened 2021-07-05 21:18 UTC by hevsouza

2021-07-06 02:24 UTC, rdahis commented
Não faltou re-publicar a tabela aqui não?

2021-07-06 22:01 UTC, rdahis commented
@hevsouza a tabela `municipio` tá vazia aqui.

2021-07-06 22:01 UTC, rdahis requested changes
A tabela municipio tá vazia aqui.

2021-07-07 12:50 UTC, crislanealves commented
Acho que tá meio bugado esse dataset, a query não tá retornando resultado para nenhuma das tabelas por aqui.

2021-07-07 14:46 UTC, hevsouza commented
> Acho que tá meio bugado esse dataset, a query não tá retornando resultado para nenhuma das tabelas por aqui.

sim, e eu só fiz revisão na de município

2021-07-07 18:46 UTC, mavalentim approved these changes
os dados tão lá agora gente! seguimos

2021-07-08 00:03 UTC, hevsouza commented
@rdahis se os primary keys estiverem certos acho q ta ok aqui

2021-07-08 19:29 UTC, rdahis approved these changes

2021-07-08 19:29 UTC, merged