[dados] Revisão br_mc_auxilio_emergencial
basedosdados/mais pull request #553
Opened 2021-07-06 21:22 UTC by hevsouza

2021-07-06 23:20 UTC, rdahis requested changes

2021-07-06 23:20 UTC, rdahis commented on bases/br_mc_auxilio_emergencial/microdados/table_config.yaml
> +    - mes
Adicionar `id_municipio` abaixo de `mes`.

2021-07-06 23:20 UTC, rdahis commented on bases/br_mc_auxilio_emergencial/microdados/table_config.yaml
> +    - nome_beneficiario
Adicionar `parcela` abaixo de `nome_beneficiario`.

2021-07-07 19:39 UTC, mavalentim approved these changes
ordem ta certa uhul

2021-07-08 20:27 UTC, rdahis approved these changes

2021-07-08 20:28 UTC, rdahis commented
Deixando passar aqui sem aprovar o check de colunas identificadoras.

2021-07-08 20:28 UTC, merged