[dados] Revisão br_bd_diretorios_brasil
basedosdados/mais pull request #570
Opened 2021-07-09 15:22 UTC by hevsouza

mudei causa_violencia e causa_overdose em `cid10` para string (é assim mesmo ou deixa INT?)
e reordenei colunas de `distrito` `escola` `instituicao_ensino_superior`

2021-07-09 15:52 UTC, rdahis commented
`causa_violencia` e `causa_overdose` no caso são `INT64` mesmo porque são indicadoras 0/1. Vou olhar o resto.

2021-07-12 14:35 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/escola/publish.sql
> +SAFE_CAST(rede AS STRING) rede
acho que seria legal deixar já na ordem, onde `rede` fica antes de `id_escola`

2021-07-12 14:35 UTC, mavalentim commented on bases/br_bd_diretorios_brasil/escola/publish.sql
> +SAFE_CAST(rede AS STRING) rede
(não tenho tanta certeza assim se essa é a ordem anseada @rdahis )

2021-07-12 17:54 UTC, hevsouza commented on bases/br_bd_diretorios_brasil/escola/publish.sql
> +SAFE_CAST(rede AS STRING) rede
pensei que rede ficava depois

2021-07-12 18:04 UTC, rdahis commented on bases/br_bd_diretorios_brasil/escola/publish.sql
> +SAFE_CAST(rede AS STRING) rede
Isso. Nos diretórios, as variáveis "mais agregadas" ficam pra trás. A primeira variável é sempre a chave primária.

2021-07-12 20:20 UTC, rdahis requested changes

2021-07-12 20:20 UTC, rdahis commented on bases/br_bd_diretorios_brasil/distrito/publish.sql
> +SAFE_CAST(sigla_uf AS STRING) sigla_uf,
Vamos manter a ordem como em todas as tabelas originais.

2021-07-12 20:20 UTC, rdahis commented on bases/br_bd_diretorios_brasil/escola/publish.sql
>  SAFE_CAST(id_escola AS STRING) id_escola,
Manter ordem original.

2021-07-12 20:20 UTC, rdahis commented on bases/br_bd_diretorios_brasil/instituicao_ensino_superior/publish.sql
> +SAFE_CAST(id_municipio AS STRING) id_municipio,
Manter ordem original.

2021-07-12 21:39 UTC, closed without merging