[dados] Revisão br_ibge_censo_demografico
basedosdados/mais pull request #574
Opened 2021-07-12 18:28 UTC by hevsouza

mudei para string algumas variáveis, algumas fiquei em dúvida e deixei INT, vejam se está certinho por favorrr

2021-07-12 20:29 UTC, rdahis requested changes

2021-07-12 20:29 UTC, rdahis commented on bases/br_ibge_censo_demografico/microdados_domicilio_1970/publish.sql
> +SAFE_CAST(numero_familia AS STRING) numero_familia,
Essa continua como `INT64` eu acho.

2021-07-19 18:26 UTC, hevsouza commented
@rdahis aqui tá pronto, eu acho

2021-07-20 12:57 UTC, rdahis commented
@hevsouza consegue ver por que tem colunas nulas nas tabelas de 2010?

2021-07-21 19:10 UTC, hevsouza commented
> @hevsouza consegue ver por que tem colunas nulas nas tabelas de 2010?

ricardo, esses erros vieram da tabela de prod, rodando a query pra `basedosdados` veio a mesma coisa, alguma direção do que eu posso fazer?

2021-07-21 20:29 UTC, rdahis commented
> > @hevsouza consegue ver por que tem colunas nulas nas tabelas de 2010?
> 
> ricardo, esses erros vieram da tabela de prod, rodando a query pra `basedosdados` veio a mesma coisa, alguma direção do que eu posso fazer?

Jura? Então vamos deixar assim por enquanto. No futuro olhamos de novo com mais calma.

2021-07-21 20:35 UTC, rdahis approved these changes

2021-07-21 20:35 UTC, merged

2023-02-28 15:33 UTC, gdocesp commented
Os Censos de 1980 e 1991 estão sem as chaves id_domicilio para juntar as bases de domicílios e pessoas...