[dados] Revisão br_sp_alesp
basedosdados/mais pull request #582
Opened 2021-07-13 19:02 UTC by hevsouza

mudei de `deputados` para `deputado` (tive que criar uma nova tabela do 0)
mudei algumas variáveis para string em `despesa_gabinete` e `despesa_gabinete_atual`

2021-07-14 13:53 UTC, rdahis requested changes

2021-07-14 13:53 UTC, rdahis commented on bases/br_sp_alesp/deputado/table_config.yaml
> +version: <vA.B> # REQUIRED
Faltou aqui.

2021-07-14 13:53 UTC, rdahis commented on bases/br_sp_alesp/deputado/table_config.yaml
> +    - sp
Maiúsculo aqui.

2021-07-14 13:53 UTC, rdahis commented on bases/br_sp_alesp/deputado/publish.sql
>  SAFE_CAST(nome_deputado AS STRING) nome_deputado,
Renomear para `nome`.

2021-07-15 21:03 UTC, d116626 commented
Realmente as colunas `ano`, `mes`, `matricula` e `fornecedor` não identificam as tabelas `despesas_gabinete_atual` e `despesas_gabinete_atual` unicamente. Olhando melhor pros dados essa tabela não tem nenhuma combinação que gere identificadores unicos, pode deixar em branco

2021-07-20 12:32 UTC, rdahis approved these changes

2021-07-20 12:32 UTC, merged