[dados] Revisão mundo_onu_adh
basedosdados/mais pull request #587
Opened 2021-07-13 20:04 UTC by hevsouza

tive que subir novas tabelas para mudar `estados` para `uf` e `municipios` para `municipio`

2021-07-14 13:37 UTC, rdahis requested changes

2021-07-14 13:37 UTC, rdahis commented on bases/mundo_onu_adh/uf/publish.sql
> +SAFE_CAST(uf AS STRING) sigla_uf,
Aqui vai dar o mesmo erro com mudanças de nome de variável. Preciso que você renomeie a variável `uf` no csv original e suba ele já correto @hevsouza. Se tiver dúvidas me avisa.

2021-07-15 19:50 UTC, hevsouza commented
esse `check if columns null` não consegui resolver, eu só baixei o csv do storage e subi de novo, nem mexi nele. Acho que vou subir de novo do 0 pra ver no que dá

2021-07-17 14:01 UTC, rdahis commented
Resolvi. Por algum motivo tinha o csv de `uf` dentro do Storage de `municipio`. Aí ele dava erro de número de colunas porque `uf` não tem a coluna `id_municipio`.

2021-07-17 14:11 UTC, rdahis approved these changes

2021-07-17 14:11 UTC, merged