[dados] Revisão br_sp_gov_orcamento
basedosdados/mais pull request #594
Opened 2021-07-16 02:45 UTC by hevsouza

2021-07-17 13:40 UTC, rdahis requested changes

2021-07-17 13:40 UTC, rdahis commented on bases/br_sp_gov_orcamento/despesas/publish.sql
> +SAFE_CAST(35 as STRING) id_estado,
Remover essa coluna.

2021-07-17 13:40 UTC, rdahis commented on bases/br_sp_gov_orcamento/receita_arrecadada/publish.sql
> +    SAFE_CAST(35 as STRING) id_estado,
Remover essa coluna.

2021-07-17 13:40 UTC, rdahis commented on bases/br_sp_gov_orcamento/receita_arrecadada/publish.sql
> +from basedosdados-dev.br_sp_gov_orcamento_staging.receita_arrecadada as t
```suggestion
FROM basedosdados-dev.br_sp_gov_orcamento_staging.receita_arrecadada AS t
```

2021-07-17 13:40 UTC, rdahis commented on bases/br_sp_gov_orcamento/despesas/publish.sql
> +from basedosdados-dev.br_sp_gov_orcamento_staging.despesas as t
```suggestion
FROM basedosdados-dev.br_sp_gov_orcamento_staging.despesas AS t
```

2021-07-17 13:40 UTC, rdahis commented on bases/br_sp_gov_orcamento/receita_prevista/publish.sql
> +from basedosdados-dev.br_sp_gov_orcamento_staging.receita_prevista as t
```suggestion
FROM basedosdados-dev.br_sp_gov_orcamento_staging.receita_prevista AS t
```

2021-07-19 18:25 UTC, hevsouza commented
o data check retornou algumas colunas vazias, mas não identifiquei o erro. Copiei tudo pra dev de novo e refiz o processo.

2021-07-20 12:40 UTC, rdahis commented
@hevsouza precisamos identificar esse erro. @d116626 tem alguma ideia?

2021-07-21 02:03 UTC, vncsna commented
Olhando uns logs por cima tem um bug no data check nesta segunda e terceira checagem que não tinha previsto. Nesta última tabela era pra segunda checagem avisar que existe um erro. Jogando as queries no BigQuery nenhuma delas funciona (exceto a primeira), e retornam o seguinte erro:

`Error while reading table: basedosdados-dev.br_sp_gov_orcamento_staging.receita_prevista, error message: Too many values in row starting at position: 116. Found 12 column(s) while expected 7.`

2021-07-21 02:23 UTC, d116626 commented
> Olhando uns logs por cima tem um bug no data check nesta segunda e terceira checagem que não tinha previsto. Nesta última tabela era pra segunda checagem avisar que existe um erro. Jogando as queries no BigQuery nenhuma delas funciona (exceto a primeira), e retornam o seguinte erro:
> 
> `Error while reading table: basedosdados-dev.br_sp_gov_orcamento_staging.receita_prevista, error message: Too many values in row starting at position: 116. Found 12 column(s) while expected 7.`

Esse é o tipico erro de quando uma coluna é removida no `basedosdados-dev` e quando o `table-approve`vai rodar gera uma tabela com menos colunas do que tem no storage

2021-07-21 11:04 UTC, vncsna commented
@d116626 como soluciona este erro?

2021-07-21 12:36 UTC, d116626 commented
> @d116626 como soluciona este erro?

Tem que remover as colunas dos CSVs que estão no storage e recriar a tabela

2021-07-21 20:38 UTC, rdahis commented
@hevsouza pode fazer aqui?

2021-07-26 13:48 UTC, hevsouza commented
@rdahis feito

2021-07-30 13:56 UTC, rdahis approved these changes

2021-07-30 13:57 UTC, merged

2021-07-30 13:57 UTC, rdahis commented
@hevsouza confere por favor se entrou tudo certo em produção!