[dados] Revisão br_inep_sinopse_estatistica_educacao_basica
basedosdados/mais pull request #605
Opened 2021-07-19 18:34 UTC by hevsouza

@rdahis criei uma nova tabela para ficar apenas `matricula`
falta preencher table config

2021-07-20 13:36 UTC, rdahis requested changes
Eu tinha falado com o @mavalentim de trocarmos todas as siglas (tipo `ensino_fund`, `ensino_medio` etc) para `ef`, `em`, `ei`, `ep`. Podemos refazer isso agora já ou deixar para o futuro.

2021-07-20 13:36 UTC, rdahis commented on bases/br_inep_sinopse_estatistica_educacao_basica/matricula/publish.sql
> +SAFE_CAST(ano AS INT64) ano,
Botar `ano` em primeiro.

2021-07-21 19:52 UTC, hevsouza commented
> Eu tinha falado com o @mavalentim de trocarmos todas as siglas (tipo `ensino_fund`, `ensino_medio` etc) para `ef`, `em`, `ei`, `ep`. Podemos refazer isso agora já ou deixar para o futuro.

to refazendo aqui

2021-07-21 20:27 UTC, rdahis commented on bases/br_inep_sinopse_estatistica_educacao_basica/matricula/publish.sql
> +SAFE_CAST(ano AS INT64) ano,
Só faltou isso aqui @hevsouza

2021-07-21 20:52 UTC, hevsouza commented
@rdahis aqui eu mudei nome de coluna também, não da merged ainda não, vou tentar mudar no csv

2021-07-21 20:52 UTC, rdahis commented
> @rdahis aqui eu mudei nome de coluna também, não da merged ainda não, vou tentar mudar no csv

Ok. E faltou preencher o `table_config`.

2021-07-24 16:47 UTC, rdahis requested changes

2021-07-24 16:47 UTC, rdahis commented on bases/br_inep_sinopse_estatistica_educacao_basica/dataset_config.yaml
> +organization: INEP # REQUIRED
Aqui é `br_inep`.

2021-07-24 16:51 UTC, rdahis approved these changes

2021-07-24 16:51 UTC, merged