[dados] mundo_kaggle_olimpiadas
basedosdados/mais pull request #614
Opened 2021-07-21 00:25 UTC by lucasnascm

pessoal, comentem em possíveis melhorias pra nome de variável! aberto a sugestões :)

2021-07-21 00:42 UTC, rdahis requested changes

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/dataset_config.yaml
> +organization: Kaggle # REQUIRED
Aqui é `mundo_kaggle`.

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/dataset_config.yaml
> +    - esporte
Pode tirar `esporte` pois tags não repetem o que já é grupo.

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/microdados/publish.sql
> +SAFE_CAST(idade AS STRING) idade,
Aqui é `INT64`.

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/microdados/publish.sql
> +SAFE_CAST(altura AS STRING) altura,
Aqui é `INT64` (ou `FLOAT64`?)

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/microdados/publish.sql
> +SAFE_CAST(peso AS STRING) peso,
Aqui é `INT64` (ou `FLOAT64`?)

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/microdados/table_config.yaml
> +    <descrição>
Põe uma descriçãozinha aqui pra galera ficar feliz.

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/microdados/table_config.yaml
> +    Download da base e padronização seguindo diretrizes da BD+;
Faltou um `-` para listar.

2021-07-21 00:42 UTC, rdahis commented on bases/mundo_kaggle_olimpiadas/microdados/table_config.yaml
> +    - medalha
Não precisa de medalha aqui, certo?

2021-07-21 00:49 UTC, lucasnascm commented
Acabei de perceber que coloquei `pais_ingles` pra especificar que a variável tava em inglês, mas `esporte` e `modalidade` tb estão. Coloco um `_ingles` ou por especificar no dataset_config que o idioma é inglês, deixa o nome mais simples?

2021-07-21 01:16 UTC, rdahis commented
> Acabei de perceber que coloquei `pais_ingles` pra especificar que a variável tava em inglês, mas `esporte` e `modalidade` tb estão. Coloco um `_ingles` ou por especificar no dataset_config que o idioma é inglês, deixa o nome mais simples?

Bem lembrado. Melhor tirar o `_ingles` de tudo.

2021-07-21 20:38 UTC, rdahis commented
Desculpa @lucasnascm, vamos só botar `idade`, `altura`, `peso` como `INT64` porque parece não haver decimais nunca. Depois aprovamos!

2021-07-22 01:27 UTC, rdahis approved these changes

2021-07-22 01:28 UTC, merged