[dados] inmet_bdmep
basedosdados/mais pull request #622
Opened 2021-07-23 20:41 UTC by filipemsc

2021-07-23 22:17 UTC, lucasnascm commented
@filipemsc tá dando esse erro aqui pra mim: `Access Denied: BigQuery BigQuery: Permission denied while opening file.`

2021-07-23 23:54 UTC, filipemsc commented
> 
> 
> @filipemsc tá dando esse erro aqui pra mim: `Access Denied: BigQuery BigQuery: Permission denied while opening file.`

resolvido!

2021-07-24 01:38 UTC, lucasnascm commented on bases/br_inmet_bdmep/estacoes/publish.sql
> +SAFE_CAST(id_municipio AS STRING) id_municipio
eu alteraria a ordem pra id_municipio, id_estacao, estacao, data_fundacao, latitude, longitude e altitude

2021-07-24 01:38 UTC, lucasnascm commented on bases/br_inmet_bdmep/microdados/publish.sql
> +SAFE_CAST(ano AS STRING) ano
Aqui tb colocaria ano, data, hora, id_estacao e as demais variáveis

2021-07-24 01:38 UTC, lucasnascm commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +
Falta o description aqui ;)

2021-07-24 01:38 UTC, lucasnascm commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +
Aqui já é aquele esquema bullet parecido com o que tu fez no `table_config` de estações

2021-07-24 01:38 UTC, lucasnascm commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +        description: Identificador da estação
Acho que seria válido colocar `ID da estação metereológica` pra manter o padrão do table_config anterior

2021-07-24 16:43 UTC, rdahis requested changes
Bem legal @filipemsc! Botando alguns comentários simples só.

2021-07-24 16:43 UTC, rdahis commented on bases/br_inmet_bdmep/estacoes/publish.sql
> +CREATE VIEW projetos-bd.br_inmet_bdmep.estacoes AS
Vamos renomear essa tabela para `estacao` no singular.

2021-07-24 16:43 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/publish.sql
> +SAFE_CAST(ano AS STRING) ano
Isso aí.

2021-07-24 16:43 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/publish.sql
> +SAFE_CAST(ano AS STRING) ano
`ano` é `INT64`.

2021-07-24 16:43 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/publish.sql
> +SAFE_CAST(temp_bulbo_hora AS FLOAT64) temp_bulbo_hora,
Vamos botar `temperatura` por extenso.

2021-07-24 16:43 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/publish.sql
> +SAFE_CAST(umid_rel_max AS FLOAT64) umid_rel_max,
Botar `umidade` por extenso.

2021-07-24 16:43 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +data_update_frequency: recorrente # REQUIRED
É recorrente ou tem uma periodicidade específica? Não é mensal a atualização?

2021-07-24 16:43 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +        description: Data (YYYY-MM-DD)
Pode tirar esse parêntese dado que tá na definição do tipo do campo.

2021-07-24 16:48 UTC, rdahis commented
@vncsna ou @d116626 sabem dizer que erro é esse nos data checks?

2021-07-24 17:34 UTC, vncsna commented
@rdahis por uma questão de segurança o github actions não usa as variáveis de ambiente em ações que são executadas em forks. Dai ele não tem a senha para acessar o Big Query.

2021-07-24 18:07 UTC, rdahis commented
> @rdahis por uma questão de segurança o github actions não usa as variáveis de ambiente em ações que são executadas em forks. Dai ele não tem a senha para acessar o Big Query.

Hmm saquei. Tem algo que possamos fazer para resolver?

2021-07-24 18:37 UTC, vncsna commented
Por enquanto não tenho nenhuma ideia boa que automatize isso. Talvez um tutorial para que o contribuidor externo saiba como adicionar essas variáveis de ambiente nos seus próprios forks.

2021-07-25 12:34 UTC, rdahis commented
> Por enquanto não tenho nenhuma ideia boa que automatize isso. Talvez um tutorial para que o contribuidor externo saiba como adicionar essas variáveis de ambiente nos seus próprios forks.

Ótimo. Pode abrir um issue com isso por favor? Está afetando o PR #624 também.

2021-07-25 19:11 UTC, filipemsc commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +data_update_frequency: recorrente # REQUIRED
A última atualização foi em 31/04. Não sei bem quando eles atualizam.

2021-07-25 19:33 UTC, vncsna commented
Está na issue #628.

2021-07-25 21:30 UTC, filipemsc commented
acho que incorporei todas as sugestões, galera. só ficou em aberto 1 comentário mesmo. :)

2021-07-26 11:29 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +data_update_frequency: recorrente # REQUIRED
Show. Põe `incerto` então.

2021-07-26 11:32 UTC, rdahis commented
> acho que incorporei todas as sugestões, galera. só ficou em aberto 1 comentário mesmo. :)

Maravilha! Respondi lá. Fechando isso acho que vamos ficar só dependendo de fecharem o issue #628.

2021-07-26 11:33 UTC, rdahis commented on bases/br_inmet_bdmep/estacao/table_config.yaml
> +    - estação meteorológica
```suggestion
    
```

2021-07-26 11:33 UTC, rdahis commented on bases/br_inmet_bdmep/microdados/table_config.yaml
> +    - estação meteorológica
```suggestion
    - brasil
```

2021-07-27 12:18 UTC, rdahis approved these changes

2021-07-27 12:19 UTC, merged