[dados] br_senado_cpipandemia
basedosdados/mais pull request #624
Opened 2021-07-24 05:05 UTC by rfdornelles

Pessoal, 
adicionando os discursos da CPI da Pandemia atualizados até a última sessão disponível.

Fiquei na dúvida se deveriam ser subidos os arquivos raspados (que estão na pasta /input), pois aparentemente eles tavam sendo barrados pelo .gitignore.

Pelo que testei, está rodando normalmente no bigquery

2021-07-24 17:15 UTC, rdahis requested changes
Boa!!

2021-07-24 17:15 UTC, rdahis commented on bases/br_senado_cpipandemia/dataset_config.yaml
> +organization: senado-federal # REQUIRED
```suggestion
organization: br-senado # REQUIRED
```

2021-07-24 17:15 UTC, rdahis commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(sequencial_sessao AS INT64) sequencial_sessao,
```suggestion
SAFE_CAST(sequencial_sessao AS STRING) sequencial_sessao,
```

2021-07-24 17:15 UTC, rdahis commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(horario_inicio_discurso AS DATETIME) horario_inicio_discurso,
Nessas duas variáveis não é pra ser `TIME` não?

2021-07-24 17:15 UTC, rdahis commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(horario_inicio_discurso AS DATETIME) horario_inicio_discurso,
Tem muito missing aparentemente. É isso mesmo?

2021-07-24 17:16 UTC, rdahis commented
Os arquivos raspados eventualmente entrarão no GCP Storage dentro de `/raw`. Não entra no Github não.

2021-07-24 17:23 UTC, rdahis requested changes
Bem maneiro! Como está sendo feita a atualização automática desses dados?

2021-07-24 17:23 UTC, rdahis commented on bases/br_senado_cpipandemia/discursos/table_config.yaml
> +primary_keys:
Não é identificado por:
- sequencial_sessao
- nome_discursante
- horario_inicio_discurso
?

2021-07-24 17:23 UTC, rdahis commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(texto_discurso AS STRING) texto_discurso,
Eu botaria a ordem inicial como:

sequencial_sessao
data_sessao
sigla_partido
sigla_uf_partido
bloco_parlamentar
nome_discursante
genero_discursante
categoria_discursante
texto_discurso
horario_inicio_discurso
horario_fim_discurso
duracao_discurso

2021-07-24 17:55 UTC, rfdornelles commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(horario_inicio_discurso AS DATETIME) horario_inicio_discurso,
Na fase intermediária de limpeza tá como date time mas tá dando erro na hora de salvar .csv. Vou mudar pra time e atualizar aqui

2021-07-24 17:56 UTC, rfdornelles commented on bases/br_senado_cpipandemia/discursos/table_config.yaml
> +primary_keys:
Não tinha pensado nisso! Pode ser sim! Vou alterar

2021-07-24 17:57 UTC, rfdornelles commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(sequencial_sessao AS INT64) sequencial_sessao,
> Bem maneiro! Como está sendo feita a atualização automática desses dados?

Ainda não tá hehe. Mas vou aproveitar que tem mais uns dias antes de voltarem do recesso parlamentar para colocar no github actions. Eu devo fazer no meu repositório, certo?

2021-07-24 18:07 UTC, rdahis commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(sequencial_sessao AS INT64) sequencial_sessao,
Para ficar atualizando na BD acho que tem que ser por actions no nosso repositório (é isso @JoaoCarabetta?)

Que tal você testar no teu repositório e depois passar pra gente o código? Seria bem bom aprendermos a fazer isso porque já podíamos começar a automatizar outras bases.

2021-07-24 19:00 UTC, rfdornelles commented on bases/br_senado_cpipandemia/discursos/publish.sql
> +SAFE_CAST(sequencial_sessao AS INT64) sequencial_sessao,
Beleza, vou tentar!

2021-07-25 12:39 UTC, rdahis approved these changes

2021-07-25 12:39 UTC, merged

2021-07-25 12:53 UTC, rdahis commented
A tabela não foi criada em produção. Discutindo o bug no Discord com @vncsna e @d116626.