[infra] Melhora e adiciona testes para o traceback da função download
basedosdados/mais pull request #626
Opened 2021-07-25 18:36 UTC by vmussa

# Issues e PRs relacionados
*  PR #580 
* Issue #519 

# Descrição breve
Este PR corrige o traceback das funções `download`, `read_sql` e `read_table` e adiciona testes que verificam se cada erro específico está associado ao traceback correto. Como sugerido por @JoaoCarabetta [aqui](https://github.com/basedosdados/mais/issues/519#issuecomment-882939665), dei preferência às exceções do `pandas-gbq`.

## Modificações em `download.py`
* Corrige ordem do bloco `try`/`except` em `read_sql`, colocando as exceções mais específicas primeiro. As mais genéricas estavam no começo, impedindo que as mais específicas aparecessem. 

## Modificações em `test_download.py`
* Isola teste do caso da não especificação de `billing_project_id`
* Adiciona testes para os seguintes erros:
  * `billing_project_id` especificado, porém inválido
  * query inválida: projeto inexistente
  * query inválida: dataset inexistente (`test_download_by_query_*` e `test_download_by_table_*`)
  * query inválida: tabela inexistente (`test_download_by_query_*` e `test_download_by_table_*`)
  * query inválida: erro de sintaxe de SQL

# Possíveis alterações para este PR
* Fazer um teste para o caso de `billing_project_id` cujo acesso é negado. Não sei qual ID usar para esse caso. Alguém tem uma ideia?
* Melhorar exceções em `read_sql`: atualmente o caso do acesso negado aponta para uma `BaseDosDadosException` que indica que o usuário ainda não tem um projeto. Será que isso faz sentido ou deveriamos, aqui, dar preferência ao erro do `pandas-gbq`?

2021-07-25 21:34 UTC, JoaoCarabetta requested changes

2021-07-25 21:34 UTC, JoaoCarabetta commented on python-package/tests/test_download.py
> +def test_download_no_billing_project_id():
Acho que os problemas de `traceback` estão associados à função de `read_sql`. A função de `download` só chama a `read_sql`. Então, faz mais sentido testar a `read_sql` direto.

2021-07-25 21:37 UTC, JoaoCarabetta commented
> Fazer um teste para o caso de billing_project_id cujo acesso é negado. Não sei qual ID usar para esse caso. Alguém tem uma ideia?

Como o projeto é público, acho que todos os `billing_ids` serão permitidos. Então, não sei se vale a pena testar para isso.

> Melhorar exceções em read_sql: atualmente o caso do acesso negado aponta para uma BaseDosDadosException que indica que o usuário ainda não tem um projeto. Será que isso faz sentido ou deveriamos, aqui, dar preferência ao erro do pandas-gbq?

Eu acho que é bom ter um tutorial no caso de o usuário não ter feito o cadastro corretamente, mas precisamos talvez precisamos especificar melhor a exception que captura isso. Hoje, as duas exceções do `read_sql` retornam o tutorial, o que não faz muito sentido.

2021-07-26 18:52 UTC, vmussa commented
@JoaoCarabetta certo, farei as alterações! Sobre o acesso negado me refiro do lado do cliente mesmo, para o caso dele escolher um `billing_project_id` privado de outro usuário. Nesses casos o `pandas-gbq` retorna uma exceção que indica "Access denied", ou algo assim. Mas talvez seja irrelevante... rs

2021-07-27 01:50 UTC, vmussa commented
Adicionei tutoriais novos a partir das exceptions `GenericGBQException`, `PyDataCredentialsError` e `ValueError`. Eles contêm instruções específicas para os possíveis erros do `read_sql`/`download`/`read_table` (erro de autenticação/autorização, erro de `billing_project_id` e de configuração/criação do projeto no BQ). Atualizei os testes para dar conta das novas exceptions.
Decidi deixar o traceback padrão da `GenericGBQException` para os erros de query, assumindo que os usuários que usam SQL diretamente são capazes de interpretar a exceção da API do Google, que, embora seja sintética, é muito clara.

2021-07-27 18:40 UTC, d116626 commented
@vmussa  e @JoaoCarabetta, será que n vale colocar as todas essas mensagens de exeption em validation/exeptions.py e só ir chamando de lá?

2021-07-27 20:41 UTC, vmussa commented
@d116626 e aí a gente declararia as variáveis com as mensagens fora da classe `BaseDosDadosException` e chamaria a exceção cada hora com uma mensagem diferente? Tipo:

```python
from from basedosdados.validation.exceptions import BaseDosDadosException, msg1, msg2, msg3
if x:
    BaseDosDadosException(msg1)
elif y:
    BaseDosDadosException(msg2)
else:
    BaseDosDadosException(msg3)
```

Ou tem algum jeito de fazer uma exceção guardar várias mensagens padrão no interior da própria classe?

2021-07-28 17:27 UTC, JoaoCarabetta commented
Bom ponto. Meus comentários:

1. Acho que podemos renomear a pasta para  `exceptions`, ou mesmo ter um arquivo chamado `exceptions.py` que contém as exceções que usaremos. 
2. É uma boa em quesito de organização, pq futuramente podemos expandir o `BaseDosDadosException` para casos mais particulares: `BaseDosDadosInvalidCredentialsException`, etc...

2021-07-29 16:10 UTC, vmussa commented
@JoaoCarabetta removi a pasta `validate` e adicionei um arquivo `exceptions.py` no diretório root, como combinamos. Nele, eu fiz uma exception pra cada tipo de erro do usuário, todas herdam da `BaseDosDadosException` e carregam uma mensagem padrão específica para seus respectivos erro.

2021-07-29 16:13 UTC, JoaoCarabetta approved these changes

2021-07-29 16:13 UTC, JoaoCarabetta commented
Perfeito! Vou jogar para a 1.5.6 e hoje podemos fazer o release

2021-07-29 16:13 UTC, merged