[dados] br_me_cno
basedosdados/mais pull request #668
Opened 2021-08-04 23:15 UTC by gustavoairestiago

2021-08-09 13:41 UTC, crislanealves commented on bases/br_me_cno/dataset_config.yaml
> +
aqui é ``ministerio-da-economia`` eu acho

2021-08-09 13:44 UTC, crislanealves commented on bases/br_me_cno/dataset_config.yaml
> +    email:
Aqui pode ser ``Receita Federal``

2021-08-09 13:51 UTC, crislanealves commented on bases/br_me_cno/dataset_config.yaml
> +
construção*

2021-08-09 13:52 UTC, crislanealves commented on bases/br_me_cno/microdados/table_config.yaml
> +    - Alteração de tipo de variável (int de identificadores para string)
variáveis

2021-08-09 13:52 UTC, crislanealves commented on bases/br_me_cno/microdados/table_config.yaml
> +    - Alteração de nome das variáeis
variáveis

2021-08-09 13:53 UTC, crislanealves commented on bases/br_me_cno/microdados/table_config.yaml
> +    - Inculsão da variável id_municipio
Inclusão

2021-08-09 13:56 UTC, crislanealves commented on bases/br_me_cno/microdados_cnae/table_config.yaml
> +    - Alteração de nome das variáeis
variáveis

2021-08-09 13:59 UTC, crislanealves commented on bases/br_me_cno/microdados_vinculo/table_config.yaml
> +    - Alteração de nome das variáeis
variáveis

2021-08-09 14:14 UTC, crislanealves reviewed
@gustavoairestiago, ficou muito bom aqui, parabéns! Por enquanto só algumas pequenas correções. 

Queria depois que você desse uma olhada:

1. na descrição das tabelas. Porque o dataset e todas as tabelas estão com a mesma descrição; e,
2. na variável ``ni_responsável``. Na tabela ``microdados`` todos terminam com ``.0`` e na ``microdados_vinculos`` não. Os dados originais são assim mesmo?

2021-08-09 14:29 UTC, rdahis commented on bases/br_me_cno/dataset_config.yaml
> +
`br-me`

2021-08-09 21:13 UTC, gustavoairestiago commented on bases/br_me_cno/dataset_config.yaml
> +
Corrigido!

2021-08-09 21:13 UTC, gustavoairestiago commented on bases/br_me_cno/dataset_config.yaml
> +    email:
Corrigido!

2021-08-09 22:37 UTC, gustavoairestiago commented on bases/br_me_cno/dataset_config.yaml
> +
Modificado!

2021-08-09 22:37 UTC, gustavoairestiago commented on bases/br_me_cno/microdados/table_config.yaml
> +    - Alteração de nome das variáeis
Modificado!

2021-08-10 11:31 UTC, rdahis requested changes

2021-08-10 11:31 UTC, rdahis commented on bases/br_me_cno/dataset_config.yaml
> +organization: Ministério da Economia # REQUIRED
```suggestion
organization: br-me # REQUIRED
```

2021-08-10 11:31 UTC, rdahis commented on bases/br_me_cno/microdados/publish.sql
> +SAFE_CAST(area AS STRING) area
Aqui não deveria ser `FLOAT64`?

2021-08-10 11:31 UTC, rdahis commented on bases/br_me_cno/microdados/table_config.yaml
> +observation_level: #REQUIRED
Aqui acho que é só `obra`, não?

2021-08-10 11:31 UTC, rdahis commented on bases/br_me_cno/microdados_cnae/table_config.yaml
> +observation_level: #REQUIRED
Aqui é:
```
- obra
- cnae_2
```

2021-08-10 11:31 UTC, rdahis commented on bases/br_me_cno/microdados_cnae/table_config.yaml
> +primary_keys:
Seria `id_cno` e `cnae_2`, não?

2021-08-10 11:31 UTC, rdahis commented on bases/br_me_cno/microdados_vinculo/table_config.yaml
> +observation_level: #REQUIRED
Aqui é talvez `vinculo`?

2021-08-10 11:31 UTC, rdahis commented on bases/br_me_cno/microdados_vinculo/table_config.yaml
> +primary_keys:
`id_cno`
`data_inicio`
`ni_responsavel`
talvez?

2021-08-10 12:06 UTC, gustavoairestiago reviewed
Atualizado - Comentários rdahis

2021-08-10 14:50 UTC, gustavoairestiago reviewed
Feito!

2021-08-11 11:36 UTC, rdahis approved these changes

2021-08-11 11:36 UTC, merged