[dados] br_ms_sinasc
basedosdados/mais pull request #716
Opened 2021-08-18 02:18 UTC by lucasnascm

2021-08-20 19:39 UTC, crislanealves commented on bases/br_ms_sinasc/microdados/table_config.yaml
> +
Não esquece de alterar aqui depois.

2021-08-20 19:43 UTC, crislanealves commented on bases/br_ms_sinasc/microdados/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
tira o ``<descrição da coluna>``

2021-08-20 19:45 UTC, crislanealves commented on bases/br_ms_sinasc/microdados/table_config.yaml
> +        is_in_staging: True # Bool [True, False], whether the column is in the staging table
tira o ``<descrição da coluna>``

2021-08-30 12:14 UTC, rdahis requested changes

2021-08-30 12:14 UTC, rdahis commented on bases/br_ms_sinasc/microdados/table_config.yaml
> +observation_level: #REQUIRED
Aqui é `nascimento`, certo?

2021-08-30 12:14 UTC, rdahis commented on bases/br_ms_sinasc/microdados/table_config.yaml
> +        name: estado_civil
`estado_civil_mae`

Tem que botar sufixos sempre que a entidade da coluna for diferente da entidade da tabela.

2021-08-30 12:14 UTC, rdahis commented on bases/br_ms_sinasc/microdados/table_config.yaml
> +        name: ocupacao
`ocupacao_mae`

2021-09-12 12:48 UTC, closed without merging

2021-09-12 12:48 UTC, lucasnascm commented
Tentei subir as alterações, mas deu um erro aqui! Fechando e criando uma branch com os dados corrigidos