[dados] br_inep_ana
basedosdados/mais pull request #725
Opened 2021-08-23 11:56 UTC by lucasnascm

2021-08-23 12:12 UTC, rdahis commented
Tirando onda nesse data check hein @lucasnascm!

2021-08-23 12:13 UTC, rdahis commented on bases/br_inep_ana/aluno/table_config.yaml
> +    - id_aluno
```suggestion
    - pessoa
```

2021-08-23 12:37 UTC, lucasnascm commented on bases/br_inep_ana/aluno/table_config.yaml
> +    - id_aluno
Segui a nomenclatura da base do saeb (até pq tem uma ligação entre as bases). Embora o censo esteja `id_pessoa_fisica`. A gente podia ver um padrão pra isso

2021-08-30 12:21 UTC, rdahis commented on bases/br_inep_ana/aluno/table_config.yaml
> +    - id_aluno
O que resolvemos aqui mesmo?

2021-08-30 12:22 UTC, lucasnascm commented on bases/br_inep_ana/aluno/table_config.yaml
> +    - id_aluno
Mantém `id_aluno`

2021-08-30 12:29 UTC, rdahis commented on bases/br_inep_ana/aluno/table_config.yaml
> +    - id_aluno
Ah não lembrei. Em `observation_level` botamos `pessoa`. Em `primary_keys` fica `id_aluno`.

2021-08-30 14:13 UTC, rdahis approved these changes

2021-08-30 14:23 UTC, rdahis requested changes

2021-08-30 14:23 UTC, rdahis commented on bases/br_inep_ana/prova/publish.sql
> +SAFE_CAST(id_bloco AS STRING) id_bloco,
As 4 variáveis abaixo devem não ter `id_` como prefixo. Guardamos esse prefixo para IDs de entidades eventualmente em diretórios.

2021-08-30 14:23 UTC, rdahis commented on bases/br_inep_ana/prova/publish.sql
> +SAFE_CAST(id_bloco AS STRING) id_bloco,
Tem que mudar também no dicionário, possivelmente.

2021-08-30 14:23 UTC, rdahis commented on bases/br_inep_ana/prova/table_config.yaml
> +observation_level: #REQUIRED
Aqui seria `questão`?

2021-08-30 14:23 UTC, rdahis commented on bases/br_inep_ana/escola/table_config.yaml
> +observation_level: #REQUIRED
Aqui seria `escola`

2021-08-31 12:26 UTC, rdahis approved these changes

2021-08-31 12:26 UTC, merged