[dados] br_bd_diretorios_brasil
basedosdados/mais pull request #920
Opened 2021-11-03 00:23 UTC by gustavoairestiago

Tabela de grandes regiões brasileiras

2021-11-03 00:39 UTC, rdahis requested changes
Seria bom já subir essa tabela com o CLI 1.6 Beta pra você praticar @gustavoairestiago.

2021-11-03 00:39 UTC, rdahis commented on bases/br_bd_diretorios_brasil/regiao/publish.sql
> +SAFE_CAST(sigla_regiao AS STRING) sigla_regiao,
Mudar para `sigla`.

2021-11-03 00:39 UTC, rdahis commented on bases/br_bd_diretorios_brasil/regiao/publish.sql
> +SAFE_CAST(regiao AS STRING) regiao
Mudar para `nome`.

2021-11-03 00:42 UTC, gustavoairestiago commented on bases/br_bd_diretorios_brasil/regiao/publish.sql
> +SAFE_CAST(regiao AS STRING) regiao
@rdahis Eu tinha colocado nome, mas fui conferir como estava na tabela municipios e as regiões estavam na coluna "regiao"... Como faremos?

2021-11-03 00:43 UTC, gustavoairestiago commented on bases/br_bd_diretorios_brasil/regiao/publish.sql
> +SAFE_CAST(regiao AS STRING) regiao
Acho que o correto seria trocar em municipio para "sigla_regiao"... e "nome" nessa tabela

2021-11-03 11:49 UTC, rdahis commented on bases/br_bd_diretorios_brasil/regiao/publish.sql
> +SAFE_CAST(regiao AS STRING) regiao
Exato. Na tabela `municipio` vira `nome_regiao`/`sigla_regiao`. Aqui fica só `nome` e `sigla`.

2021-11-03 14:51 UTC, gustavoairestiago commented
@rdahis Feito!

2021-11-04 01:24 UTC, rdahis approved these changes

2021-11-04 01:25 UTC, merged